### ISSUE TITLE
up arrow not showing history

### ISSUE THREAD

**Issue by rramsey** [cbucher/console#113]
This may be me being stupid, but when I press the up arrow, it doesn't show my command history.  It scrolls up the window.  And I can't see a place in the hotkey settiings to change it.  To reproduce:

> dir c:\
> folders scroll by
> press up arrow, window scrolls up 

Expected behavior:

> dir c:\
> folders scoll by
> press up arrow, then "dir c:\" is entered at the prompt.

It works from within a regular command prompt.  Do I need to explicitly set the shell to windows command shell?  I thought I already was because this is at the top of the window when I open console:

Microsoft Windows [Version 6.3.9600](c) 2013 Microsoft Corporation. All rights reserved.

This is running on Windows 8.1 Update 1, 64 bit, ConsoleZ 1.10.0.14089
Thanks!

**Comment by GJKrupa** [comment]
I had the same issue and it had me scratching my head for a minute or 2.  It's caused by having Scroll Lock active.  Just hit the Scroll Lock/ScrLk key again to clear it - no reboot required.

**Comment by Rudde** [comment]
@GJKrupa I experience this issue, and even with Scroll lock disabled
