### ISSUE TITLE
CTRL + Click opens a Url

### ISSUE THREAD

**Issue by Trias-at-work** [cbucher/console#123]
It would be great if ConsoleZ could implement a feature like the terminal on Mac OS X. If you do a cmd + Double-Click on a Url, it will open the link in the browser (if it is a link).

I find this feature very helpful for debugging and logging. Do you think you could implement it or a similar feature in ConsoleZ? That would be much appreciated :).

**Comment by Coochik** [comment]
Hey! What would you think about rendering Web links underlined when hovering them? Clicking is great, but will be nice to know what are you clicking on.

**Comment by cbucher** [comment]
As it is currently specified, I don't know it is a clickable link before you clicked on.
When "click link" command is used, link is defined by word selection.

You can open a new issue, providing an alternate specification or contribute to source code.

**Comment by Coochik** [comment]
Ok, makes sense! I'll look into code.
