### ISSUE TITLE
Save current views, close the application, and then restore views

### ISSUE THREAD

**Issue by kevinrood** [cbucher/console#127]
I would like to open a series of views (split) in a single tab to work on a particular project, then save this information (each view's working directory, view size, view location). I would then like to open this series of views again after closing the application (probably from a menu item).

**Comment by postromantic** [comment]
Yep, it would be nice to have a 'Auto save/restore opened tabs' checkbox in settings. Similar to ConEmu (https://github.com/Maximus5/ConEmu)

**Comment by brentonhouse** [comment]
+1

**Comment by HwapX** [comment]
+1

**Comment by DerellLicht** [comment]
+1, most definitely.  At work, I often have 6 or 8 tabs open; having to manually re-open and do CDs is very grinding...

**Comment by cbucher** [comment]
part of the workspace specification #274
