### ISSUE TITLE
Use DirectWrite for Font Rendering

### ISSUE THREAD

**Issue by CoolOppo** [cbucher/console#134]
It would be fantastic if DirectWrite was supported for font rendering! It is noticeably crisper than that of any other font rasterizer I have seen.

I threw together a comparison in Sublime Text; it supports DirectWrite, but oddly it's disabled by default. Take a look:

#### GDI:
![](http://i.imgur.com/gWrhB1Z.png)

#### DirectWrite:
![](http://i.imgur.com/eZefJJh.png)

**Comment by cbucher** [comment]
http://www.beatstamm.com/typography/RTRCh4.htm

![image](https://cloud.githubusercontent.com/assets/363759/9609614/f35f9f6a-50d4-11e5-9530-c54b98943cea.png)

Your top picture shows a simple anti-aliased smoothing:
![image](https://cloud.githubusercontent.com/assets/363759/9609841/4ab2214c-50d6-11e5-88ef-26940eb256a0.png)


Your bottom picture shows a cleartype smoothing:
![image](https://cloud.githubusercontent.com/assets/363759/9609832/38ffdb60-50d6-11e5-8fde-ac5f6a032371.png)

You demonstrate no gain with DirectWrite. ClearType is available with GDI.

You must provide pictures comparing ClearType Fractional width and ClearType Natural width to justify the usage of DirectWrite.
