### ISSUE TITLE
Vote for new icon for ConsoleZ

### ISSUE THREAD

**Issue by gordlea** [cbucher/console#163]
I've been thinking that ConsoleZ could use a new, more modern icon.

I submit my proposal, and invite other to submit icons to vote on.

**Note**: Final icon should be HighDPI aware.

Here is my entry:

![icons2](https://cloud.githubusercontent.com/assets/782154/5428820/b10ead6a-8387-11e4-8ab7-4d74774f5c66.png)

![icons3](https://cloud.githubusercontent.com/assets/782154/5428821/b48e4284-8387-11e4-97e5-1d7e04e1349d.png)

**Comment by gordlea** [comment]
Nice work on the HighDPI support.

**Comment by cbucher** [comment]
Just a reminder: new icon must contain the following sizes (in pixels):
16x16   20x20   24x24   32x32
48x48   60x60   72x72   96x96
256x256

**Comment by gordlea** [comment]
@cbucher: Not sure where we are on this, but I created a pull request #174  that includes the new icon.

**Comment by cbucher** [comment]
before
![image](https://cloud.githubusercontent.com/assets/363759/6183689/9516c8c6-b358-11e4-971e-2bad237b4b05.png)

after
![image](https://cloud.githubusercontent.com/assets/363759/6183693/9f9f8c74-b358-11e4-8ea8-c97ebc05a527.png)
