### ISSUE TITLE
Launching Console at startup - DLL injection has failed

### ISSUE THREAD

**Issue by krypsin** [cbucher/console#168]
Have been using ConsoleZ for a while and must say that it's pretty damn awesome.

Only problem I have is launching it from startup.
About 90% of the time I'll get this error in this screenshot:
![ss 2015-01-21 at 08 33 35](https://cloud.githubusercontent.com/assets/8135396/5833193/4fbd87b4-a148-11e4-9a24-22031102f237.png)
    Error
        DLL injection has failed (reason:timeout)!

It's rare that ConsoleZ will start automatically without an issue.

I'm guessing it's probably caused by the fact that the default shell I use is Cygwin bash.

I've tried adding Console to registry values for startup (rather than just putting it in the Startup folder), but still gives same results.

Any help with this would be amazing as it's quite a pain

**Comment by cbucher** [comment]
Sorry, but you provide zero information...

no ConsoleZ version,  no OS version, no configuration, nothing !

**Comment by krypsin** [comment]
Apologies.

OS: Windows 7 SP1 x64
ConsoleZ: Version 1.12.0.14282
ConsoleZ config: http://pastebin.com/y0azdTGD

**Comment by cbucher** [comment]
What is the version of cygwin batch ?
How do you configured startup ?
Is cygwin bash crashing at startup ?
Do you have the same problem if you replace bash by cmd ?

**Comment by pietrok** [comment]
I am getting the same dll injection error. I've had consoleZ working on the same version of windows (7 SP1) but I think I was using 32-bit Cygwin. 

GNU bash, version 4.1.17(9)-release (x86_64-unknown-cygwin)

**Comment by cbucher** [comment]
@pietrok
This issue describes a timeout when ConsoleZ is launched automatically at startup.
If you have systematically this error then verify your antiviral software log.

@krypsin @pietrok 
Install the [last version of ConsoleZ](https://github.com/cbucher/console/wiki/Downloads
) (>= 1.13.0.15040).
Error message should indicate which waiting operation is in timeout.

**Comment by cbucher** [comment]
timeout....
