### ISSUE TITLE
Legacy package doesn't start on XP

### ISSUE THREAD

**Issue by oscarfv** [cbucher/console#169]
I downloaded and unzipped the legacy package

https://github.com/cbucher/console/releases/download/1.12.0/ConsoleZ.1.12.0.14282.7z

I used the `Win32/Release` binaries. When I try to execute it a message popup appears saying that it is not a valid Win32 application.

Windows XP SP3 32 bits.

**Comment by cbucher** [comment]
#158 duplicated issue
