### ISSUE TITLE
Does it support multibyte language or UTF8?

### ISSUE THREAD

**Issue by liuyug** [cbucher/console#172]
HI,

My window 7 pro is chinese version. The default codepage is cp932. It is multibytes encoding.
In consoleZ all chinese characters are overlapped and ascii characters are normal.

Does it support multibyte language or UTF8?

**Comment by cbucher** [comment]
932 is japanese default codepage.

You just have to select an Unicode font
![image](https://cloud.githubusercontent.com/assets/363759/5996866/25c20cdc-aab2-11e4-9d25-058bb90f7087.png)

**Comment by liuyug** [comment]
Chinese codepage is cp936. 

Follow help guide, I have fixed encoding error. Thanks.

**Comment by FrankFan** [comment]
there is the same question for me.
![image](https://cloud.githubusercontent.com/assets/1589433/7018728/864068f0-dd3a-11e4-800c-27ff2e37a279.png)

the version is the latest: [download from wiki](https://github.com/cbucher/console/wiki/Downloads)

ConsoleZ is my favourite console in win7, but recently this promblem puzzled me. 
your suggestion I've tried, but failed.

### first: 
in my `regedit`, there was not a subkey named "ConsoleZ command window" at all.
![image](https://cloud.githubusercontent.com/assets/1589433/7018826/d9d0cde2-dd3b-11e4-9d2f-97e2fe2a7db5.png)


### second:  
![image](https://cloud.githubusercontent.com/assets/1589433/7018784/5413b2dc-dd3b-11e4-8d00-345f039e2065.png)
`Click OK. you may get a dialog saying that required files are already installed on the hard disk.`  NOT LIKE THIS.

### third:  I cannot go further. :-(

can you help me fix this ?

**Comment by FrankFan** [comment]
sorry to bother.

finally I find a solution to fix Chinese mulitiybte, multi Character

![image](https://cloud.githubusercontent.com/assets/1589433/7020772/4ed63d36-dd4e-11e4-82ad-cd69ea8e7cb6.png)



```shell
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Console\ConsoleZ command window]
"CodePage"=dword:000003a8
"FontSize"=dword:000a0000
"FontFamily"=dword:00000036
"FontWeight"=dword:00000190
"FaceName"="Consolas"
"HistoryNoDup"=dword:00000000
```

**Comment by wxiangbo** [comment]
nice!

**Comment by saleo** [comment]
@FrankFan ， thank you for the solution!

**Comment by SgLy** [comment]
@FrankFan Many thanks for your solution!

**Comment by gb112211** [comment]
@FrankFan good！

**Comment by xjsXjtu** [comment]
Thanks, FrankFan. It works for me.

**Comment by eslizn** [comment]
very good

**Comment by yellowiscool** [comment]
It also fixes the Powerline fonts :smile:

**Comment by Jessypp** [comment]
Thanks,@FrankFan
