### ISSUE TITLE
Drawing issues with tmux

### ISSUE THREAD

**Issue by davidknaack** [cbucher/console#175]
I'm running into a text drawing issue when I'm using tmux in a terminal. It seems to mostly be a text wrapping issue.

I am running git-bash as my shell (I haven't tested with cmd). I ssh into a linux VM, and then run tmux. I split the screen and adjust the split so that I have a narrow panel (22 cols wide) on the right. When I issue commands in the narrow panel that cause output that wraps, the text that ConsoleZ renders is not correctly wrapped to the pane, it wraps all the way around and draws on the left side of the left panel, and also writes text on the left-hand pane border line.

If I bring up mintty and attach to the same tmux session so that the output is mirrored in both terminals, the output is rendered correctly in mintty. It seems like maybe a control code isn't being caught or handled in a way that lets these tmux pane work.

Edit: It occured to me to unhide the console window, since that's where the text is. Clearly the issue is not ConsoleZ, and probably isn't something that can be addressed with a change to ConsoleZ. However, since it affects display inside ConsoleZ, I wonder if you may have run into it before and know either which piece of software is the problem, or may know of a fix.

**Comment by cbucher** [comment]
I think I need a picture.

The output wraps because the console width is too small?
(Verify the count of columns in mintty and Windows Console.)

Otherwise the ansi escaping is misinterpreted.
Verify if the ansi escaping is handled by ssh or bash.
(Try using cmd.exe)

**Comment by davidknaack** [comment]
Here are images of the problem. On the left is mintty, ConsoleZ on the right, using a git-bash or cygwin session.
In the first windows I ssh into a linux server and start tmux. In the second I ssh in to the same server and tmux attach to that session. The output is cloned to both terminals (the behavior of each terminal is the same if I do them separately, it's just easier to compare when cloning).

I split the window with tmux, and do 'ls -la' or lsof in the right-hand panel. You can see that in the mintty console on the left the line wrapping is correct, but the wrapping in the console that ConsoleZ is showing, on the right, is wrong.

http://i.imgur.com/eQxOLS4.png

Longer lines output by lsof makes it easier to see how it's wrapping to the far left:

http://i.imgur.com/FTbgXoz.png

Something is definitely not handling ansi escape sequences correctly. So I spent some more time screwing around with it. Your question about what is handling the sequences lead me through a series of steps that involved looking at $TERM at various points, which in turn lead me to a fix:

In ConsoleZ set the shell to the cygwin.bat (C:\cygwin64\Cygwin.bat) file. After it starts, start 'screen' (may need to install with cygwin installer).

Now when I ssh to my target server and start tmux the escape sequences are handled correctly, and that means that finally I can have both a correctly-rendered tmux session, and also see my desktop background! 

http://i.imgur.com/3Ei5dCb.png

So, I guess consider this closed, maybe it'll help the next guy who comes searching for this problem.

**Comment by cbucher** [comment]
ok, thank you for sharing your solution.

>In ConsoleZ set the shell to the cygwin.bat (C:\cygwin64\Cygwin.bat) file. After it starts, start 'screen' (may need to install with cygwin installer).

**Comment by AdamReece-WebBox** [comment]
Thanks for sharing your answer @davidknaack. I did try this out as per #503, though I'm finding this problem only happens when TMUX is run on a Ubuntu 18.04 system. (Works great on Debian 9.9.)

Using `screen` within the Linux VM works though, saves a process on your host system or needing to install screen in Cygwin.

ConsoleZ -> SSH -> Screen -> TMUX

**Comment by jvd10** [comment]
> Using `screen` within the Linux VM works though, saves a process on your host system or needing to install screen in Cygwin.

This is great!  The workaround of running tmux inside of screen seems to fix the text reflowing and resizing issues.

Issues like this have plagued me for years in various combinations of ssh, osx and linux; I really wish that I would have thought of this earlier.  I swear I've messed around with setting XTERM, etc, etc, without ever really fixing it (or then messing up the behavior of vim or some other thing.)  This workaround is nice and easy and seems to just work.
