### ISSUE TITLE
Tabs and icons too small

### ISSUE THREAD

**Issue by char101** [cbucher/console#176]
I think some of the icons and the tabs looks too narrow vertically (changeset b45f10e, Release Legacy x64, Visual Studio 2013). I'm using a standard 96 DPI monitor.

![2](https://cloud.githubusercontent.com/assets/71255/6242543/eef33bea-b763-11e4-983d-8015d00acff5.png)

**Comment by char101** [comment]
As a comparison this is how it previously looks like

![3](https://cloud.githubusercontent.com/assets/71255/6242553/105b64f6-b764-11e4-988e-67974370c30f.png)

**Comment by char101** [comment]
I think the tabareaheight computation should be `::GetSystemMetrics(SM_CYSMICON) + 8` (24 - 16) instead of `+ 4`.

**Comment by cbucher** [comment]
![image](https://cloud.githubusercontent.com/assets/363759/6244203/430d37b2-b750-11e4-9a0c-026b212583d3.png)

Yes height of tabs has been reduced. I decided to expand the console view.
Nobody complains during development or long beta test (at least 400 downloads).
And you are only one since the release version as been published.

**Comment by char101** [comment]
So it is intentional.
I'm not complaining since I can modify and compile it myself, but IMO 4 pixels reduction does not really matter. To expand the console area it's easier to put the toolbar in the same row with the menubar.
For general use I think it's better to stick with the normal size, i.e. 24 pixels.

**Comment by cbucher** [comment]
> To expand the console area it's easier to put the toolbar in the same row with the menubar.
For general use I think it's better to stick with the normal size, i.e. 24 pixels.

28 is always better than 24
People who count pixels usually hide "futile" bars (menu/toolbar/status).
