### ISSUE TITLE
Can't open bash shell

### ISSUE THREAD

**Issue by Pajamaman** [cbucher/console#177]
I created a tab with the following shell setting:

    "C:\Program Files (x86)\Git\cmd\git.exe" -r "--login -i"

Screenshot:

![image](https://cloud.githubusercontent.com/assets/1323271/6339646/1fc77a32-bb75-11e4-98b4-bdf8e206b2de.png)

Yet when I open a new bash tab it immediately closes, like it doesn't respect the command line arguments. Am I doing something wrong or is this a bug?

I can't find the documentation, but I found this usage of the -r command line argument here: https://github.com/cbucher/console/issues/82

**Comment by cbucher** [comment]
Please read the documentation.
The -r flag is a ConsoleZ (console.exe) command line parameter (not a git.exe command line parameter).

**Comment by Pajamaman** [comment]
That doesn't explain why this doesn't work either:

    "C:\Program Files (x86)\Git\cmd\git.exe" --login -i

And, like I said, what documentation?
