### ISSUE TITLE
Where's the documentation?

### ISSUE THREAD

**Issue by Pajamaman** [cbucher/console#178]
This is what I see when I try to view the help files:

![image](https://cloud.githubusercontent.com/assets/1323271/6353007/d25809d0-bc03-11e4-95a7-5d8123677012.png)

Does the documentation live online somewhere? Or is the help viewer broken?

**Comment by cbucher** [comment]
Yes, this is the documentation.

Try this: http://www.xyplorer.com/faq-topic.php?id=chm

**Comment by Pajamaman** [comment]
That fixed it. Thanks.
