### ISSUE TITLE
Tab console cursor color missing

### ISSUE THREAD

**Issue by corvannoorloos** [cbucher/console#181]
Hello,

Even though the setting is available in the `console.xml` file after selecting the "Console" cursor style, the cursor color isn't available from the program settings.

```xml
<cursor style="12" r="255" g="255" b="255"/>
```

![28-2-2015 3-09-32](https://cloud.githubusercontent.com/assets/1499293/6424320/43462668-bef7-11e4-980b-8bb323951816.png)

Manually editing the `console.xml` cursor color doesn't reflect any changes.

**Comment by cbucher** [comment]
This cursor mimics Windows console cursor ... so the color is defined by xor background color.

By the way, thank you for screenshot: I found an anomaly (#182).

**Comment by corvannoorloos** [comment]
> This cursor mimics Windows console cursor

:+1:

Though I think the wrong default might have been selected? As far as I know the default Win7 cursor background color is `#c0c0c0`, instead of `#fff`.

**Comment by cbucher** [comment]
you're right it should be 0xc0c0c0 xor background instead of 0xffffff xor background

**Comment by corvannoorloos** [comment]
Still have to compile it, but thanks again!

**Comment by corvannoorloos** [comment]
@cbucher in the experimental version running ConsoleZ the cursor has been updated. The `console.xml` is still showing white:
```xml
<cursor style="12" r="255" g="255" b="255"/>
```

**Comment by cbucher** [comment]
white on black
![image](https://cloud.githubusercontent.com/assets/363759/6479195/b5994fd6-c241-11e4-9dc2-4d1b7634d889.png)

yellow on blue
![image](https://cloud.githubusercontent.com/assets/363759/6479167/17d77278-c241-11e4-8034-d6f51808c4ec.png)

magenta on green
![image](https://cloud.githubusercontent.com/assets/363759/6479174/4ac18624-c241-11e4-8e5a-91ee9387003a.png)

red on cyan
![image](https://cloud.githubusercontent.com/assets/363759/6479180/67340fc0-c241-11e4-962c-c103e5119044.png)

cyan on red
![image](https://cloud.githubusercontent.com/assets/363759/6479188/923e5a86-c241-11e4-9efb-70fdeddab4e8.png)

...

mimics Windows console cursor

**Comment by corvannoorloos** [comment]
@cbucher I've definitely noticed. Thanks!

The main reason I'm asking is I'm using [git](https://github.com/corvannoorloos/console) to track the changes made to my `console.xml`, which cursor colors aren't getting updated after restarting ConsoleZ.

white on black
```xml
<cursor style="12" r="255" g="255" b="255"/>
```

yellow on blue
```xml
<cursor style="12" r="255" g="255" b="255"/>
```

etc.

**Comment by cbucher** [comment]
the cursor is not blank, it's 0xc0c0c0 xor background
cursor color settings are ignored for this specific cursor (they have no use and no sense)

r,g and b attributes have a default value: 255
you can omit these attributes, but they will be written each time you modify your settings

My suggestion: modify the settings with ConsoleZ and stop to edit the configuration file by yourself
