### ISSUE TITLE
Edit/Settings/Tabs/Shell field content is lost after filling the Startup dir

### ISSUE THREAD

**Issue by mihaiolteanu** [cbucher/console#184]
I'm adding a new tab configuration from Edit/Settings/Tabs. 

If, when filling the **Shell** field I copy/paste the path from another location and *not* using the browse option, when I browse for the **Startup dir** and chose a location, the Shell field is lost (i.e. deleted). 

Tests steps:
1. Open Edit/Settings/Tabs
2. Add (new tab)
3. Browse for shell path
4. Copy shell path from the text field (automatically filled after previous step)
5. Delete the tab
6. Add (new tab)
7. Paste the previous copied text into the Shell text field
8. Browser for a Startup dir
9. After choosing a Startup dir, the Shell text field is lost

The Shell text field at step 7 is valid, because it was obtained with the browse option. If I follow the step 3 with step 8 and 9, the Shell text field is not lost.

The same issue is present in [bozho/console] (https://github.com/bozho/console) as well.

Edit: Same issue is present in Edit/Settings/Console when choosing the Startup dir.

**Comment by cbucher** [comment]
Try last [experimental version 1.14.0.15071](https://dl.dumptruck.goldenfrog.com/p/MFMLht6iWV/ConsoleZ.1.14.0.15071.7z?dl=1)

**Comment by mihaiolteanu** [comment]
The problem seems to be solved for `Edit/Settings/Tabs/Shell` but still persists for `Edit/Settings/Console`
![consolez_lost](https://cloud.githubusercontent.com/assets/8273519/6633751/2d57458a-c956-11e4-9b7b-abf4bf6cb224.PNG)

**Comment by cbucher** [comment]
fixed
