### ISSUE TITLE
Renaming and then cloning a tab doesn't keep the renaming

### ISSUE THREAD

**Issue by mihaiolteanu** [cbucher/console#186]
1. Open a new tab
2. Right-click on tab / Rename Tab (or Ctrl+R); give the tab a new name
3. Right-click on tab / Clone in new Tab 
4. The new tab has the initial name of the tab from step 1 and not the new name entered in step 2

**Comment by cbucher** [comment]
That's debatable.

![image](https://cloud.githubusercontent.com/assets/363759/6643161/790609d6-c9aa-11e4-821c-779b850a12a6.png)

Why if I clone the *view1* in a new tab, the new tab should be named *workspace1*?
