### ISSUE TITLE
Colors rendered differently across shells

### ISSUE THREAD

**Issue by joonro** [cbucher/console#188]
I have mainly used PowerShell with ConsoleZ, and I have set up color schemes according to the PowerShell color that you can get from 

```posh
PS > [enum]::GetValues([System.ConsoleColor]) | Foreach-Object {Write-Host $_ -ForegroundColor $_}
```

But when I use different shell (such as `cmd.exe` or `git bash`) with the same color scheme, the colors are off. Does ConsoleZ render colors different across different shells? It would be great if we can use consistent color schemes regardless of the shells.

**Comment by cbucher** [comment]
ConsoleZ renders colors according to the settings you have configured.

**Comment by joonro** [comment]
Thanks for the reply - and you are right. I forgot that I have to set the background color separately from the color map and that is why I thought the colors were different. Once I set the background color correctly, it looks fine.
