### ISSUE TITLE
How to start Console with a init bat file?

### ISSUE THREAD

**Issue by fate-lovely** [cbucher/console#189]
with cmd.exe, I can pass "/k something.bat" to launch shell with some configuration, but I don't know how to do that in Console.
I have tried console.exe /? or console.exe /help or console.exe --help and so on ..
I am a mac programmer and I am not familiar with windows (especially about the shell)

**Comment by cbucher** [comment]
This is a GUI application. You can click on help in the menu or in the toolbar to display the manual.

**Comment by ericblade** [comment]
Edit->Settings->Tabs, set your shell to cmd.exe /k batfile.bat
