### ISSUE TITLE
Adding a 'window' entry in the menubar

### ISSUE THREAD

**Issue by Nacos** [cbucher/console#190]
Hello, 

I would love to have a drow-down menu in the menubar displaying all currently opened tabs and, when you click on it, focusing on the correct tab. (like what you can find in notepad++).
Having this menu also available on the context menu when you right-click on the systray icon (putting consoleZ and the correct tab in the front) would also be awesome.

Do you think that could be possible ?

Thanks

**Comment by cbucher** [comment]
Hello,

Are you talking about the menu "Context menu # 3" (see `Settings/Hotkeys/Mouse`)?
In this case, yes that can be done.

**Comment by Nacos** [comment]
Oh yes you're right, it's exactly this menu (it was a bit hidden behind a generic name ;) )

**Comment by cbucher** [comment]
> it was a bit hidden behind a generic name ;)

I agree ^^
By the way, if you found labels that can fit in the settings table, I'm interested.

**Comment by cbucher** [comment]
Can you try/test the last experimental version?

**Comment by Nacos** [comment]
Thanks for adding this feature.

When consoleZ is simply hidden behind other windows : works as expected.

When consoleZ is minimized properly, right click on the systray icon does not restore the window with full focus (I suppose it is the expected behavior because I can reproduce it on the last stable version).
In this case, after I try to click in the "Tabs" menu (from the systray icon) and restore consoleZ from the taskbar, I can see minor graphic glitches : 
![consolezgraphicglitch](https://cloud.githubusercontent.com/assets/134682/6820855/f8661b18-d2d2-11e4-8722-c475a62baf9f.PNG)

I'm nitpicking here, this is not a critical bug and when I switch the tab again the glitch disappear ;)

ConsoleZ 1.14.0.15083 (x64 version)
Windows 8.1 x64

**Comment by cbucher** [comment]
When the application is minimized (iconic), the size of the application is the size of the button in the taskbar. That explains the glitches.
I wondered how to handle the minimized state. I think I will show and give focus to the application on right click (on systray icon) and so display the popup menu.

**Comment by cbucher** [comment]
@Nacos you can try the last experimental version

**Comment by Nacos** [comment]
Seems to work as expected :)

I will get back to you if I find any issues.

**Comment by cbucher** [comment]
thx
