### ISSUE TITLE
chcp 65001 doesnt function properly

### ISSUE THREAD

**Issue by fprijate** [cbucher/console#192]
While command chcp xxxx functions properly for other codepages,
it  doesn't function for codepage 65001 (utf8)

**Comment by cbucher** [comment]
Please, when you create an issue, describe the problem! I don't have a crystal ball!

Codepage issue cannot be related with ConsoleZ.

The codepage indicates how to interpret text sent into output by CLI applications.
If codepage 65001 doesn't work, perhaps your application doesn't output utf8...

![image](https://cloud.githubusercontent.com/assets/363759/6765047/424c303e-cfcf-11e4-8242-61788810d23b.png)

If you want display UNICODE chars you must select a TrueType font (see `Using ConsoleZ / Language settings` in the help).

**Comment by fprijate** [comment]
Here is a sample image.
Platform: Win7, with Slovenian language support.
Both ConsoleZ and cmd shell are using consolas font (or any other ttf font)
![test](https://cloud.githubusercontent.com/assets/1025131/6790759/319bbe80-d1aa-11e4-8301-d4a674e2c664.png)

**Comment by fprijate** [comment]
I am sorry for molesting you.
After reading instructions , everything is working fine.
Sorry again and thanks for your program.
I am using it a lot.
Thanks again

Franček
