### ISSUE TITLE
New command - paste selection

### ISSUE THREAD

**Issue by apla** [cbucher/console#193]
Sometimes I need to insert into new shell command multiple files from previous command. `Paste selected` is very useful then, it allows me to avoid copying and pasting. This feature is supported on Mac OS X `Terminal.app` and when I paste selected text system clipboard remains intact.

Thank you for your work, this project is awesome!

**Comment by cbucher** [comment]
I can select text in multiple views. That implies a restriction: the text pasted in a view would be the text selected in this view.
![image](https://cloud.githubusercontent.com/assets/363759/6778338/26b4ae94-d152-11e4-9351-93aa053a6fa5.png)

Another restriction: you cannot check "Copy on select". Another restriction: you cannot check "Copy on select". The scroll is locked from the beginning of selecting text to an action on the selected text (copy/clear).

**Comment by apla** [comment]
That feature is intended to work within a view. You pasting currently selected text into current cursor position. Every view has its own cursor, and every view can have selection, so there is no issue here.

_While writing reply to "Copy on select" feature I found why "Copy on select" turned on by default. I use Mac for a long time and don't understand the thing: Ctrl-C is actually mapped to two very different commands — break current command and copy selection. So, using virtual machine to run Windows, I cannot use Ctrl-C as a selection copy command and I cannot turn off "Copy on select" because I don't have Ins key._

> Another restriction: you cannot check "Copy on select"

Actually, you can. If "Copy on select" checked and "Clear selection on copy" isn't, then `Paste selected` can work just fine (run action, then scroll and paste).

**Comment by cbucher** [comment]
>Actually, you can. If "Copy on select" checked and "Clear selection on copy" isn't, then Paste selected can work just fine (run action, then scroll and paste).

That implies you cannot paste two times the selection.

**Comment by cbucher** [comment]
@apla please try the last experimental version

**Comment by cbucher** [comment]
@apla please, try the last experimental version

**Comment by cbucher** [comment]
@apla please, try the last experimental version

**Comment by cbucher** [comment]
@apla please, try the last experimental version

**Comment by cbucher** [comment]
@apla please, try last beta version

**Comment by cbucher** [comment]
@apla please, try last beta version
