### ISSUE TITLE
Program does not respond by opening the setting dialog.

### ISSUE THREAD

**Issue by hyee** [cbucher/console#194]
Hi,

I encounter following problems since the new version in Win7 64 platform:
1). The whole program losts focus if open the setting dialog or renaming the tab, in this case I can do nothing but kill the program. This issue does not 100% occur.
2). The tab title will automatically become "Administrator: ..." if execute any command in the tab, I don't choose the "run as administrator" option. In previous version before supporting Win XP, this issue does not happen.
3). I can never split the tabs by clicking the related menu items, as well as draging the tabs to accomplish this purpose.

**Comment by cbucher** [comment]
>The whole program losts focus if open the setting dialog or renaming the tab, in this case I can do nothing but kill the program. This issue does not 100% occur.
I experience this problem too. But it is sporadic. Key and mouse button down events are swallowed by explorer.exe process. Try too kill all instances of explorer.exe to verify. You will close the desktop shell, don't forget to keep task manager opened and launch explorer from it ('File/Run new task`).

>The tab title will automatically become "Administrator: ..." if execute any command in the tab, I don't choose the "run as administrator" option.
Seems you launch ConsoleZ with elevated privileges...

>In previous version before supporting Win XP
*Warning: there is no longer maintenance for legacy version.*
This modification concerns only the 32 bit legacy version. You must use a 64 bits version of ConsoleZ under a 64 bits OS.

>I can never split the tabs by clicking the related menu items, as well as draging the tabs to accomplish this purpose.
I don't understand. Upgrade with the last experimental version and post the diagnostic report `Help / Diagnose`.

**Comment by hyee** [comment]
Hi,

The issues can be found in following screen-cap even I switch to 64bit consoleZ:
1) Split tabs doesn't work, sometimes the program will be terminated unexpectely by clicking the item
2) The "Administrator: ..." title

![sshot-1](https://cloud.githubusercontent.com/assets/761520/6778570/ab4b1558-d18e-11e4-9755-410b9d9ea602.png)

I also click the "Diagnose" but no log is generated under that folder.

**Comment by cbucher** [comment]
>I also click the "Diagnose" but nothing happend, and no log is generated under that folder. My version is 1.13.0.15044

That's why I wrote:
**Upgrade with the last experimental version** and post the diagnostic report Help / Diagnose.

**Comment by hyee** [comment]
Hi,

As I can see that the latest release version is 1.13, there is no 1.14 binary files available.

**Comment by hyee** [comment]
Sorry, my bad, I didn't find the experimental before. Now I switch to 1.14 and click "diagnos", the program was terminated. As shown below:

![sshot-1](https://cloud.githubusercontent.com/assets/761520/6781034/379dac26-d1a5-11e4-88e5-d3981eafa559.png)

**Comment by hyee** [comment]
Hi,

The lost focus issue seldom be seen in V1.14. And finally I know why the tab windows cannot be splitted,  if the shell path is a relative path instead of an absolute path, then this issue happens, as shown below:

![sshot-1](https://cloud.githubusercontent.com/assets/761520/6782462/4932e956-d1af-11e4-8b21-e05fc1fdf7e6.png)

**Comment by cbucher** [comment]
Can you send me the crash dump?
Create registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`. The crash dump should be located in `%LOCALAPPDATA%\CrashDumps`.
Zip it and upload it to Dropbox, Google Drive, or a similar service, then post the link.

**Comment by hyee** [comment]
37MB of dump file at https://drive.google.com/file/d/0B3b0xhzRjQoQNncxRTczdHBTVmc/view?usp=sharing

**Comment by cbucher** [comment]
Thank you for the crash dump. I hope I fixed the `Diagnose` problem in the last experimental version.
Can you try this version?

**Comment by hyee** [comment]
The diagnose function works fine now.  Since Github doesn't support uploading the log file, I've have to rename it as png file. You can save the broken png as zip file to see the log.

For the "administrator:" title issue, you can try exec command "title abcd" to recur. Thanks a lot.
. 

![dmp6f1e tmp](https://cloud.githubusercontent.com/assets/761520/6800860/7d260474-d25d-11e4-9a44-bb4ddc39f11a.png)

**Comment by char101** [comment]
To close the unclosable settings dialog you can use Process Hacker -> View -> Windows -> find the window, right click, then select Close.

Also it seems that this only happens when ConsoleZ window is maximized.

**Comment by cbucher** [comment]
>For the "administrator:" title issue, you can try exec command "title abcd" to recur.

I cannot reproduce your issue.
I cannot see "Adminitrator:" prefix in your diagnostic report.
![image](https://cloud.githubusercontent.com/assets/363759/6991749/0925c3aa-daa7-11e4-87db-7d6c5ec1f0ae.png)

**Comment by cbucher** [comment]
>And finally I know why the tab windows cannot be splitted,  if the shell path is a relative path instead of an absolute path, then this issue happens, as shown below:
>
>![sshot-1](https://cloud.githubusercontent.com/assets/761520/6782462/4932e956-d1af-11e4-8b21-e05fc1fdf7e6.png)

With this setting:
![image](https://cloud.githubusercontent.com/assets/363759/6991845/8ed6c12a-daac-11e4-8e56-fbca969b9978.png)
If checked, the startup dir is the current working directory of the view you want to split; otherwise the startup dir is the one specified in tab's settings (by default ConsoleZ current working directory).

**Comment by cbucher** [comment]
> 1). The whole program losts focus if open the setting dialog or renaming the tab, in this case I can do nothing but kill the program. This issue does not 100% occur.

After many attempts, I finally found a reproduction scenario:
- maximize ConsoleZ
- iconize ConsoleZ
- restore ConsoleZ
- open a modal dialog box (settings / rename tab / message box)

**Comment by cbucher** [comment]
@hyee @char101  can you try the last version (1.14.129 or more) ?

**Comment by hyee** [comment]
I've tried the new version, and currently the losting focus issue no more occurs.
By the way,  
1) The "Administrator..." title issue still exists,  you may turn off Windows UAC and try "title abcd" to recur.
2) Still cannot split tabs when the tab's shell path is relative path. If I uncheck the "Open new shell ..." box, the program will start a new tab and split with current tab, and what I've expected is splitting the existing tabs. 

Attached is the log, please download and save as txt file. Thanks

![dmp6f1e](https://cloud.githubusercontent.com/assets/761520/7554034/028e3726-f748-11e4-9af6-c479db72bcc1.png)

**Comment by cbucher** [comment]
>1) The "Administrator..." title issue still exists, you may turn off Windows UAC and try "title abcd" to recur, this issue doesn't happen in version V1.12.

```
ConsoleZ aero x86 1, 14, 0, 15129
is elevated? no
UAC prefix "管理员: "
Tab (active): dbcli
  View (active):  管理员:  cdads
  is elevated? no
```

Neither ConsoleZ nor the tab are launched as administrator.
#167 fix elevated process detection
Before fixing  this bug, all processes launched without UAC wrer wrongly considered as elevated.
You can open a new issue, if you want a behavior modification.

>2) Still cannot split tabs when the tab's shell path is relative path. If I uncheck the "Open new shell ..." box, the program will start a new tab and split with current tab, and what I've expected is splitting the existing tabs.

Yes, splitting means open a **new** shell with same parameters.

Thx
