### ISSUE TITLE
Dynamically Update Tab Title

### ISSUE THREAD

**Issue by arrrrrrr** [cbucher/console#196]
Some applications (such as x264 encoder) use the console title to display current progress of the running application and it's updated periodically when another 'n' amount of frames are output, so might be every say 10 or 100 frames, for example. At present its possible to force a title update by switching tabs and then switching back again. Perhaps always checking for title updates is unnecessary for most cases, but making it switchable with say a sane interval for checking (maybe once every 5-10s?) would be neat.

**Comment by cbucher** [comment]
@arrrrrrr you can try the last experimental version

**Comment by arrrrrrr** [comment]
Neat. Seems to be working as expected, will ping back if it stops doing so. Thanks a bunch.

**Comment by cbucher** [comment]
thx
