### ISSUE TITLE
How to use AutoHotkey with ConsoleZ?

### ISSUE THREAD

**Issue by rdcoe** [cbucher/console#197]
I am using the TabExpansion++ module, loaded by my profile.  When I launch PowerShell directly, I can use Ctrl-D to logout of the shell.  When inside ConsoleZ, Ctrl-D prints to the console.  I have verified the same version of PowerShell is running, as per the attached screen capture.

![consolez](https://cloud.githubusercontent.com/assets/11742613/6948665/4bb5de7a-d87d-11e4-96a2-a26dfb7077c8.png)

**Comment by cbucher** [comment]
> I can use Ctrl-D to logout of the shell.

how? As far as I know, neither Powershell neither TabExpansion++ module handle Ctrl-D.

**Comment by rdcoe** [comment]
Sorry, I forgot that I am using hotkeys for this:
#IfWinActive ahk_class ConsoleWindowClass
^L::SendInput , {Esc}cls{Enter}
^D::SendInput , {Esc}exit{Enter}
#IfWinActive

**Comment by cbucher** [comment]
You mean you use autohotkey.

When you use ConsoleZ, your are no longer in a Windows console but in ConsoleZ application.
So, you must modify your autohotkey script to handle ^D in ConsoleZ application.

Try replacing `ConsoleWindowClass` with `Console_2_Main`.

**Comment by cbucher** [comment]
@rdcoe Try replacing `ConsoleWindowClass` with `Console_2_Main`.

**Comment by rdcoe** [comment]
That worked.  Thanks.
