### ISSUE TITLE
Toolbar does not work from remote desktop

### ISSUE THREAD

**Issue by johnbinu** [cbucher/console#200]
Hi,

I've this issue where the toolbar does not work when I connect to my machine from Remote Desktop. This used to work fine previously (not sure exactly which version).

Both my machines are running Windows 8.1.
I am using ConsoleZ 1.13.0.15044.

Repro Steps:
1. Connect to a remote machine using Windows remote desktop.
2. Start ConsoleZ application.
3. Toolbar should be working fine now.
4. Disconnect remote desktop.
5. Reconnect to remote desktop to that machine.
6. Toolbar will not be clickable. Tooltips also will show incorrectly.

Thanks,
John.

**Comment by cbucher** [comment]
It's a bug in Microsoft common control toolbar. This component computes button size when WM_THEMECHANGED window message is received. But the computation is wrong when the toolbar contains drop down buttons.
I reported the bug to Microsoft.

**Comment by johnbinu** [comment]
Hi, thanks for looking into this.
I was sure there was a prior working version. I tried version 'ConsoleZ.1.12.0.14282' from the archives and it works without issues. I tested it by logging in couple of times via RDP. Probably addition of new toolbars items in version 1.13.* exposed MS bug, not sure about that. Just trying to provide some info if it helps.

Thanks for enhancing and supporting this wonderful software :)

**Comment by cbucher** [comment]
> Probably addition of new toolbars items in version 1.13.* exposed MS bug, not sure about that.

In aero version, toolbar is rendered by a custom code (written by Alain Rist). This code doesn't handle drop down buttons. So in aero version the "New tab" button wasn't a drop down button. I fixed this code.
The ConsoleZ's legacy version (or Console2) or other WTL projects (like programmer's notepad) have the same problem.

**Comment by cbucher** [comment]
I thank the person at Microsoft who solves the WTL bug.

@johnbinu can you try the last version (1.14.128 or more) ?

**Comment by johnbinu** [comment]
I downloaded ConsoleZ.1.14.0.15129  and tested couple of times by logging in and out of my remote PC and the issue does not repro anymore. Thanks a bunch :).

**Comment by cbucher** [comment]
Thx
