### ISSUE TITLE
tab area double click behavior

### ISSUE THREAD

**Issue by spamfilterman** [cbucher/console#201]
Currently when you double click in the empty area along the tab bar, it goes full screen, or back to windowed if already full screen.
I would prefer instead that a double click in that area makes a new tab.  You can already double click on the window title bar to toggle fullscreen-ness, so this seems redundant and I do it by accident too much.  
I should be able to implement that if it sounds like an acceptable change.  

Also, if you double click on the left/right tab scroll buttons, that also makes that window go fullscreen.  I find myself accidentally doing this a lot.  I would rather nothing happens there on a double-click there.
After a quick search, I couldn't obviously see where those left/right buttons were implemented.  If you think that it would straight-forward to fix that, point me to where those buttons are implemented and I'll try to do it.

Thanks.

**Comment by cbucher** [comment]
Yes, if you double click in extended frame area, you maximize the application. This is the same visual aspect as caption, then this is same behavior.
This is the same behavior for internet explorer, chrome, firefox and many other tabbed applications.

You can use the middle mouse button in tab area to close (if the mouse cursor is on a tab) or create a new tab.
This is the same behavior for firefox.

>  I couldn't obviously see where those left/right buttons were implemented.

Search `ScrollButtons`.

**Comment by spamfilterman** [comment]
ok, you make a good point about the behavior compared to other tabbed programs.
I may still try to ignore double clicks on the scroll buttons though.
