### ISSUE TITLE
Not all vertical space is used

### ISSUE THREAD

**Issue by eviljoe** [cbucher/console#203]
Not all of the vertical space available to the console will be used as rows.

I have attached a screenshot to show the issue.

![not-all-vertical-space-used](https://cloud.githubusercontent.com/assets/7276751/7299727/98cbf2a6-e9a5-11e4-8d8e-e9b645de56dd.jpg)

After executing the above command, if I hit enter again, the first line will go off of the top of the screen instead of another line being added.

I am not sure if it is relevant, but I have changed my font & font size to Lucida Console, 10 pt. I am also using Cygwin Bash instead of the Windows shell.

**Comment by eviljoe** [comment]
Hmmm... after looking closer at some of the closed issues (#173 in particular), I have figured out that I need to change the font in the Console Window.  I have done that, and all my vertical space is now used.

**Comment by larvata** [comment]
I have same problem and my workaround is:
1. [View-Console Window]
2. stretch console window to full height
3. [View-Console Window] again to hide console window
