### ISSUE TITLE
No text printed after tput reset

### ISSUE THREAD

**Issue by eviljoe** [cbucher/console#204]
After executing `tput reset` in a Cygwin Bash terminal, the prompt is never reprinted.  No typed characters are echoed until I press `enter` again.  After I press `enter`, all of the non-echoed characters are interpreted as a command.

To Recreate:
 1. Create a Cygwin Bash terminal
  * My Shell option is set to "C:\cygwin64\bin\bash.exe --login -i"
 1. Execute the command, `tput reset`.
  * The terminal prompt will not be printed
 1. Enter `asdf`
  * These characters will not be echo'ed to the screen
 1. Press `enter`
  * "bash: asdf: command not found" will be printed because Bash attempted to execute the asdf command.

`tput reset` is a command that normally clears the entire screen buffer (like `cls` in Windows).  It does not print a bunch of empty lines like the `clear` command.

**Comment by cbucher** [comment]
>  * The terminal prompt will not be printed

No, I test and the prompt is printed.

ConsoleZ displays the Windows console buffer. That's all.
Unless the display is different between the Windows console and ConsoleZ, this is not a ConsoleZ issue.

**Comment by eviljoe** [comment]
Whoops. You are correct.  I removed my .bashrc (which was doing some crazy stuff) and now `tput reset` works a bit better.  I am seeing `]0;~` at the top of the buffer after a `tput reset` though (see screenshot below).  It is in both the Console Window and ConsoleZ buffers though.  So is that a ConsoleZ bug?  If no, do you know who I can report that bug to?  Microsoft?

![strange-escape](https://cloud.githubusercontent.com/assets/7276751/7318243/a1ebb4fe-ea57-11e4-98f2-c7954595743f.png)

**Comment by cbucher** [comment]
>So is that a ConsoleZ bug?

No
The issue can be reproduced **without** ConsoleZ...
![image](https://cloud.githubusercontent.com/assets/363759/7327971/c0621958-ead1-11e4-887c-9c4653d8006e.png)

>Microsoft?

No

You can report the issue to the developers of these tools (cygwin, bash or ncurses).
