### ISSUE TITLE
Select text with Shift+arrow keys

### ISSUE THREAD

**Issue by alexchandel** [cbucher/console#207]
The behavior of `cmd.exe` when selecting text is terrible, even in ConsoleZ, when compared to the behavior of any reasonable terminal emulator like OS X's Terminal.app. In particular, the cursor gets completely lost when selecting text. One way to ameliorate this is to allow text to be selected directly through ConsoleZ using the shift key and the arrow keys.

**Comment by cbucher** [comment]
@alexchandel I think that's a good idea, but really hard to implement.
I don't know if I can found time for this...

**Comment by cbucher** [comment]
@alexchandel Please, try the last experimental version.
I handle the selection with keyboard by using hotkeys.
Don't forget to specify hotkeys.
I don't know if it is the best solution... but I prefer a solution where keys can be set.

**Comment by cbucher** [comment]
@alexchandel Please, try the last experimental version.

**Comment by cbucher** [comment]
@alexchandel Please, try the last experimental version.

**Comment by cbucher** [comment]
@alexchandel please, try beta version

**Comment by alexchandel** [comment]
fwiw it seemed to work
