### ISSUE TITLE
Hide when loosing focus

### ISSUE THREAD

**Issue by dhaumann** [cbucher/console#208]
Yakuake, a quake-like console under KDE/Linux has the feature that if the console application looses the focus, it automatically hides itself. This is extremely convenient, since it automatically closes whenever I click on some other application with the mouse (typically, I want ConsoleZ to disappear in this case).

It would be create if you could add this features as an option to ConsoleZ?

My current workaround is to wrap ConsoleZ with Qonsole in order to obtain this behavior.

**Comment by cbucher** [comment]
@dhaumann Try the last experimental version.

**Comment by dhaumann** [comment]
Will test once there are binaries - thanks!

**Comment by cbucher** [comment]
@dhaumann  You can find the binaries in the download section... :disappointed:

**Comment by dhaumann** [comment]
I see, was looking at the releases, which does not list the experimental version. Tried it now and it works. If anything comes up, I'll let you know. Feel free to close this issue.

Thanks a lot for implementing this!
