### ISSUE TITLE
Integration with PuTTY using ANSICON no longer works.

### ISSUE THREAD

**Issue by webmaven** [cbucher/console#209]
I am trying to get PuTTY working with ConsoleZ according to this solution using ANSICON: http://superuser.com/a/390872

In my case, making a tab named PuTTY with the following command (since I have both programs' directories on the path):
```ansicon putty -load Default```

But PuTTY still keeps popping up as an independent window, rather than inside a ConsoleZ tab.

Am I missing a setting of some sort?

**Comment by cbucher** [comment]
PuTTY is not a

**Comment by webmaven** [comment]
Thanks for noting I should be using the plink executable instead. It doesn't work either, but in a different way:

A blank tab appears momentarily, and then disapears, or occasionally is replaced with a plain command console.

As for your recommendation, can you give setup instructions to get an OpenSSH terminal working within a ConsoleZ tab?

**Comment by cbucher** [comment]
download OpenSSh for Windows: http://www.mls-software.com/opensshd.html

you can configure your tab like this: `<path to ssh>\ssh.exe -l <username> <server>`

http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/slogin.1?query=ssh&sec=1

**Comment by webmaven** [comment]
I needed to modify the command a bit more to work:
```"<path to ssh>\ssh.exe" -p 2222 <username>@<server>```

However, this is still not getting me proper display of escape sequences using ANSICON. Any further suggestions?

I am basically trying to get something like this end result:
http://www.kevwebdev.com/blog/in-search-of-a-better-windows-console-using-ansicon-console2-and-git-bash.html

**Comment by cbucher** [comment]
ansicon is useless with OpenSSH.for Windows.
if you still have the problem, perhaps the problem is located on the server side...
verify your prompt variable, term variable etc ...

**Comment by wavefreak** [comment]
I had the same trouble, but don't got happy with plink and ansicon. In this combination some keys never got escaped the right way.

So my recommendation if you are user of Git Bash (will be installed if you use Git for Windows of Github for Windows) you'll have OpenSSH running anyway.

- Change your shell (default or for tab to: %SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe)
- I just checked quick if it works with CMD, but no success.
- Use in console "ssh -p 2222 <username>@<server>"

Or use ssh config file to just type "ssh myserver" ...
