### ISSUE TITLE
Localize ConsoleZ

### ISSUE THREAD

**Issue by ya158** [cbucher/console#210]
Can you make ConsoleZ fully localizable? Now some word are in hard-coded string. Kirill (github.com/akirill/console) did the patch to store localizable strings in satellite DLLs (http://kirill.ca/dblog/storico.asp?s=Console ; http://sourceforge.net/p/console/patches/22/)

**Comment by cbucher** [comment]
Before coding, I need some guarantees:
Are you a translator?
Do you know a translator team?
Which languages can you maintained?
Can you estimate the translation delay?

**Comment by ya158** [comment]
I am not a professional translator. I have only translated into Russian some programs. One of them is the original Console from bozho (akirill used this translation for his fork). I have almost translated your ConsoleZ. Tomorrow I will translate the rest one.

**Comment by alexchandel** [comment]
-1 for DLL bloat. Let's find away to do it without increasing the number of DLLs, or not at all. It's bad enough ConsoleZ already ships `ConsoleHook.dll`/`ConsoleHook32.dll`/`FreeImage.dll`/`FreeImagePlus.dll`.

**Comment by cbucher** [comment]
@alexchandel I cannot see how an additional file for each language would be a problem ...

**Comment by ya158** [comment]
Sorry for disturbing you. But I would like to know if I have to expect fully localizable version.

**Comment by cbucher** [comment]
@ya158 You can now begin localization in russian.
You can clone the project and edit *l10n/RUS/console.ini*.
We use [this tool](https://github.com/cbucher/LocalizeRC) to localize the rc file.
I will add help file (chm) localization soon.

**Comment by ya158** [comment]
@cbucher 
My localized console.ini - https://github.com/ya158/ConsoleZRUS

**Comment by cbucher** [comment]
@ya158 Please fork this repository and do a pull request.
I insist that your name appears in the commit ^^

**Comment by cbucher** [comment]
I don't know if you tried to build, but I don't think the text `Формат заголовка основного окна:` will fit here:
![image](https://cloud.githubusercontent.com/assets/363759/7947919/80a230b4-0980-11e5-94c3-c86ade944a30.png)
The RC file may require adjustments.

**Comment by cbucher** [comment]
I must fix some bugs in translation program:
![image](https://cloud.githubusercontent.com/assets/363759/7954005/ab9ab638-09cb-11e5-9325-3e2142272210.png)

ComboBox items are wrong (I think new code page is not used by the program).

I will maximize text areas (without moving anything) to avoid some truncations:
![image](https://cloud.githubusercontent.com/assets/363759/7954082/76590c8a-09cc-11e5-9e2d-caee1bfa3d08.png)

**Comment by ya158** [comment]
I have localized ConsoleZ 1.13.0.15044 with Radialix (unavalable program unfortunately). If interested, you can download Console_RUS.exe  https://yadi.sk/d/_Y26E2XEh3v97
Some items have been already moved and resized in Console_RUS.exe.

**Comment by alexchandel** [comment]
@cbucher How can you not? I want one executable, not an exe + an assortment of DLLs. -1 for DLL bloat again.

**Comment by cbucher** [comment]
@alexchandel And you have constructive ideas?
To the question: ``How an additional file for each language would be a problem?`
you respond: `I want one executable, not an exe + an assortment of DLLs`

That's ridiculous!

**First**, you want no DLL ... that will be dificult to use DLL injection in this case :disappointed:

**Second**, you will have optional language pack DLLs ... you can delete or not install the DLL
I do not yet know how I will distribute these DLLs.

**Third**, if you **want** then you code.
That's the meaning of free source project.
You can suggest, give your opinion but not require when the project does not belong to you!

**Comment by cbucher** [comment]
@ya158 Please, try [experimental version 1.15.0.15161](https://dl.dumptruck.goldenfrog.com/p/wEH1CksD86/ConsoleZ.1.15.0.15161.7z?dl=1) with [russian language pack](https://dl.dumptruck.goldenfrog.com/p/L4kiy_y-TT/console_RUS.dll?dl=1) (**not compatible** with legacy version!)

**Comment by ya158** [comment]
Sorry for the late reply.
I have tried  experimental version 1.15.0.15161 with russian language pack.
1. This version does not work with  Win XP (neither with 32-bit nor with 64-bit)
2. The dialog  "About ConsoleZ..." is empty
I have edited console_RUS.dll (without dialog   "About ConsoleZ...") https://yadi.sk/d/pDE39rGthHsCv

Moreover I would like to ask:
1. What is the difference between  "Release Legacy" and "Release"? 
2. What is the file Console.pdb function?

**Comment by cbucher** [comment]
Legacy version has the old "and ugly" interface of Console2, is compatible with retired OS like Win XP. I hope this version can be removed in a short time (the download counter shows this version has no longer a non significant usage).

There is no point in editing binary, I will not use it.
You should provide me the ini file and rc file (if need larger).

If you use Windows XP, you will not be able to build language DLLs nor test principal target. :disappointed:

A program database (PDB) file holds debugging information. The file is required to analyze a crash dump. (Google is you friend)

**Comment by cbucher** [comment]
Last modifications:
- Support of UTF-8 for **ini** and **rc** file (then we can see diffs in git)
The program LocalizeRC has been modified.
The makefile use iconv to convert **rc** file UTF-8 to UTF-16.
- Labels are larger (translation needs less modification of the rc file).

**Comment by ya158** [comment]
Please advice which program I can use for edition of your files console.rc?
About Windows XP: I have to use Windows XP on some computers and I need  ConsoleZ to work on these computers.

**Comment by cbucher** [comment]
Personally I use a text editor to edit the rc file and I compile with Visual Studio to see the result.
I'm pretty maniac and I like pixel precision alignment.

I tried some tools but **none** supports correctly rc file:
- Resource Hacker
- Resource Builder
- ResEdit

Sorry, I have no solution without Visual Studio to propose...

**Comment by ya158** [comment]
I finished translate l10n/RUS/console.rc (without l10n/RUS/console.ini) forked and did a pull request
Please compile binaries. And don't forget about Windows XP

**Comment by cbucher** [comment]
Some modifications to simplify translation:
- radio buttons and check boxes text are now vertically centered and the height is 16.
So the text automatically use two lines when it is too big.
The RC file should not be modified, unless the translation tales more than 2 lines.
- static cannot be vertically centered but have been maximized.
**LocalizeRC** program has been modified to detect when label text exceed label dimensions.
In this case needed dimensions and recommendation are given. 
The RC file should not be modified unless  label text exceed label dimensions.

With this modifications, french translation required only 22 modifications of the RC file.

**Comment by cbucher** [comment]
@ya158 Hi, release version 1.15 will be create soon. Consider updating Russian translation with last modifications.

**Comment by ya158** [comment]
I finished translate l10n/RUS/console.rc and l10n/RUS/console.ini forked and did a pull request
And don't forget about Windows XP

**Comment by cbucher** [comment]
@ya158 please, try last beta version

**Comment by cbucher** [comment]
@ya158 Can you translate strings added in version 1.16 (in a new pull request)?
