### ISSUE TITLE
Background Text Opacity behavior not well defined

### ISSUE THREAD

**Issue by morinted** [cbucher/console#211]
Hi,

I can't figure out what the background text opacity slider does. I found commit f40c56593eb2cc7c8e86 where it was added, but changing the setting does nothing visible for me. Is it for use with a particular transparency setting? Does Window docking, quake, or borders need to be off/on?

On debug my top line is: `ConsoleZ aero amd64 1, 14, 0, 15129`, so I figure that I am using Aero and should see something.

I'm on Windows 8.1.

Thanks for your help

**Comment by cbucher** [comment]
**Background text opacity** The opacity of the background color can be adjusted.
Set a background color to see something visible. (For example type `color 4f`.)
