### ISSUE TITLE
Aggregate taskbar state/progress

### ISSUE THREAD

**Issue by alejandro5042** [cbucher/console#212]
I have a few scripts that set the progress bar state of the PowerShell window. That way you can have a long running operation in the background and monitor it's progress on the taskbar. ConsoleZ should aggregate the task bar states of each of its tabs and modify its own taskbar state to this aggregate value.

Information on the Windows 7 taskbar API:
https://msdn.microsoft.com/en-us/magazine/dd942846.aspx

Here is a PowerShell script that displays the capability of the Windows taskbar in a console window. You just have to run this from a regular PowerShell window. Save this snipplet to a Test.ps1 file and run it. You'll need to update the path to where your WindowsAPICodePack.Shell.dll exists.

```
param
(
    $PathToWindowsAPICodePack = "**PATH**\WindowsAPICodePack1.1\Microsoft.WindowsAPICodePack.Shell.dll"
)

Add-Type -TypeDefinition @"
// http://learn-powershell.net/2013/08/26/make-a-window-flash-in-taskbar-using-powershell-and-pinvoke/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Runtime.InteropServices;

public class NativeMethods
{
    [StructLayout(LayoutKind.Sequential)]
    public struct FLASHWINFO
    {
        public UInt32 cbSize;
        public IntPtr hwnd;
        public UInt32 dwFlags;
        public UInt32 uCount;
        public UInt32 dwTimeout;
    }

    // Stop flashing. The system restores the window to its original state. 
    const UInt32 FLASHW_STOP = 0;
    
    // Flash the window caption. 
    const UInt32 FLASHW_CAPTION = 1;
    
    // Flash the taskbar button. 
    const UInt32 FLASHW_TRAY = 2;
    
    // Flash both the window caption and taskbar button.
    // This is equivalent to setting the FLASHW_CAPTION | FLASHW_TRAY flags. 
    const UInt32 FLASHW_ALL = 3;
    
    // Flash continuously, until the FLASHW_STOP flag is set. 
    const UInt32 FLASHW_TIMER = 4;
    
    // Flash continuously until the window comes to the foreground. 
    const UInt32 FLASHW_TIMERNOFG = 12; 

    [DllImport("user32.dll")]
    [return: MarshalAs(UnmanagedType.Bool)]
    static extern bool FlashWindowEx(ref FLASHWINFO pwfi);

    public static bool FlashWindow(IntPtr handle, UInt32 timeout, UInt32 count)
    {
        IntPtr hWnd = handle;
        FLASHWINFO fInfo = new FLASHWINFO();

        fInfo.cbSize = Convert.ToUInt32(Marshal.SizeOf(fInfo));
        fInfo.hwnd = hWnd;
        fInfo.dwFlags = FLASHW_ALL | FLASHW_TIMERNOFG;
        fInfo.uCount = count;
        fInfo.dwTimeout = timeout;

        return FlashWindowEx(ref fInfo);
    }
}
"@

try
{
    [void][Reflection.Assembly]::LoadFrom($PathToWindowsAPICodePack)
    $TaskBarObject = [Microsoft.WindowsAPICodePack.TaskBar.TaskBarManager]::Instance
    
    if ([Microsoft.WindowsAPICodePack.TaskBar.TaskBarManager]::IsPlatformSupported)
    {
        $TaskBarObject.SetProgressState("Indeterminate")
        sleep 2
        
        $TaskBarObject.SetProgressState("Normal")

        for ($i = 0; $i -lt 100; $i++)
        {
            $TaskBarObject.SetProgressValue($i, 100)
            sleep -milliseconds 10
            
            if ($i -eq 40)
            {
                $TaskBarObject.SetProgressState("Paused")
                sleep 1
                $TaskBarObject.SetProgressState("Normal")
            }
            
            if ($i -eq 60)
            {
                $TaskBarObject.SetProgressState("Error")
            }
        }
        
        [void][NativeMethods]::FlashWindow((Get-Process -Id $pid).MainWindowHandle, 150, 10)
    }
}
catch
{
    Write-Error $_
}
finally
{
    try
    {
        $TaskBarObject.SetProgressState("NoProgress")
    }
    catch
    {
    }
}
```

**Comment by cbucher** [comment]
I have no way to retrieve these states...
And if you execute your script in a shell running under ConsoleZ, this shell is hidden (it has no button in taskbar), so the script will fail:

```
C:\priv\projects\test.ps1 : Exception calling "SetProgressState" with "1" argument(s): "A valid active Window is needed to update the Taskbar."
At line:1 char:1
+ . .\test.ps1 C:\priv\projects\packages\WindowsAPICodePack-Shell.1.1.1\lib\Micros ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,test.ps1

```

**Comment by alejandro5042** [comment]
A real bummer. I appreciate your quick turnaround!

I realize this is a low priority request and I understand if we don't do it. But it would be really cool. I wonder if there is any other way to communicate progress to the ConsoleZ process. A custom named pipe to communicate extra details? How about calling an .exe that does IPC? I'd love to help by writing any PowerShell scripts to expose this functionality to users.

My build scripts already have progress bars, but this would be ideal since users won't need to monitor the console. It would benefit the ~300 engineers who my scripts everyday!

**Comment by alejandro5042** [comment]
Also, maybe this could serve as a way to communicate other details to ConsoleZ. Like tab colors, replace the custom icon, status bar updates, etc.

**Comment by cbucher** [comment]
I agree for monitoring a progression and display a progress bar.
But I have doubts concerning icon, status bar updates &.... I think, script or console application execution should not rely on ConsoleZ.

Did you use Write-Progress in Powershell?

**Comment by alejandro5042** [comment]
I agree, I don't think apps should rely on ConsoleZ being their host. Yet here at work, there are many of us that use ConsoleZ. Again, it can be an optional feature for being on ConsoleZ... if my script finds a consolez-helper.exe, I can call it and pass whatever information I would like to customize the shell. The progress features would be rich enough that nobody would want to use a regular shell :) Really, nobody should be using the regular shell, yours is superior in every way!

Yes I do use Write-Progress for all my scripts. It does a great job... if have the screen open. If you can support this out-of-the-box, that would be awesome. The thing is what to do after progress has completed? Do you flash the window for a few seconds and then permanently highlight it? I suppose that would be a good option.

**Comment by cbucher** [comment]
>The thing is what to do after progress has completed? Do you flash the window for a few seconds and then permanently highlight it? I suppose that would be a good option.

I won't handle alerts.
As now, if text changes in an inactive tab, tab will flash.

if you want to alert on end of processing, you can add notifications in your script:
- messagebox
```
$wshell = New-Object -ComObject Wscript.Shell
$wshell.Popup("Operation Completed",0,"Done",0x1)
```

- tooltip ballon on systray
```
if($global:objNotifyIcon -eq $null)
{
  [void] [System.Reflection.Assembly]::LoadWithPartialName("System.Windows.Forms")

  $global:objNotifyIcon = New-Object System.Windows.Forms.NotifyIcon
}

if($global:objNotifyIcon -ne $null)
{
  $global:objNotifyIcon.Icon = [System.Drawing.SystemIcons]::Error
  $global:objNotifyIcon.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Info
  $global:objNotifyIcon.BalloonTipText = "Finished!" 
  $global:objNotifyIcon.BalloonTipTitle = "Hello World"

  $global:objNotifyIcon.Visible = $true
  $global:objNotifyIcon.ShowBalloonTip(10000)
}
```

- toast
```
$ErrorActionPreference = "Stop"

#toast
$notificationTitle = "Notification: " + [DateTime]::Now.ToShortTimeString()

[Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime] > $null
$template = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText01)

#Convert to .NET type for XML manipuration
$toastXml = [xml] $template.GetXml()
$toastXml.GetElementsByTagName("text").AppendChild($toastXml.CreateTextNode($notificationTitle)) > $null

#Convert back to WinRT type
$xml = New-Object Windows.Data.Xml.Dom.XmlDocument
$xml.LoadXml($toastXml.OuterXml)

$toast = New-Object Windows.UI.Notifications.ToastNotification ($xml)
#$toast.Tag = "PowerShell"
#$toast.Group = "PowerShell"
$toast.ExpirationTime = [DateTimeOffset]::Now.AddMinutes(5)
#$toast.SuppressPopup = $true

$notifier = [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier("winstore_cw5n1h2txyewy!Windows.Store")
$notifier.Show($toast);
```

**Comment by cbucher** [comment]
@alejandro5042 please, try the last experimental version

**Comment by cbucher** [comment]
@alejandro5042 please, try last beta version

**Comment by cbucher** [comment]
@alejandro5042 please, try last beta version
