### ISSUE TITLE
Newline characters are mishandled using the fish shell in cygwin.

### ISSUE THREAD

**Issue by jonthegiant** [cbucher/console#213]
Expected behavior (using fish shell in cygwin):
![cygwin_fish_newline](https://cloud.githubusercontent.com/assets/5591930/7731839/e0a20612-fee8-11e4-9c29-b0b309f188a9.png)

Mishandled newline behavior (using fish shell in cygwin **inside** consolez):
![consolez_fish_newline_bug](https://cloud.githubusercontent.com/assets/5591930/7731841/e60dba9c-fee8-11e4-9105-899b4366bc85.png)

Notice the '?'s inserted at new lines.

**Comment by cbucher** [comment]
ConsoleZ reads the *UNICODE* console buffer and draw it.
Console does not interpret, does not change, does not convert the characters.
If the text is different then the shell's command line or settings are different.

Verify your prompt variable.

**Comment by jonthegiant** [comment]
Seems to be an issue with fish itself, sorry. Please close this if you wish. Thanks.
