### ISSUE TITLE
Clicking on View-settings freezes the application

### ISSUE THREAD

**Issue by manojth** [cbucher/console#214]
This is a random issue and does not happen everytime we load the settings dialog box.

Steps
1. Open a new tab for bash.
2. Click on the command window.
3. Now click on Edit->Settings from the menu.
4. The "settings" dialog is shown.
5. Try to close the dialog box by clicking on "ok" button.

Actual Result
The dialog box does not close. The dialog box flashes whenever user clicks on OK button. This denotes the control (focus) is on the command prompt (below the dialog box). User is stuck here and has to go to "Task bar" and kill th e process of ConsoleZ.

Expected Result
User should be able to click on ok and exit the dialog box.

**Comment by cbucher** [comment]
#194
Download the last version (currently in pre-release) and verify that's fixed.
