### ISSUE TITLE
Text selection using keyboard only

### ISSUE THREAD

**Issue by Di-Kai** [cbucher/console#216]
Currently, text can be conveniently selected using mouse.
As most of the time one's hands are on keyboard, it would be really handy if text can be selected solely using keyboard. For example, using LeftShift + ArrowKeys. ArrowKeys will be used to move cursor around to determine the range of selection (Just as that is in Word or a webpage).

**Comment by cbucher** [comment]
duplicate #207

**Comment by cbucher** [comment]
@Di-Kai  Please, try the last experimental version.
