### ISSUE TITLE
Pipe and redirect not consistent with DOS box behaviour

### ISSUE THREAD

**Issue by lgastevens** [cbucher/console#217]
Hi, I use a lot of Perl scripts within ConsoleZ; when using pipes or redirects I'm not seeing the same behaviour as I do in a regular Windows DOS box (cmd.exe).
I'm using ConsoleZ 1.13.0.15044 (on Windows 7)

I have this simple perl script:

`C:\Users\ludovicostev\Documents\Scripts\acli>type test.pl`
`print "this is a test to print out some text";`
`C:\Users\ludovicostev\Documents\Scripts\acli>test.pl`
`this is a test to print out some text`

On a DOS box I can do this:
`C:\Users\ludovicostev\Documents\Scripts\acli>test.pl > file.txt`

And the output is redirected to the output file as expected:
`C:\Users\ludovicostev\Documents\Scripts\acli>type file.txt`
`this is a test to print out some text`

If I do the same thing with ConsoleZ, the output file gets created, but no output gets redirected to it..
`C:\Users\ludovicostev\Documents\Scripts\acli>test.pl > file.txt`

`C:\Users\ludovicostev\Documents\Scripts\acli>type file.txt`

`C:\Users\ludovicostev\Documents\Scripts\acli>`

But if I do this, then it works correctly even with ConsoleZ:
`C:\Users\ludovicostev\Documents\Scripts\acli>perl.exe test.pl > file.txt`

`C:\Users\ludovicostev\Documents\Scripts\acli>type file.txt`
`this is a test to print out some text`

Same issue with pipes..
New perl script:

`C:\Users\ludovicostev\Documents\Scripts\acli>type test2.pl`
`print <STDIN> . " - which was piped to me";`

In a DOS box pipe works:
`C:\Users\ludovicostev\Documents\Scripts\acli>type file.txt | test2.pl`
`this is a test to print out some text - which was piped to me`

But in ConsoleZ it does not:
`C:\Users\ludovicostev\Documents\Scripts\acli>type file.txt | test2.pl`
` - which was piped to me`

..unless I do this:
`C:\Users\ludovicostev\Documents\Scripts\acli>type file.txt | perl.exe test2.pl`
`this is a test to print out some text - which was piped to me`

I'm not entirely sure what is going on here; it would seem to me that ConsoleZ has some problems feeding arguments to commands which are de-referenced using windows file extensions..
As a workaround I can place my scripts into batch files (which spell out the perl.exe) but I would have expected ConsoleZ to be consistent with cmd.exe.

Thanks
Best regards
Ludovico Stevens

**Comment by cbucher** [comment]
Your ConsoleZ version is outdated.

Consolez is not a shell.
ConsoleZ reads the UNICODE console buffer and draw it. That's all.
Execution and redirection are done by the shell specified in you tab configuration (by default cmd.exe).
If you don't have the same behavior, then you don't use the same shell or not with the same environment.

You can verify perl integration with assoc and ftype commands.
