### ISSUE TITLE
Long lines truncated 

### ISSUE THREAD

**Issue by twowheelmotion** [cbucher/console#218]
I really love ConsoleZ. It has made the transition from OS X back to Windows a much nicer experience. But there is one problem I am having:

Long output lines are truncated. In the image below, it should not end with "m". The complete line is "matches (y/n)"

So everything between the "m" and the ")" gets dropped when the printing continues to the next line.

![consolez_truncated](https://cloud.githubusercontent.com/assets/4992903/7868418/cdb8e932-0530-11e5-80ff-abbf1c9452d6.PNG)

**Comment by cbucher** [comment]
Verify your setting...
Post a diagnostic report.

**Comment by twowheelmotion** [comment]
ConsoleZ aero x86 1, 14, 0, 15129
is elevated? no
UAC prefix "Administrator: "
Tab: ConsoleZ
  View (active): 1. ConsoleZ
  is elevated? no
font index: 8
face name: Lucida Console
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=14
max window size: cols=157 rows=69
Tab: ConsoleZ
  View (active): 2. ConsoleZ
  is elevated? no
font index: 8
face name: Lucida Console
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=14
max window size: cols=157 rows=69
Tab (active): ConsoleZ
  View (active): 3. ConsoleZ
  is elevated? no
font index: 8
face name: Lucida Console
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=14
max window size: cols=157 rows=71
Monitors 2
  Flags 0
  DeviceID \\?\DISPLAY#DEL4026#5&f9673b6&0&UID257#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0013
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Dell 1908FP(Digital)
  StateFlags 3
  Rect (1280,0)x(2560,1024)
  Work (1280,0)x(2560,1024)
  Flags 1  primary
  DeviceID \\?\DISPLAY#DEL4026#5&f9673b6&0&UID258#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0008
  DeviceName \\.\DISPLAY2\Monitor0
  DeviceString Dell 1908FP(Digital)
  StateFlags 3
  Rect (0,0)x(1280,1024)
  Work (0,0)x(1280,994)
Settings file C:\Users\acampbell\ConsoleZ\console.xml
<?xml version="1.0"?>
<settings>
	<console change_refresh="10" refresh="100" rows="25" columns="80" buffer_rows="500" buffer_columns="0" shell="" init_dir="" start_hidden="0" save_size="0" background_text_opacity="255">
		<colors background_text_opacity="255">
			<color id="0" r="0" g="0" b="0"/>
			<color id="1" r="0" g="0" b="128"/>
			<color id="2" r="0" g="150" b="0"/>
			<color id="3" r="0" g="150" b="150"/>
			<color id="4" r="170" g="25" b="25"/>
			<color id="5" r="128" g="0" b="128"/>
			<color id="6" r="128" g="128" b="0"/>
			<color id="7" r="192" g="192" b="192"/>
			<color id="8" r="128" g="128" b="128"/>
			<color id="9" r="0" g="100" b="255"/>
			<color id="10" r="0" g="255" b="0"/>
			<color id="11" r="0" g="255" b="255"/>
			<color id="12" r="255" g="50" b="50"/>
			<color id="13" r="255" g="0" b="255"/>
			<color id="14" r="255" g="255" b="0"/>
			<color id="15" r="255" g="255" b="255"/>
		</colors>
		<cursor style="0" r="255" g="255" b="255"/>
		<background type="0" r="0" g="0" b="0">
			<image file="" relative="0" extend="0" position="0">
				<tint opacity="0" r="0" g="0" b="0"/>
			</image>
		</background>
	</console>
	<appearance>
		<font name="Courier New" size="10" bold="0" italic="0" smoothing="0" bold_intensified="0" italic_intensified="0" extra_width="0">
			<color use="0" r="0" g="0" b="0"/>
		</font>
		<window title="ConsoleZ" icon="" use_tab_icon="1" use_console_title="0" show_cmd="1" show_cmd_tabs="1" use_tab_title="1" trim_tab_titles="20" trim_tab_titles_right="0" main_title_format="?U([%u] )?N({%u} )%m?s( - %s)" tab_title_format="%n. ?U([%u] )?N({%u} )%t?s( - %s)"/>
		<controls show_menu="1" show_toolbar="1" show_statusbar="1" show_tabs="1" hide_single_tab="1" show_scrollbars="1" flat_scrollbars="0" tabs_on_bottom="0" hide_tab_icons="0" show_searchbar="1"/>
		<styles caption="1" resizable="1" taskbar_button="1" border="1" inside_border="2" tray_icon="1" quake_like="0" jumplist="0" integrated_ime="0" quake_animation_time="300">
			<selection_color r="255" g="255" b="255"/>
		</styles>
		<position x="-1" y="-1" dock="-1" snap="-1" z_order="0" save_position="0" w="-1" h="-1" save_size="0"/>
		<transparency type="3" active_alpha="216" inactive_alpha="215" r="0" g="0" b="0"/>
		<fullscreen start_in_fullscreen="0" fullscreen_monitor="0"/>
	</appearance>
	<behavior>
		<copy_paste copy_on_select="0" clear_on_copy="1" no_wrap="1" trim_spaces="1" copy_newline_char="0" sensitive_copy="1" include_left_delimiter="0" include_right_delimiter="0" left_delimiters=" ([" right_delimiters=" )]" eol_spaces="1" rtf="1"/>
		<scroll page_scroll_rows="0"/>
		<tab_highlight flashes="3" stay_highligted="1"/>
		<close allow_closing_last_view="0" confirm_closing_multiple_views="1"/>
		<focus follow_mouse="1"/>
		<instance allow_multi="1"/>
		<clone use_current_dir="0"/>
		<search match_case="0" match_whole_word="0"/>
		<runas use_credprov="1"/>
	</behavior>
	<hotkeys use_scroll_lock="1">
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="83" command="settings"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="112" command="help"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="0" code="115" command="exit"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="84" command="newtab1"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="113" command="newtab2"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="114" command="newtab3"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="115" command="newtab4"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="116" command="newtab5"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="117" command="newtab6"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="118" command="newtab7"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="119" command="newtab8"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="120" command="newtab9"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="121" command="newtab10"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="122" command="newtab11"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="123" command="newtab12"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="49" command="switchtab1"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="50" command="switchtab2"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="51" command="switchtab3"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="52" command="switchtab4"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="53" command="switchtab5"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="54" command="switchtab6"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="55" command="switchtab7"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="56" command="switchtab8"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="57" command="switchtab9"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="48" command="switchtab10"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="9" command="nexttab"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="9" command="prevtab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="87" command="closetab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="82" command="renametab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="34" command="nextview"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="33" command="prevview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="37" command="leftview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="39" command="rightview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="38" command="topview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="40" command="bottomview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="dechsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="inchsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="decvsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="incvsize"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="87" command="closeview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="detachview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="attach"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="79" command="splithoriz"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="69" command="splitvert"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clone"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="122" command="fullscreen"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="96" command="zoom100"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="107" command="zoominc"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="109" command="zoomdec"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="71" command="groupall"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="71" command="ungroupall"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="grouptab"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="84" command="ungrouptab"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clear"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="67" command="copy"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="65" command="selectall"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="46" command="clear_selection"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="86" command="paste"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="stopscroll"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowdown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpagedown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="find"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findnext"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findprev"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtransparency"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="112" command="dumpbuffer"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu1"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu2"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu3"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="ctrlC"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd1"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd2"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd3"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd4"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd5"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd6"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd7"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd8"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd9"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd10"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="activate" win="0"/>
	</hotkeys>
	<mouse>
		<actions>
			<action ctrl="0" shift="0" alt="0" button="1" name="copy"/>
			<action ctrl="0" shift="1" alt="0" button="1" name="select"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="select_column"/>
			<action ctrl="0" shift="0" alt="0" button="3" name="paste"/>
			<action ctrl="1" shift="0" alt="0" button="1" name="drag"/>
			<action ctrl="0" shift="0" alt="0" button="4" name="link"/>
			<action ctrl="0" shift="0" alt="0" button="2" name="menu"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="menu2"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="menu3"/>
		</actions>
	</mouse>
	<tabs>
		<tab title="ConsoleZ" use_default_icon="0">
			<console shell="" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
		</tab>
	</tabs>
	<external_commands>

</external_commands>
</settings>

**Comment by cbucher** [comment]
you just have to post as code:
```
ConsoleZ aero x86 1, 14, 0, 15129
is elevated? no
UAC prefix "Administrator: "
Tab: ConsoleZ
  View (active): 1. ConsoleZ
  is elevated? no
font index: 8
face name: Lucida Console
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=14
max window size: cols=157 rows=69
Tab: ConsoleZ
  View (active): 2. ConsoleZ
  is elevated? no
font index: 8
face name: Lucida Console
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=14
max window size: cols=157 rows=69
Tab (active): ConsoleZ
  View (active): 3. ConsoleZ
  is elevated? no
font index: 8
face name: Lucida Console
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=14
max window size: cols=157 rows=71
Monitors 2
  Flags 0
  DeviceID *
  DeviceKey *
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Dell 1908FP(Digital)
  StateFlags 3
  Rect (1280,0)x(2560,1024)
  Work (1280,0)x(2560,1024)
  Flags 1  primary
  DeviceID *
  DeviceKey *
  DeviceName \\.\DISPLAY2\Monitor0
  DeviceString Dell 1908FP(Digital)
  StateFlags 3
  Rect (0,0)x(1280,1024)
  Work (0,0)x(1280,994)
Settings file C:\Users*\ConsoleZ\console.xml
<?xml version="1.0"?>
<settings>
	<console change_refresh="10" refresh="100" rows="25" columns="80" buffer_rows="500" buffer_columns="0" shell="" init_dir="" start_hidden="0" save_size="0" background_text_opacity="255">
		<colors background_text_opacity="255">
			<color id="0" r="0" g="0" b="0"/>
			<color id="1" r="0" g="0" b="128"/>
			<color id="2" r="0" g="150" b="0"/>
			<color id="3" r="0" g="150" b="150"/>
			<color id="4" r="170" g="25" b="25"/>
			<color id="5" r="128" g="0" b="128"/>
			<color id="6" r="128" g="128" b="0"/>
			<color id="7" r="192" g="192" b="192"/>
			<color id="8" r="128" g="128" b="128"/>
			<color id="9" r="0" g="100" b="255"/>
			<color id="10" r="0" g="255" b="0"/>
			<color id="11" r="0" g="255" b="255"/>
			<color id="12" r="255" g="50" b="50"/>
			<color id="13" r="255" g="0" b="255"/>
			<color id="14" r="255" g="255" b="0"/>
			<color id="15" r="255" g="255" b="255"/>
		</colors>
		<cursor style="0" r="255" g="255" b="255"/>
		<background type="0" r="0" g="0" b="0">
			<image file="" relative="0" extend="0" position="0">
				<tint opacity="0" r="0" g="0" b="0"/>
			</image>
		</background>
	</console>
	<appearance>
		<font name="Courier New" size="10" bold="0" italic="0" smoothing="0" bold_intensified="0" italic_intensified="0" extra_width="0">
			<color use="0" r="0" g="0" b="0"/>
		</font>
		<window title="ConsoleZ" icon="" use_tab_icon="1" use_console_title="0" show_cmd="1" show_cmd_tabs="1" use_tab_title="1" trim_tab_titles="20" trim_tab_titles_right="0" main_title_format="?U([%u] )?N({%u} )%m?s( - %s)" tab_title_format="%n. ?U([%u] )?N({%u} )%t?s( - %s)"/>
		<controls show_menu="1" show_toolbar="1" show_statusbar="1" show_tabs="1" hide_single_tab="1" show_scrollbars="1" flat_scrollbars="0" tabs_on_bottom="0" hide_tab_icons="0" show_searchbar="1"/>
		<styles caption="1" resizable="1" taskbar_button="1" border="1" inside_border="2" tray_icon="1" quake_like="0" jumplist="0" integrated_ime="0" quake_animation_time="300">
			<selection_color r="255" g="255" b="255"/>
		</styles>
		<position x="-1" y="-1" dock="-1" snap="-1" z_order="0" save_position="0" w="-1" h="-1" save_size="0"/>
		<transparency type="3" active_alpha="216" inactive_alpha="215" r="0" g="0" b="0"/>
		<fullscreen start_in_fullscreen="0" fullscreen_monitor="0"/>
	</appearance>
	<behavior>
		<copy_paste copy_on_select="0" clear_on_copy="1" no_wrap="1" trim_spaces="1" copy_newline_char="0" sensitive_copy="1" include_left_delimiter="0" include_right_delimiter="0" left_delimiters=" ([" right_delimiters=" )]" eol_spaces="1" rtf="1"/>
		<scroll page_scroll_rows="0"/>
		<tab_highlight flashes="3" stay_highligted="1"/>
		<close allow_closing_last_view="0" confirm_closing_multiple_views="1"/>
		<focus follow_mouse="1"/>
		<instance allow_multi="1"/>
		<clone use_current_dir="0"/>
		<search match_case="0" match_whole_word="0"/>
		<runas use_credprov="1"/>
	</behavior>
	<hotkeys use_scroll_lock="1">
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="83" command="settings"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="112" command="help"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="0" code="115" command="exit"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="84" command="newtab1"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="113" command="newtab2"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="114" command="newtab3"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="115" command="newtab4"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="116" command="newtab5"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="117" command="newtab6"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="118" command="newtab7"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="119" command="newtab8"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="120" command="newtab9"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="121" command="newtab10"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="122" command="newtab11"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="123" command="newtab12"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="49" command="switchtab1"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="50" command="switchtab2"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="51" command="switchtab3"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="52" command="switchtab4"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="53" command="switchtab5"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="54" command="switchtab6"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="55" command="switchtab7"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="56" command="switchtab8"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="57" command="switchtab9"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="48" command="switchtab10"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="9" command="nexttab"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="9" command="prevtab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="87" command="closetab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="82" command="renametab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="34" command="nextview"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="33" command="prevview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="37" command="leftview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="39" command="rightview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="38" command="topview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="40" command="bottomview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="dechsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="inchsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="decvsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="incvsize"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="87" command="closeview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="detachview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="attach"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="79" command="splithoriz"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="69" command="splitvert"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clone"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="122" command="fullscreen"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="96" command="zoom100"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="107" command="zoominc"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="109" command="zoomdec"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="71" command="groupall"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="71" command="ungroupall"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="grouptab"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="84" command="ungrouptab"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clear"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="67" command="copy"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="65" command="selectall"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="46" command="clear_selection"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="86" command="paste"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="stopscroll"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowdown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpagedown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="find"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findnext"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findprev"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtransparency"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="112" command="dumpbuffer"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu1"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu2"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu3"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="ctrlC"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd1"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd2"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd3"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd4"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd5"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd6"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd7"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd8"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd9"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd10"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="activate" win="0"/>
	</hotkeys>
	<mouse>
		<actions>
			<action ctrl="0" shift="0" alt="0" button="1" name="copy"/>
			<action ctrl="0" shift="1" alt="0" button="1" name="select"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="select_column"/>
			<action ctrl="0" shift="0" alt="0" button="3" name="paste"/>
			<action ctrl="1" shift="0" alt="0" button="1" name="drag"/>
			<action ctrl="0" shift="0" alt="0" button="4" name="link"/>
			<action ctrl="0" shift="0" alt="0" button="2" name="menu"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="menu2"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="menu3"/>
		</actions>
	</mouse>
	<tabs>
		<tab title="ConsoleZ" use_default_icon="0">
			<console shell="" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
		</tab>
	</tabs>
	<external_commands>
 
</external_commands>
</settings>
```

**Comment by cbucher** [comment]
I don't see misconfiguration in the report.
I think you simply resize the console (when you reduce the width, the text that was on the right side of the cutoff disappears).

**Comment by twowheelmotion** [comment]
Ah I see. You are correct. If the windows is initially wide enough, everything renders. 

Thank you.
