### ISSUE TITLE
why the command prompt isn't left-aligned?

### ISSUE THREAD

**Issue by Frank-KunLi** [cbucher/console#222]
Windows Version: Windows 7 Chinese professional
ConsoleZ.x64.1.14.0.15129                                  
The command prompt always isn't left-aligned.

Like:
                                                                                            C:\Users\huaiming.lk\Desktop\ConsoleZ.x64.1.14.0.15129>
                                                                
Thanks. Look forward your help.

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
Read the documentation and follow instructions from "Language Settings" chapter.

**Comment by Frank-KunLi** [comment]
hi cbucher,  It works well with the way you introduced. Thanks for your help.
