### ISSUE TITLE
Does not work with latest git preview at https://github.com/git-for-windows/git/releases

### ISSUE THREAD

**Issue by kjeremy** [cbucher/console#226]
Previously I could set up ConsoleZ to launch the bash shell by specifying `<console shell="C:\Program Files (x86)\Git\bin\sh.exe --login -i" ... >`

With the new git-for-windows preview this doesn't work anymore.  I've changed to `<console shell="C:\Users\jkolb\AppData\Local\Programs\Git\git-bash.exe" ... >` but now I get a messagebox stating: `DLL injection has failed (reason:timeout (hook))!`

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
I tested the portable version.
PortableGit\usr\bin\sh.exe works fine with ConsoleZ.
git-bash.exe is not a Windows console application (mintty).

**Comment by nmors** [comment]
works for me using (non-portable) git bash i.e. `C:\Program Files\Git\bin\bash.exe`
however, i got the reported error when using `C:\Program Files\Git\git-bash.exe`

Make sure you are using the correct shell binary
