### ISSUE TITLE
Feature request: remove the "Administrator:" prefix even when tab is not set to run as admin

### ISSUE THREAD

**Issue by hyee** [cbucher/console#227]
As reported in #194 that the "Administrator:" prefix is shown when UAC is turned off and "Run as current user" option is selected.  My expectation is to remove the prefix , and if possible, always remove it even the program is run as administrator.

**Comment by cbucher** [comment]
@hyee please, try the last experimental version

**Comment by hyee** [comment]
Very good, it works, many thanks!

**Comment by cbucher** [comment]
Thx
