### ISSUE TITLE
Support typographic ligatures

### ISSUE THREAD

**Issue by yellowiscool** [cbucher/console#229]
Hi,

I don't know how complex it is, but a nice feature would be supporting ligatures. Monospaced fonts with ligatures such as [Hasklig](https://github.com/i-tu/Hasklig) or [FiraCode](https://github.com/tonsky/FiraCode) can be used in console for example.

**Comment by cbucher** [comment]
Hi,

I don't understand your request...

**Comment by yellowiscool** [comment]
You have a good description on [the Hasklig page](https://github.com/i-tu/Hasklig), but here is an example  (Hasklig has ligatures, Source code pro not) :

![2015-06-14 19_44_20-i-tu_hasklig](https://cloud.githubusercontent.com/assets/45740/8149702/c6748618-12cd-11e5-9b44-c24794654ef9.png)

It might be something easy to implement (just an option somewhere), but it can also break the application (Atom has some issues for example). Personally, it's just a small visual improvement. I don't mind if it's not available in ConsoleZ.

**Comment by cbucher** [comment]
@yellowiscool I read some documentation on how ligatures works with GDI rendering.
I will try to use the `GetCharacterPlacement` API.

**Comment by cbucher** [comment]
@yellowiscool please, try last beta version

**Comment by yellowiscool** [comment]
It works fine :-)

I tried with FiraCode (it needs a TTF font, the OTF font doesn't work) and it looks beautiful. Thank you :-)

![2015-08-26 11_05_27-program manager](https://cloud.githubusercontent.com/assets/45740/9489583/64cd2a48-4be2-11e5-84a8-34c0e6eedc54.png)

**Comment by cbucher** [comment]
Thx
 I could study typographic ligatures, it was interesting.
