### ISSUE TITLE
Shell title format does not work

### ISSUE THREAD

**Issue by aaroninvincea** [cbucher/console#231]
The ?s() and %s formatting for "shell title" do not work. The fix is quite simple, but I am not familiar with Git, so I will paste the diff here:

    Index: Console/ConsoleView.cpp
    ==================================================================
    --- Console/ConsoleView.cpp
    +++ Console/ConsoleView.cpp
    @@ -1475,14 +1475,18 @@
     {
        CWindow consoleWnd(m_consoleHandler.GetConsoleParams()->hwndConsoleWindow);
        CString strConsoleTitle(L"");
     
        consoleWnd.GetWindowText(strConsoleTitle);
    -	if( strConsoleTitle.Find(DEFAULT_CONSOLE_COMMAND) != -1 )
    +	if( strConsoleTitle == DEFAULT_CONSOLE_COMMAND )
        {
            strConsoleTitle = L"";
        }
    +	else if( strConsoleTitle.Find(DEFAULT_CONSOLE_COMMAND L" - ") == 0 )
    +	{
    +		strConsoleTitle = strConsoleTitle.Mid(sizeof(DEFAULT_CONSOLE_COMMAND L" - ")/sizeof(wchar_t)-1);
    +	}
        else if( this->GetConsoleHandler().IsElevated() )
        {
            if( m_strUACPrefix.IsEmpty() )
            {
                m_strUACPrefix = Helpers::GetUACPrefix().c_str();

**Comment by cbucher** [comment]
please, next time explain in which cases it does not work :wink: 

Your code doesn't work when I launch cmd.exe as administrator.

**Comment by cbucher** [comment]
@aaroninvincea please, try the last experimental version

**Comment by cbucher** [comment]
@aaroninvincea please, try the last experimental version

**Comment by cbucher** [comment]
@aaroninvincea please, try the last experimental version

**Comment by cbucher** [comment]
@aaroninvincea please, try last beta version

**Comment by cbucher** [comment]
@aaroninvincea please, try last beta version
