### ISSUE TITLE
Add support for current directory leaf format in window title

### ISSUE THREAD

**Issue by aaroninvincea** [cbucher/console#232]
I propose adding the title format %D to show the current directory leaf in the tab title. (So if %d gives "c:\Program Files (x86)\Microsoft\Whatever\example\narf", %D would just give "narf"). I have already implemented this my local copy, but I am not familiar with Git so I will paste the diff here:

    Index: Console/MainFrame.cpp
    ==================================================================
    --- Console/MainFrame.cpp
    +++ Console/MainFrame.cpp
    @@ -1367,10 +1367,13 @@
                case L't': layers.top()->str += tabView->GetTitle(); break;
                case L's': if( !bShellTitle ) { bShellTitle = true; strShellTitle = consoleView->GetConsoleCommand(); }
                           layers.top()->str += strShellTitle; break;
                case L'd': if( !bCurrentDir ) { bCurrentDir = true; strCurrentDir = consoleView->GetConsoleHandler().GetCurrentDirectory(); }
                           layers.top()->str += strCurrentDir; break;
    +			case L'D': if( !bCurrentDir ) { bCurrentDir = true; strCurrentDir = consoleView->GetConsoleHandler().GetCurrentDirectory(); }
    +			           { wstring s = strCurrentDir; s = s.substr(s.rfind(L'/')+1); s = s.substr(s.rfind(L'\\')+1); layers.top()->str += s; }
    +			           break;
                case L'A': layers.top()->str += consoleView->GetConsoleHandler().IsElevated()? L"y" : L""; break;
                case L'U': layers.top()->str += ( consoleView->IsRunningAsUser() )? L"y" : L""; break;
                case L'N': layers.top()->str += ( consoleView->IsRunningAsUserNetOnly() )? L"y" : L""; break;
                default:
                    goto error;

**Comment by cbucher** [comment]
Hi,
Create a pull request, that's really easy:
https://help.github.com/articles/using-pull-requests/

**Comment by cbucher** [comment]
@aaroninvincea please, try the last experimental version

**Comment by DerellLicht** [comment]
Actually, this argument appears to be %d not %D (the latter produces an error!!)

**Comment by cbucher** [comment]
Then you didn't try the last experimental version...

**Comment by DerellLicht** [comment]
Ah... true, I did not; I will do so in the morning... perhaps that will address the issue that I posted separately as well!!

**Comment by cbucher** [comment]
@aaroninvincea please, try the last experimental version

**Comment by cbucher** [comment]
@aaroninvincea please, try the last experimental version
@DerellLicht please, try the last experimental version

**Comment by DerellLicht** [comment]
Yes, excellent!  Actually, I had tried it back on June 25, and it was working well then, I just forgot to post results back here; sorry!!  It works *very* well now.

**Comment by cbucher** [comment]
thx
