### ISSUE TITLE
"Clone in new Tab" doesn't keep the current directory

### ISSUE THREAD

**Issue by Ithildir** [cbucher/console#233]
I think this is a regression bug in 1.14.0.15129, because this feature works perfectly in 1.13.0.15044.

**Expected behavior:**
A new tab opens and the current directory of the new tab is the same of the old one.

**Actual behavior:**
The new tab has the startup directory as current dir.

BTW, thank you so so much for ConsoleZ! :blush:

**Comment by cbucher** [comment]
@Ithildir please, try the last experimental version

**Comment by Ithildir** [comment]
I tried it, it works! :smile: Thank you very much!

**Comment by rofrol** [comment]
Doesn't work for me. Version ConsoleZ.1.15.0.15211.7z
