### ISSUE TITLE
ConsoleZ does not work with Git Bash of git-for-windows

### ISSUE THREAD

**Issue by kKdH** [cbucher/console#234]
When i try to use the git bash of git-for-windows (Git-2.4.3.1-2nd-release-candidate-32-bit) as ConsoleZ shell, ConsoleZ freezes and reports:
![19-06-2015 13-18-11](https://cloud.githubusercontent.com/assets/11158578/8252492/c80a80ba-1686-11e5-81a5-7e49e2637658.png)

shell is: C:\Program Files (x86)\Git\git-bash.exe  --login -i 
and my home directory as startup dir.

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

Please, search in closed issues before opening duplicates.
#226
