### ISSUE TITLE
Wiki page on building is not complete

### ISSUE THREAD

**Issue by devcooch** [cbucher/console#236]
Hello,

The "how to compile" page (https://github.com/cbucher/console/wiki/How-to-compile) says you need Boost.
I have Boost, however it's not clear for me where this configuration is coming from? I don't see any path to boost in project/solution.
What is recommended way for that?

Cheers,
Dmitry

**Comment by cbucher** [comment]
See files named *BoostIncludePath.props.user.template*, the usage is described inside.
Or simply edit "Include directories" in project settings.
