### ISSUE TITLE
Color Key Transparency Question

### ISSUE THREAD

**Issue by AMWARD** [cbucher/console#237]
When I turn on color key transparency I can click through console to the desktop. I would like to keep the transparency but have a transparent "back" to the window so I can't click or right click through to the desktop. I am using 1.14.0.15129 on Win7.

**Comment by cbucher** [comment]
The behavior of the window change depending on color key.
With some colors like RGB(0,0,0) or RGB(255,255,255) the mouse control can pass through,  but for other colors it can't.

https://social.msdn.microsoft.com/Forums/en-US/a52488a0-efa4-43b7-9c3b-106c10d5c909/different-behavior-for-setlayeredwindowattributes?forum=windowssdk

I can't find any precise documentation. But it may be related to AERO.

Just avoid pure black and pure white. Usually magenta is chosen.
