### ISSUE TITLE
"Clone in new tab" doesn't quite work right

### ISSUE THREAD

**Issue by DerellLicht** [cbucher/console#239]
I just updated to build 15129 (x64 version), and this seems to now have a bug in it.
I use "Clone in new tab" frequently, and it's been previously working quite nicely.  With this build, though, the behavior of this function has changed... 
First, I have added %d in the Main title format, but still use %t in Tab title format.
So here's the situation:
1. I have a custom tab definition that opens a tab in c:\SourceCode\vci
2. then did "cd bcs_fix" (current directory is now c:\SourceCode\vci\bcs_fix )
Tab shows label specified for that tab (VCI Projects).
3. right-click on tab, select "Clone in new tab".
The new tab is opened in c:\SourceCode\vci, rather than c:\SourceCode\vci\bcs_fix as it previously did (and as I intended).  Further, tab label is c:\SourceCode\vci\bcs_fix, which is not where it opened, and is not the correct label "VCI Projects" either.

I was previously using build 15044, and it worked as I expected...

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by DerellLicht** [comment]
Hokay, nevermind.  build 15173 works fine...
Sorry about that
