### ISSUE TITLE
Environment variables lost upon startup

### ISSUE THREAD

**Issue by tz77** [cbucher/console#240]
If you define an environment variable via "set foo=bar" and start console.exe afterwards, then the environment variable %foo% is no longer defined inside the console frontend for all recent versions of console.exe beyond 1.10.0.14089. Up to build number 1.10.0.14089 this used to work.

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
see #225
