### ISSUE TITLE
Detached view can't be attached again

### ISSUE THREAD

**Issue by wayne-zhang** [cbucher/console#244]
1. Detach a view (File > Detach View);
2. Console attached;
3. Attach consoles (File > Attach Consoles);
4. Nothing happened.

A normal CMD/Console (start by cmd.exe) can be attached, but it can't be attached again when it was detached once.

Tested on version 1.14.0.15129 X64 version.

**Comment by cbucher** [comment]
I know, it's be design. DLL injection can be done only one time with the same DLL.
There is no simple solution.

**Comment by wayne-zhang** [comment]
Thank you for the quick response. It's really a nice tool, makes Windows console has the similar features as Linux's.
