### ISSUE TITLE
Handle vertical re-sizing of console

### ISSUE THREAD

**Issue by khazhyk** [cbucher/console#245]
Two things related to this behavior:
Pressing alt toggles the visibility of the menu bar if it isn't set to be permanently visible.

1)
Is it possible to disable this behavior?
I can't find a hotkey setting for this.

2)
When the menu bar is toggled in this way it doesn't seem to send the "resize" to the underlying console, so full screen console applications break since the screen size is wrong. (If you resize the whole window it works properly)
This also happens when a new tab is open causing the tab view to unhide.

**Comment by cbucher** [comment]
1) no
2) I can't reproduce your issue
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by khazhyk** [comment]
I'm using git bash as my underlying shell.

Steps to reproduce:

Open a full screen application such as irssi/htop (I'm doing this over an ssh session if it matters)
![image](https://cloud.githubusercontent.com/assets/1542025/8598475/e081a1e4-2628-11e5-83d8-aa2d9a725bcc.png)

Press alt or otherwise vertically resize the console, the underlying application doesn't resize.
![image](https://cloud.githubusercontent.com/assets/1542025/8598477/e50f13b8-2628-11e5-8961-5de1fb48d80d.png)

Horizontally resize the console, the underlying application resizes to the correct vertical/horizontal size.
![image](https://cloud.githubusercontent.com/assets/1542025/8598497/fde3bd1c-2628-11e5-9352-d742314cebf3.png)

When using mintty running git bash resizing vertically works as expected: any "fullscreen" app resizes.

The vertical resize issue happens when I use git bash which opens in the windows command prompt, or if I use cmd.exe directly. Horizontal resizing additionally doesn't work in cmd.exe

**Comment by cbucher** [comment]
**https://github.com/cbucher/console/wiki/How-to-Report-an-Issue**

ConsoleZ only displays the console buffer.
Show the real console (`View / Console Window`) and notice you have the same bug.
In this case this is not a ConsoleZ's issue but an issue of your console application...

**Comment by khazhyk** [comment]
Well I guess it's more of a feature request than a bug. I installed consolez because the standard windows console isn't very good, so saying that the "underlying console" doesn't support it doesn't really do much. The underlying console doesn't support resizing horizontally either, but that works fine in consolez.

**Comment by cbucher** [comment]
Can be a SSH client application's issue or a terminal configuration issue.
My advice:
download OpenSSh for Windows: http://www.mls-software.com/opensshd.html
You can install only client.

you can configure your tab like this: `"<path to ssh>\ssh.exe" -l <username> <server>`
By default `"<path to ssh>\ssh.exe"`is `"C:\Program Files\OpenSSH\bin\ssh.exe"`.

manual:
http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man1/slogin.1?query=ssh&sec=1

**Comment by johnpbloch** [comment]
FYI @khazhyk if you update the default display options in git bash, those changes will also make their way to ConsoleZ.
