### ISSUE TITLE
Settings UI doesn't work, unless prefs file already exists

### ISSUE THREAD

**Issue by 0xabu** [cbucher/console#247]
After copying the binaries for a recent preview version (1.15.0.15183) onto a completely clean (re-installed) machine, the settings dialog was unable to render anything useful. It looked like this:
![image](https://cloud.githubusercontent.com/assets/13037682/8657932/6bce83aa-2955-11e5-8f95-7fe719579390.png)

After poking around for a bit, I realised that if I just copied over %APPDATA%/Console/console.xml from another machine, then the settings dialog started working again.

**Comment by cbucher** [comment]
You don't have rights to write a configuration file in console.exe directory.

**Comment by 0xabu** [comment]
Right. I installed to C:\Program Files\ConsoleZ, which must be a fairly common setup. The typical modern behaviour is to write prefs in the user's profile directory, and not place them in the application directory. Especially if it's not user-writable :)

**Comment by cbucher** [comment]
I agree.
That's something I should have fix a long time ago, but I forgot...

**Comment by cbucher** [comment]
@0xabu please, try the last experimental version

**Comment by 0xabu** [comment]
Seems to be fixed, thanks!
