### ISSUE TITLE
cannot dir to network drive

### ISSUE THREAD

**Issue by worrawutp** [cbucher/console#250]
I have my network drive mapping to, let say, drive Z:\
I cannot change directory to that Z:\. I got a message return "The system cannot find the drive specified." when I type Z: and hit enter at command prompt.  
But I can goto drive Z: by doing the same thing when I use normal windows command prompt (cmd.exe)

I use latest consolez 1.14.0.15129

Is there any setup that I could take into account ?

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue
This problem doen't concern ConsoleZ!
