### ISSUE TITLE
Input in one tab sometimes gets copied to another tab

### ISSUE THREAD

**Issue by fsufitch** [cbucher/console#252]
There is an intermittent occurrence in which keyboard input in one tab sometimes gets invisibly duplicated in another open tab. Both times I have seen it, the nested terminal was the Windows command prompt (cmd.exe), and I was running Cygwin in one or both of the consoles.

Since all input is duplicated, this is a very big security problem. The second (and last) time it occured for me, it duplicated several git commands and inputs -- *including my private key password that was "invisibly" typed into the intended tab* -- into a chatroom in another tab.

I am not able to reliably reproduce this bug, so I unfortunately cannot provide steps to test it. I wanted to raise the issue nonetheless since it entirely kills ConsoleZ for me.

Thanks for looking into it.

*Edit: This is ConsoleZ 1.14.0.15129 running on Windows 7 Professional*

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
before report a bug, just read documentation and verify you haven't activate a **feature**.
you grouped unintentionally console inputs ...
if you are not comfortable with keyboard, you can suppress the hotkeys in the settings

![image](https://cloud.githubusercontent.com/assets/363759/9080578/3609e68a-3b55-11e5-910e-72c5ee47d317.png)

And before someone says it is not documented, just read introduction:

![image](https://cloud.githubusercontent.com/assets/363759/9080612/a6ba4d70-3b55-11e5-9070-9264ca35fdc8.png)
