### ISSUE TITLE
Window buffer is wrong in fullscreen

### ISSUE THREAD

**Issue by Frexuz** [cbucher/console#254]
Anything wrong in my settings, or is this a bug? I've tried buffer size as 0 and 0 as well (maybe 0 meant auto)

v1.14.0.15129 on Windows 10

![image](https://cloud.githubusercontent.com/assets/49692/9135536/ee42c4a0-3d0e-11e5-912e-938fb6aaa16d.png)

![image](https://cloud.githubusercontent.com/assets/49692/9135554/1badf9aa-3d0f-11e5-98fc-d27363d6ef4b.png)

![image](https://cloud.githubusercontent.com/assets/49692/9135510/856a3ec2-3d0e-11e5-8139-b489a881b2d4.png)

Fullscreen buffer is the same size as the non-fullscreen window size:
![image](https://cloud.githubusercontent.com/assets/49692/9135590/8ca7f6ba-3d0f-11e5-9642-a0b5757fe137.png)

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue
