### ISSUE TITLE
Window transparency - Color key + Alpha at the same time

### ISSUE THREAD

**Issue by mbodomi** [cbucher/console#255]
(hmmm hmmm. maybe? for using irssi while watching movies)

**Comment by cbucher** [comment]
@mbodomi please, try last beta version

**Comment by cbucher** [comment]
@mbodomi please, try last beta version

**Comment by mbodomi** [comment]
I tried it! It didn't really work well.

**Comment by cbucher** [comment]
You come too late!
I don't have a crystal ball, can you be more explicit.
