### ISSUE TITLE
Running batch file under tab closes the tab when batch file completes

### ISSUE THREAD

**Issue by lokimon** [cbucher/console#256]
Steps to reproduce
Create any batch file. a.bat
Set a.bat as the shell for a tab.
Open that tab with the -t option on a command line.
a.bat does run, but tab goes away as soon as a.bat completes.

Is there anyway to keep it open?  So that you can see the results or run the batch command again.

Thanks for looking

**Comment by cbucher** [comment]
This is  the normal behavior of a batch file execution...
Read cmd.exe command line documentation!

**Comment by lokimon** [comment]
Hang on.

When I start a command prompt and run a batch file in that command prompt, I've never had the command prompt close.  But maybe this is a new feature request. 

I am a programmer on a cross platform project.  When I complete a feature, I need to build it for multiple platforms.  What I would like to do is create tabs for all the compilers, and then run a custom batch file to start the build.  I would like the tab to stay open, so I can see the results.  I can then create a shortcut that opens all those tabs, and off it goes.  I can currently open all the tabs, but I have to type in the batch file in each one.  When I do this the consolez tab doesn't close after completing the batch file.  I am just trying to eliminate extra steps, and perhaps make consolez a little more useful.

So if the shell option isn't suppose to work that way, maybe a run batch option can be added.  This would open the command prompt and just run the batch file.  Just as I would do if I typed it in after opening the tab.

**Comment by cbucher** [comment]
A programmer can search information and read a manual...
https://technet.microsoft.com/en-us/library/bb490880.aspx
![image](https://cloud.githubusercontent.com/assets/363759/9393811/9901ec5c-4784-11e5-99a8-f8ebd0e1b87f.png)

:trollface: **use `%SystemRoot%\System32\cmd.exe /K ...`** :trollface:

Typing `dummy.cmd` in the command prompt (aka cmd.exe) is like typing the command `call dummy.cmd`. The script is interpreted by the current command prompt.

Executing `dummy.cmd` launches the command line `%SystemRoot%\System32\cmd.exe /C dummy.cmd` to interpret the script. And with /C option, the process ends when script is finished.
You can verify by pressing ⊞ Win+R and typing `dummy.cmd`.

**Comment by lokimon** [comment]
Actually, I was hoping to not have to use the /K, which I did know about and does sort of work.  

The issue with that is i start about 6 different compiles in 6 different tabs from one shortcut.  If one of those compiles fail for whatever reason, I'd like to be able to make a fix, hit the up arrow and restart that particular compile.  Using the shell command doesn't give me that.

I 100% understand that what I'm asking for is a new feature and is just a suggestion to make your fork better.  If you don't want suggestions, that's fine.  But all these insulting emots when you are not taking the effort to understand isn't going to win you any advocates.  Just saying.

**Comment by cbucher** [comment]
> I can currently open all the tabs, but I have to type in the batch file in each one.

in the manual you can see an example of -r parameter
with this parameter you can specify the batch file on ConsoleZ command line...
there is no reason to create a tab per batch file

>The issue with that is i start about 6 different compiles in 6 different tabs from one shortcut. If one of those compiles fail for whatever reason, I'd like to be able to make a fix, hit the up arrow and restart that particular compile. Using the shell command doesn't give me that.

Ok the build command is not in the history...
But what is the problem?
You don't want to type the build command because is too long?
- you can use doskey and set an alias (only one letter if you want)
- you can create batch file, with a short name, in  the path
- ...

>I 100% understand that what I'm asking for is a new feature and is just a suggestion to make your fork better. 

I cannot see a feature request but only basic questions!.
