### ISSUE TITLE
UI becomes very ugly when get some Chinese charaters

### ISSUE THREAD

**Issue by heartbeast** [cbucher/console#257]
![consolez](https://cloud.githubusercontent.com/assets/11706335/9384322/5b5678ac-4782-11e5-9455-e36a6d3e06a3.PNG)

One picture shows all

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

Read the manual (press F1 in ConsoleZ):

![image](https://cloud.githubusercontent.com/assets/363759/9384436/c1ba5f32-4750-11e5-94f4-1d02082b1acb.png)

**Comment by heartbeast** [comment]
Thank very much!!
Now it's my favorite Console!
