### ISSUE TITLE
Minimize to tray on close/minimize button

### ISSUE THREAD

**Issue by olukelo** [cbucher/console#259]
Can you add this option? It wiil be super!

**Comment by cbucher** [comment]
You have a tray icon, which restore the application when clicked, and a minimize button.
What is missing?

**Comment by olukelo** [comment]
When  minimized app  is present in two places - in tray, and in main panel. This adds mess to my working layout. Of course it is up to you, but as a user, I prefer to have app icon only in one place, either main panel or tray(preferable).

**Comment by cbucher** [comment]
I don't know what is a main panel.
I assume you speak of taskbar.
You can remove the taskbar button in the settings...
