### ISSUE TITLE
ctrl+c with bash unexpectedly closes tab

### ISSUE THREAD

**Issue by draenor** [cbucher/console#264]
Pressing `ctrl+c` in a bash tab is the unexpected equivalent of the default `ctrl+w` close tab hotkey. This does not happen in console2. 

The mingw version of bash used: https://git-scm.com/download/win

Shell: 

    C:\Program Files\Git\bin\sh.exe --login -i

Same if I run it through cmd.exe

    C:\Windows\System32\cmd.exe /c "C:\Program Files\Git\bin\bash.exe" --login -i

I also tried to trap the signal in bash 

    trap '' SIGINT

but still the shell exits immediately with a closed tab as result

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

duplicate

**Comment by afayes** [comment]
having the same issue

**Comment by FredoVelcro** [comment]
@cbucher giving the duplicate link would be more useful for readers ;) 
https://github.com/cbucher/console/issues/262

**Comment by cbucher** [comment]
@FredoVelcro Find the right link (the one with a label) two lines below required a superhero, you saved this issue ;)

**Comment by FredoVelcro** [comment]
mission over ;)
