### ISSUE TITLE
Program sometimes crash

### ISSUE THREAD

**Issue by hyee** [cbucher/console#265]
I've using 1.15.0.15237 32bit version, sometimes the prorgam would crash, normally happening when draging or maximizing the window, as a result, its attaching process(java.exe for example) is still running in background and not able to be accessed. The issue happens more frequently in Win10.

I didn't experience the issue when I was using v1.15.0.15181.

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by hyee** [comment]
ConsoleZ aero x86 1, 15, 0, 15237
    is elevated? no
    UAC prefix "Administrator: "
    Tab (active): dbcli
      View (active):  DBCLI - Not Connected
      is elevated? no
      Windows console font
    font index: 4
    face name: Lucida Console
    font familly: 54 MODERN vector true type
    font weight: 400
    font size: width=6 height=10
    max window size: cols=217 rows=74
      ConsoleZ font
    GetFontLanguageInfo returns 262144.
    The font contains extra glyphs not normally accessible using the code page.

    Monitors 1
      Flags 1  primary
      DeviceID \\?\DISPLAY#SEC5441#4&34a8404&0&UID67568640#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
      DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0000
      DeviceName \\.\DISPLAY1\Monitor0
      DeviceString Generic PnP Monitor
      StateFlags 3
      Rect (0,0)x(1366,768)
      Work (0,0)x(1304,768)
    Settings file C:\Soft\dbcli\bin\ConsoleZ\console.xml
    <?xml version="1.0"?>
    <settings>
        <console change_refresh="10" refresh="100" rows="200" columns="200" buffer_rows="9999" buffer_columns="1000" shell="" init_dir="" start_hidden="0" save_size="0" background_text_opacity="255">
            <colors background_text_opacity="255">
                <color id="0" r="0" g="0" b="0"/>
                <color id="1" r="0" g="0" b="128"/>
                <color id="2" r="0" g="150" b="0"/>
                <color id="3" r="0" g="150" b="150"/>
                <color id="4" r="170" g="25" b="25"/>
                <color id="5" r="128" g="0" b="128"/>
                <color id="6" r="128" g="128" b="0"/>
                <color id="7" r="192" g="192" b="192"/>
                <color id="8" r="128" g="128" b="128"/>
                <color id="9" r="0" g="100" b="255"/>
                <color id="10" r="0" g="255" b="0"/>
                <color id="11" r="0" g="255" b="255"/>
                <color id="12" r="255" g="50" b="50"/>
                <color id="13" r="255" g="0" b="255"/>
                <color id="14" r="255" g="255" b="0"/>
                <color id="15" r="255" g="255" b="255"/>
            </colors>
            <cursor style="0" r="255" g="255" b="255"/>
            <background type="0" r="0" g="0" b="0">
                <image file="" relative="0" extend="0" position="0">
                    <tint opacity="0" r="0" g="0" b="0"/>
                </image>
            </background>
        </console>
        <appearance>
            <font name="Lucida Console" size="9" bold="0" italic="0" smoothing="2" bold_intensified="0" italic_intensified="0" extra_width="0" ligature="0">
                <color use="0" r="0" g="255" b="0"/>
            </font>
            <window title="ConsoleZ" icon="" use_tab_icon="1" use_console_title="0" show_cmd="1" show_cmd_tabs="1" use_tab_title="1" trim_tab_titles="20" trim_tab_titles_right="0" main_title_format="?U([%u] )?N({%u} )%m?s( - %s)" tab_title_format="?s( %s):( DBCLI - Not Connected)"/>
            <controls show_menu="1" show_toolbar="0" show_statusbar="0" show_tabs="1" hide_single_tab="0" show_scrollbars="1" flat_scrollbars="1" tabs_on_bottom="0" hide_tab_icons="1" show_searchbar="1"/>
            <styles caption="1" resizable="1" taskbar_button="1" border="0" inside_border="2" tray_icon="1" quake_like="0" jumplist="1" integrated_ime="1" quake_animation_time="300" hide_when_inactive="0">
                <selection_color r="128" g="128" b="128"/>
            </styles>
            <position x="-1" y="-1" dock="-1" snap="-1" z_order="0" save_position="0" w="-1" h="-1" save_size="0"/>
            <transparency type="0" active_alpha="206" inactive_alpha="255" r="0" g="0" b="0"/>
            <fullscreen start_in_fullscreen="0" fullscreen_monitor="0"/>
        </appearance>
        <behavior>
            <copy_paste copy_on_select="1" clear_on_copy="0" no_wrap="1" trim_spaces="1" copy_newline_char="0" sensitive_copy="1" include_left_delimiter="0" include_right_delimiter="0" left_delimiters=" ([" right_delimiters=" )]" eol_spaces="1" rtf="1"/>
            <scroll page_scroll_rows="0"/>
            <tab_highlight flashes="3" stay_highligted="1"/>
            <close allow_closing_last_view="0" confirm_closing_multiple_views="1"/>
            <focus follow_mouse="0"/>
            <instance allow_multi="0"/>
            <clone use_current_dir="1"/>
            <search match_case="0" match_whole_word="0"/>
            <runas use_credprov="1"/>
        </behavior>
        <hotkeys use_scroll_lock="1">
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="83" command="settings"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="112" command="help"/>
            <hotkey ctrl="0" shift="0" alt="1" extended="0" code="115" command="exit"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="112" command="newtab1"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="113" command="newtab2"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="114" command="newtab3"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="115" command="newtab4"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="116" command="newtab5"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="117" command="newtab6"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="118" command="newtab7"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="119" command="newtab8"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="120" command="newtab9"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="121" command="newtab10"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="122" command="newtab11"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="123" command="newtab12"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="49" command="switchtab1"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="50" command="switchtab2"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="51" command="switchtab3"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="52" command="switchtab4"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="53" command="switchtab5"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="54" command="switchtab6"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="55" command="switchtab7"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="56" command="switchtab8"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="57" command="switchtab9"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="48" command="switchtab10"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtab11"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtab12"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="9" command="nexttab"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="9" command="prevtab"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="87" command="closetab"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="82" command="renametab"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="1" code="34" command="nextview"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="1" code="33" command="prevview"/>
            <hotkey ctrl="0" shift="0" alt="1" extended="1" code="37" command="leftview"/>
            <hotkey ctrl="0" shift="0" alt="1" extended="1" code="39" command="rightview"/>
            <hotkey ctrl="0" shift="0" alt="1" extended="1" code="38" command="topview"/>
            <hotkey ctrl="0" shift="0" alt="1" extended="1" code="40" command="bottomview"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="dechsize"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="inchsize"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="decvsize"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="incvsize"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="87" command="closeview"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="detachview"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="attach"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="79" command="splithoriz"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="69" command="splitvert"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clone"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="122" command="fullscreen"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="96" command="zoom100"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="107" command="zoominc"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="109" command="zoomdec"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="groupall"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="71" command="ungroupall"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="84" command="grouptab"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="84" command="ungrouptab"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="76" command="clear"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="1" code="45" command="copy"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="65" command="selectall"/>
            <hotkey ctrl="0" shift="1" alt="0" extended="0" code="8" command="clear_selection"/>
            <hotkey ctrl="0" shift="1" alt="0" extended="1" code="45" command="paste"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="paste_selection"/>
            <hotkey ctrl="1" shift="0" alt="0" extended="0" code="81" command="stopscroll"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowup"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowdown"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageup"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpagedown"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolleft"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolright"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageleft"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageright"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="find"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findnext"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findprev"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtransparency"/>
            <hotkey ctrl="1" shift="1" alt="0" extended="0" code="112" command="dumpbuffer"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu1"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu2"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu3"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="ctrlC"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd1"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd2"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd3"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd4"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd5"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd6"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd7"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd8"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd9"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd10"/>
            <hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="activate" win="0"/>
        </hotkeys>
        <mouse>
            <actions>
                <action ctrl="0" shift="0" alt="0" button="2" name="copy"/>
                <action ctrl="0" shift="0" alt="0" button="1" name="select"/>
                <action ctrl="0" shift="1" alt="0" button="1" name="select_column"/>
                <action ctrl="0" shift="0" alt="0" button="2" name="paste"/>
                <action ctrl="1" shift="0" alt="0" button="1" name="drag"/>
                <action ctrl="0" shift="0" alt="0" button="4" name="link"/>
                <action ctrl="0" shift="0" alt="0" button="0" name="menu"/>
                <action ctrl="0" shift="0" alt="0" button="0" name="menu2"/>
                <action ctrl="0" shift="0" alt="0" button="0" name="menu3"/>
            </actions>
        </mouse>
        <tabs>
            <tab title="dbcli" use_default_icon="0">
                <console shell="..\..\dbcli.bat" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
                <cursor style="12" r="255" g="255" b="255"/>
                <colors background_text_opacity="255">
                    <color id="0" r="0" g="0" b="0"/>
                    <color id="1" r="0" g="0" b="128"/>
                    <color id="2" r="0" g="128" b="0"/>
                    <color id="3" r="0" g="128" b="128"/>
                    <color id="4" r="128" g="0" b="0"/>
                    <color id="5" r="128" g="0" b="128"/>
                    <color id="6" r="128" g="128" b="0"/>
                    <color id="7" r="192" g="192" b="192"/>
                    <color id="8" r="128" g="128" b="128"/>
                    <color id="9" r="0" g="0" b="255"/>
                    <color id="10" r="0" g="255" b="0"/>
                    <color id="11" r="0" g="255" b="255"/>
                    <color id="12" r="255" g="0" b="0"/>
                    <color id="13" r="255" g="0" b="255"/>
                    <color id="14" r="255" g="255" b="0"/>
                    <color id="15" r="255" g="255" b="255"/>
                </colors>
            </tab>
            <tab title="dbcli_db2" use_default_icon="0">
                <console shell="..\..\dbcli.bat &quot;set database db2&quot;" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
                <cursor style="12" r="255" g="255" b="255"/>
                <colors background_text_opacity="255">
                    <color id="0" r="0" g="0" b="0"/>
                    <color id="1" r="0" g="0" b="128"/>
                    <color id="2" r="0" g="128" b="0"/>
                    <color id="3" r="0" g="128" b="128"/>
                    <color id="4" r="128" g="0" b="0"/>
                    <color id="5" r="128" g="0" b="128"/>
                    <color id="6" r="128" g="128" b="0"/>
                    <color id="7" r="192" g="192" b="192"/>
                    <color id="8" r="128" g="128" b="128"/>
                    <color id="9" r="0" g="0" b="255"/>
                    <color id="10" r="0" g="255" b="0"/>
                    <color id="11" r="0" g="255" b="255"/>
                    <color id="12" r="255" g="0" b="0"/>
                    <color id="13" r="255" g="0" b="255"/>
                    <color id="14" r="255" g="255" b="0"/>
                    <color id="15" r="255" g="255" b="255"/>
                </colors>
            </tab>
        </tabs>
        <external_commands>
    </external_commands>
    </settings>

**Comment by cbucher** [comment]
Please provide a crash dump.

To generate a crash dump: create registry key `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps`. If you didn't install a post mortem debugger, you should find crash dump here: `%LOCALAPPDATA%\CrashDumps`.
If you need assistance, you can read [this documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb787181%28v=vs.85%29.aspx).

Zip it and upload it to Dropbox, Google Drive, or a similar service, then post the link.

**Comment by hyee** [comment]
Hello,

The dump is available at https://drive.google.com/file/d/0B3b0xhzRjQoQd0hmb0pxSjhsZEk/view?usp=sharing

Thank you.

**Comment by cbucher** [comment]
Hello,

I analyzed the crash dump and I found the origin of the crash.
Curiously, the origin is not a recent modification. Code was already wrong five years ago.

Regards

**Comment by cbucher** [comment]
@hyee please, try last beta version

**Comment by hyee** [comment]
It's fixed , thank you very much!

**Comment by cbucher** [comment]
thx
