### ISSUE TITLE
[Beta 1.15.0.15252] Scrolling doesn't work when the scrollbars are hidden

### ISSUE THREAD

**Issue by yellowiscool** [cbucher/console#269]
How to reproduce :

 * Disable the scrollbars
 * Display a text file
 * Try to scroll

A gif showing the issue :
![console2](https://cloud.githubusercontent.com/assets/45740/9784681/0213b90e-57ad-11e5-885b-4a9c4d99171e.gif)

How it should be : 
![console2b](https://cloud.githubusercontent.com/assets/45740/9784680/02137430-57ad-11e5-9965-99f584541de7.gif)

My diagnostic file:
http://pastebin.com/mjJ7jLBF

I use ZSH with a Cygwin Shell but I have exactly the same issue with a classic cmd.exe shell. I also disabled typographic ligatures for this report.

**Comment by cbucher** [comment]
@yellowiscool please, try last beta version

**Comment by yellowiscool** [comment]
Thank you, it looks like it's fixed.
