### ISSUE TITLE
Add command-line switch to toggle window visibility

### ISSUE THREAD

**Issue by knobhead** [cbucher/console#276]
Hi, 

thanks for this wonderful fork and your efforts. Exactly what I needed.

However, I'm missing one tiny little feature: 
I'd love to see another command-line switch to toggle the visibility of a ConsoleZ instance.
I mostly use ConsoleZ completely hidden. My file manager gives me an option to "open terminal here". It does work and successfully opens a new tab in ConsoleZ with correct paths and everything, but I still have to press my hotkey to actually show the ConsoleZ window.

Win 7 32bit
ConsoleZ version 1,15

Any chance of this being implemented? 

Unfortunately I'm not gifted with coding skills, so I can't hack it myself and send you a pull request...

Thanks!

**Comment by cbucher** [comment]
Hi,

Sure, that's a good idea.

**Comment by knobhead** [comment]
:+1: :bow:

**Comment by cbucher** [comment]
@knobhead please, try last experimental version

**Comment by knobhead** [comment]
hi @cbucher , cool, seems to work like a charm for me! (Win 7 32bit) :+1:

**Comment by cbucher** [comment]
thx
