### ISSUE TITLE
Menu bar hidden

### ISSUE THREAD

**Issue by jurajpetrik** [cbucher/console#277]
So I managed to click the menu setting to hide the menu. How can I bring it back? Why does it even let me do that?

![consolez-screen](https://cloud.githubusercontent.com/assets/5968938/10370053/8ddbf564-6ddd-11e5-9c42-a9a90472bae9.png)

**Comment by cbucher** [comment]
press alt key (like internet explorer)

**Comment by jurajpetrik** [comment]
Perfect, thanks.
