### ISSUE TITLE
Option to maximize on start

### ISSUE THREAD

**Issue by AndiDog** [cbucher/console#278]
I don't want to use full screen mode because with one screen, I need access to other windows as well. Therefore an option to maximize on start would be really helpful.

**Comment by cbucher** [comment]
Every Windows GUI application can be maximized on start. There is no need for an option.
- shortcut/taskbar properties : http://www.computerhope.com/tips/tip201.htm.
- script: `start /?`

**Comment by AndiDog** [comment]
Fair enough. When attaching Console to the start bar, the setting has to be made on the .exe

**Comment by markchalloner** [comment]
I'ld like to reopen this issue. There are applications (e.g. Royal TS) that support embedding ConsoleZ. Without an option to maximize, an ugly border is shown:

![screenshot208](https://cloud.githubusercontent.com/assets/665830/12199385/9f6d1ee6-b60f-11e5-86d8-f8abbf5c00b4.png)

**Comment by cbucher** [comment]
You can remove border in styles settings.
