### ISSUE TITLE
MSYS2 in ConsoleZ can't clear screen properly

### ISSUE THREAD

**Issue by voltagex** [cbucher/console#281]
Starting nano, or clearing the screen doesn't work properly - previous output is left over

![image](https://cloud.githubusercontent.com/assets/159567/10593337/9f36fd42-770e-11e5-8c66-df32277b96c6.png)
![image](https://cloud.githubusercontent.com/assets/159567/10593343/ac61c13c-770e-11e5-91e6-e1ab30f6ecb2.png)

Shell is set to

`C:\msys64\usr\bin\sh.exe -c 'MSYSTEM=MSYS exec /bin/sh --login -i`

Any ideas?

I'm using 1.15.0.15253

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by voltagex** [comment]
Apologies. Seems like it occurs "outside" of ConsoleZ as well - doesn't explain why it doesn't happen when launching MSYS2 normally, though.

**Comment by Lunatrius** [comment]
In MSYS1 clear was just an alias (`alias clear='$COMSPEC //C cls'`) while in MSYS2 it's a native binary. It works fine with `Mintty`, but fails with `cmd`.

**Comment by yoshiwaan** [comment]
I only find this is the case if I use `exec /bin/sh --login -i` when starting a tab.

If I just call C:\msys64\usr\bin\sh.exe -i --login (and set the environment variables I need in the ENVIRONMENT section for the tab in consoleZ) then things work much better, including clear.
I'm not sure if there are any downsides to doing this as I've just started doing it in this manner, but I've found none so far.
For anyone interested the environment variables I've found I've needed to set in the Environment tab of Consolez to get this working properly are:
* MSYSTEM=MSYS
* TERM=cygwin
* PATH=/usr/local/bin:/usr/bin:/bin:/opt/bin:%PATH%
* HOME=%USERPROFILE%

So I would say to try that unless someone comes along and educates me as to why it's better to use the exec form.

**Comment by yoshiwaan** [comment]
Okay, found it pretty easily. This is an MSYS2 problem. 

The /etc/profile file created by MSYS2 (which gets run when the --login script is passed to bash) sets this:
```
export TERM=xterm-256color
```
Which is why clear doesn't work. Running a command like `export TERM=cygwin` fixes clear for me.

The short term fix for this is to set the TERM correctly in your user profile for now (for example ~/.bash_profile) as any values you pass when calling bash are overwritten by this setting. Hopefully that /etc/profile can be fixed upstream from MSYS so it's only set if TERM doesn't already exist.

**Comment by voltagex** [comment]
Why is `export TERM=xterm-256color` the problem? What does mintty/MSYS2 actually support?

**Comment by cbucher** [comment]
[source](http://tldp.org/HOWTO/Text-Terminal-HOWTO-1.html)

>A terminal consists of a screen and keyboard that one uses to communicate remotely with a computer (the host). One uses it almost like it was a personal computer but the terminal is remote from its host computer that it communicates with (on the other side of the room or even on the other side of the world). Programs execute on the host computer but the results display on the terminal screen. Originally terminals were stand-alone devices with no computational ability and thus they were once much cheaper in cost than computers. They had no pictures or audio, but could only display text and were thus called "text terminals". Today, the cost of PC computers is so low that one may use a PC like a text terminal by running a software program to make it behave like an old text terminal. 

The environment variable TERM defines the terminal name (physical or emulated) and so indicates terminal capabilities. Applications will read this variable to know the capabilities of the terminal.
If you indicate a wrong terminal, some functions will fail.

Here you emulate a terminal in a Windows console. Windows console only handle 16 colors. Intuitively, `xterm-256color` is not the good one.
Try `cygwin` which is the terminal emulator designed for Windows console.

**Comment by yoshiwaan** [comment]
FYI

https://sourceforge.net/p/msys2/tickets/241/

**Comment by modulok** [comment]
Just for any google searches that land here with the same problem with ConsoleZ running tcsh:

I had this same issue with the `clear` command not working properly. I had consoleZ set to run a cygwin tcsh shell on startup. In my tcsh config file `C:\cygwin64\home\modulok\.cshrc` I had the TERM environment variable set as `setenv TERM xterm-color`. Changing this to `setenv TERM cygwin` fixed the problem for me. `clear` now works correctly.
