### ISSUE TITLE
High DPI support in the "Settings" dialogue box

### ISSUE THREAD

**Issue by yever** [cbucher/console#284]
I'm using ConsoleZ as an alternative for Cygwin's tty and I really enjoy using it. The issue is pretty minor, but I thought it might make sense to report it anyway: 

In the "Settings" dialogue box under "Tab", the tabs ("Main", "Background", "Colors & Cursor", "Environment") are clipped on a High DPI display (3840x2160). 
Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/10565807/10728482/86aae06c-7be2-11e5-9ba8-28ea40022eec.png)

The "About" window is also very small and hardly legible (a screenshot wouldn't help here; the pixels are just very small).

I'm using version 1.15.0.15253.

**Comment by yever** [comment]
@cbucher Thank you!
I've compiled it an tested it and it works fine. I'm closing the issue.

**Comment by cbucher** [comment]
@yever Please, try the last experimental version.

**Comment by yever** [comment]
@cubcher - what experimental version do you mean? I've already compiled it and tried it with your new commits and said it works. Is there a new release?

**Comment by cbucher** [comment]
Built versions can be downloaded from wiki/Download section (https://github.com/cbucher/console/wiki/Downloads).

>I've already compiled it and tried it with your new commits and said it works.
Fix is validated. I close the issue.

Thank you

**Comment by yever** [comment]
Well, strangely neither the experimental nor any other version works from them zip/7z files in wiki/Download. The ``exe`` file simply doesn't run.

**Comment by cbucher** [comment]
?!? Hum... No...

**Comment by yever** [comment]
@cbucher - It's been a while, but apparently the culprit was using cygwin's ``7z``. I used the native Windows one and everything works fine, including the experimental version.

**Comment by cbucher** [comment]
Thx
