### ISSUE TITLE
Q: How do I exit full screen?

### ISSUE THREAD

**Issue by adamralph** [cbucher/console#285]

**Comment by cbucher** [comment]
You can:
- use "Full Screen" hotkey
- use "Context menu #3"
- press alt key and use the menu
- use the notification area icon
![image](https://cloud.githubusercontent.com/assets/363759/10851338/e80400e6-7f2a-11e5-9494-6b2b7fd1bd77.png)

**Comment by adamralph** [comment]
@cbucher thanks very much.

> * use "Full Screen" hotkey

I knew about the assignable hot keys but since there isn't one assigned by default I assumed there must be some other obvious way which I was missing.

> * use "Context menu #3"

I forgot all about the context menu :stuck_out_tongue:.

> * press alt key and use the menu

The alt key does nothing in windowed mode, so this is a little surprising.

> * use the notification area icon

I can't do this, since I can't *see* the notification area when in full screen.

Given that a minimal toolbar remains visible in full screen, I would expect there to be a button on that toolbar which switches back to windowed mode (although I would also like an option to hide that toolbar). Given that there is no hotkey assigned by default, and that the notification area is invisible, the only way to switch under default settings is to right click or press alt, and neither of these are very intuitive.

For me, the problem is solved by assigning F11, but I think other people may get stuck in the same way I did.

**Comment by cbucher** [comment]
>> - use "Full Screen" hotkey

>I knew about the assignable hot keys but since there isn't one assigned by default I assumed there must be some other obvious way which I was missing.

By default, F11 is assigned to "Full Screen" command.
Either your configuration file was older than "full screen" feature, or you deleted this hotkey.

>> - press alt key and use the menu

>The alt key does nothing in windowed mode, so this is a little surprising.

The alt key show the menu when the menu is hidden (even in windowed mode).

**Comment by adamralph** [comment]
> By default, F11 is assigned to "Full Screen" command.
> Either your configuration file was older than "full screen" feature, or you deleted this hotkey.

Yes, this must be because of the old config file which I propagated to my newer installation. It seems like the config file contains *all* the hotkey actions, including those which are unmapped. I guess it would be better if it only contained those which had been customised. I assume the current approach is a method of persisting any hotkeys which had been turned off, but this could also be done with an explicit property indicating the switching off of a hotkey rather than just saying 'unmapped'. This would prevent a newer hotkey mapping such as full screen toggle=F11 being masked by a previously unmapped full screen toggle.

**Comment by cbucher** [comment]
>It seems like the config file contains all the hotkey actions, including those which are unmapped. I guess it would be better if it only contained those which had been customised.

Yes, initial developers should have made this choice.
But change this now, would only affect future hotkeys. For "Full screen", this is too late.

The current behavior is also a prudent choice.
Provide a list of pre-configured hotkeys, when there is no configuration file, is easy. But force a new hotkey, when the user has already a configured environment can be annoying. Suppose this hotkey is already used in ConsoleZ or in an unknown shell or command line tool.
