### ISSUE TITLE
Using hotkey 'Activate ConsoleZ (global)' does not trigger 'Active window' transparency.

### ISSUE THREAD

**Issue by dss539** [cbucher/console#286]
**issue:** Using hotkey 'Activate ConsoleZ (global)' does not trigger 'Active window' transparency.

**settings**
Activate ConsoleZ (global) set to ctrl+shift+~
Transparency set to *Alpha* 
Active: 20 Inactive: 80

**repro**
select a window other than ConsoleZ (e.g. windows explorer)
trigger activation hotkey

**result**
ConsoleZ is correctly activated, but it still uses the *Inactive window* transparency value.

**expected**
ConsoleZ should switch to the *Active window* transparency value, just like occurs when activated via mouseclick/alt+tab/win+tab.

**diagnostic**
I don't currently have easy access to post files, so here is the header of the diagnostic report.
I can provide the full report upon request.
```
ConsoleZ aero amd64 1, 15, 0, 15253
is elevated? no
UAC prefix "Administrator: "
Tab (active): ConsoleZ
  View (active): 1. ConsoleZ
  is elevated? no
  Windows console font
font index: 6
face name: 
font familly: 48 MODERN
font weight: 400
font size: width=8 height=12
max window size: cols=120 rows=82
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 3
  Flags 1  primary
  DeviceID \\?\DISPLAY#DELF042#5&250e1d4e&0&UID1078020#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (0,0)x(1680,1050)
  Work (0,0)x(1680,1010)
  Flags 0
  DeviceID \\?\DISPLAY#DELF042#5&250e1d4e&0&UID1078019#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
  DeviceName \\.\DISPLAY2\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (1680,0)x(3360,1050)
  Work (1680,0)x(3360,1050)
  Flags 0
  DeviceID \\?\DISPLAY#DELF041#5&250e1d4e&0&UID1048832#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0014
  DeviceName \\.\DISPLAY3\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (3360,0)x(5040,1050)
  Work (3360,0)x(5040,1050)
```

**Comment by cbucher** [comment]
@dss539 Please, try the last experimental version.

**Comment by dss539** [comment]
@cbucher Thanks, will try it ASAP. Corporate firewall blocks goldenfrog, so I have to take some extra steps to obtain the experimental version.

**Comment by dss539** [comment]
OK, I'm taking way too long to verify this. I'll make a reminder to verify it at home tonight. Sorry for the delay.

**Comment by dss539** [comment]
I just tried 1.16.0.15318 because that was the latest listed here: https://github.com/cbucher/console/wiki/Downloads

I suspect that did not include your fix because the problem still occurred.

I cloned and built the latest with your fix, and I can confirm that it works perfectly now.
Thanks!
