### ISSUE TITLE
High DPI support

### ISSUE THREAD

**Issue by drewnoakes** [cbucher/console#287]
Currently the toolbar and tab headers look strange and are too tiny to easily interact with:

![image](https://cloud.githubusercontent.com/assets/350947/11103167/b9bb43ec-88b8-11e5-98cf-f6b2da1ace16.png)

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by drewnoakes** [comment]
[console-diagnostic.txt](https://github.com/cbucher/console/files/32789/console-diagnostic.txt)

**Comment by cbucher** [comment]
@drewnoakes Please, try the last experimental version and post a new diagnostic report.

**Comment by drewnoakes** [comment]
Is there an installer for the experimental build you mention?

**Comment by cbucher** [comment]
Ni, go to download section and un7zip...

**Comment by cbucher** [comment]
@drewnoakes Please, try the last experimental version and post a new diagnostic report.

**Comment by drewnoakes** [comment]
Downloading the archive from [this downloads page](https://github.com/cbucher/console/wiki/Downloads) gives this in Chrome:

![image](https://cloud.githubusercontent.com/assets/350947/12380984/6c459c1a-bdd4-11e5-87cc-60e68ff9dcdc.png)

**Comment by cbucher** [comment]
http://www.ghacks.net/2014/07/15/fix-chromes-safe-browsing-feature-blocking-downloads-browser/

https://www.virustotal.com/fr/url/45dd3ff0c7a431100e31540d2ab8d013a4d95b6070d5cefc0c5e5f78e7078396/analysis/1453102494/

Thanks Google for insulting clean software providers!

**Comment by cbucher** [comment]
@drewnoakes please try beta version

**Comment by drewnoakes** [comment]
The beta version (ConsoleZ.x64.1.16.0.16029) downloaded without any warnings.

The UI now looks like this:

![image](https://cloud.githubusercontent.com/assets/350947/12787603/fdfd7c34-ca8d-11e5-8241-4913f35dacb4.png)

Thanks for the updates!

Unfortunately I hit the issue described in #301 so couldn't do any further testing of other UI elements. The settings window looked good.

**Comment by cbucher** [comment]
You can test with cmd or powershell or ...

**Comment by drewnoakes** [comment]
But when I start ConsoleZ it crashes because of how I configured it. Perhaps the dialog that appears should offer resetting settings to defaults. Or the main window should appear without any children/tabs.

**Comment by cbucher** [comment]
There is a tip in [FAQ](https://github.com/cbucher/console/wiki/FAQ):

> When you configure a shell, verify it starts before exiting the application. Never modify the first (default) tab settings. Test and if verification is OK, move your tab settings in first place.
