### ISSUE TITLE
Screen Drawing over RDP

### ISSUE THREAD

**Issue by JCapriotti** [cbucher/console#290]
I'm running a cmd window through ConsoleZ, accessing my computer over RDP (Pulse Secure Terminal Services Client, which just uses Windows RDP I think). The window is fairly big... about 1250 x 1440. 

I ran into an issue with how the screen redraws. For example, if I call curl on a binary file like this...

    curl https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/fonts/fontawesome-webfont.woff -v

This shows a mess of characters in the window, and absolutely kills my bandwidth (its maxing out at 12 Mbps). I'm using Windows 10 Task Manager to show network use for running processes.

After it is done running, the whole window contains random characters like ````!▒L@▒▒▒▒Q▒X▒S▒↑▒▒◄▒▒▒```` and typing in the window has horrible lag. The screen isn't scrolling, but typing one character seems to trigger an entire redraw based on the bandwidth use I'm seeing. 

Is there any workaround for this? 

Diagnostic Log:
[dmp6EDA.txt](https://github.com/cbucher/console/files/48546/dmp6EDA.txt)

Thanks...
Jason

**Comment by cbucher** [comment]
ConsoleZ displays the Windows console buffer. Do you have a distinct behavior in ConsoleZ and Windows console (View/Windows Console)?

**Comment by cbucher** [comment]
@JCapriotti ConsoleZ displays the Windows console buffer. Do you have a distinct behavior in ConsoleZ and Windows console (View/Windows Console)?

**Comment by JCapriotti** [comment]
Yes, there was a difference between the bandwidth used when running ConsoleZ vs Windows console. Not sure if there's any additional debug information available but I can provide whatever additional details you need.

However, I recently started using straight Windows RDP rather than whatever the Pulse Secure wrapper uses. That seemed to improve things quite a bit. So it could have more to do with Pulse Secure than ConsoleZ. That was a little surprising since I thought Pulse Secure was just RDP. 

Anyway... long story short isn't really a problem for me right now.

**Comment by cbucher** [comment]
>Do you have a distinct behavior in ConsoleZ and Windows console (View/Windows Console)?

concerning random characters?
(show the hidden Windows console by using the menu View/Windows Console)

>Yes, there was a difference between the bandwidth used when running ConsoleZ vs Windows console.

The only way to affect the bandwidth is a CPU limitation, otherwise there is no interaction...

**Comment by JCapriotti** [comment]
I'm not sure if it is the random characters; I assume it is any character. Calling curl on a binary file was the easiest example of getting the console draw and scroll a lot of data.

I took some notes, just eyeballing performance:

**Pulse Secure**
* *Cmd.exe* - fast refresh, 4 Mbps, 20% remote CPU, 25% local CPU
* *ConsoleZ* - extremely slow refresh, 12.5 Mbps, unknown remote CPU (screen won't redraw), 5% local CPU
* *ConsoleZ command window* - fast refresh, 4 Mbps, 20% remote CPU, 25% local CPU

**Windows RDP**
* *Cmd.exe* - fast refresh, 3 Mbps, 20% remote CPU, 25% local CPU
* *ConsoleZ* - **fastest refresh**, 10 Mbps, 15% remote CPU, 10% local CPU
* *ConsoleZ command window* - fast (same as cmd.exe) but visually slower than ConsoleZ, 4 Mbps, 20% remote CPU, 25% local CPU

**Comment by cbucher** [comment]
When the console window is hidden, the drawing is more faster (there is no need to draw in the console window). I assume the drawing is synchronous and that's explain why a console application is faster when the console window is hidden.

You can modify the refresh by modifying timeouts:
![image](https://cloud.githubusercontent.com/assets/363759/12109637/2057d7d2-b384-11e5-8751-7fcf73d6b0bf.png)

I tried to obtain this kind of information (problems or feedback concerning the rendering performance) here #183. I got zero feedback in 7 months!
