### ISSUE TITLE
Font colors aren't shown when using "glass" transparency

### ISSUE THREAD

**Issue by SuperPommeDeTerre** [cbucher/console#291]
When using "glass" transparency in the settings, the terminal font colors aren't shown (backaground colors are).
When using others transparency settings, all works fine...
For information, I'm using ANSIcon v1.66. (in 64 bits mode)

**Comment by cbucher** [comment]
Diagnostic report is missing.
The transparency doesn't affect the text rendering in code.
If background colors are visible, then text colors are visible too.

I can only see a way : you checked "Custom color" in Settings/Appearance/Font. But in this case you have a single text color whatever the mode of transparency...

**Comment by SuperPommeDeTerre** [comment]
I just verified my settings, and I don't have set a custom font color.
What is the dignostic report you require ?

**Comment by cbucher** [comment]
The Windows blur effect is responsible.

You should reduce the background opacity:
![image](https://cloud.githubusercontent.com/assets/363759/11978205/f541f054-a989-11e5-97dd-0bff42765979.png)
And select a very dark Windows glass color.

**Comment by SuperPommeDeTerre** [comment]
Thanks !
