### ISSUE TITLE
Arrange tabs using keyboard

### ISSUE THREAD

**Issue by VarunAgw** [cbucher/console#292]
Vimium for Chrome have a feature to arrange tabs using (Ctrl+>, Ctrl+<). It will be awesome if I can create a hotkey to do the same in ConsoleZ

**Comment by cbucher** [comment]
@VarunAgw Please, try last experimental version.

**Comment by VarunAgw** [comment]
Thanks! That was fast. I'll try it today

**Comment by cbucher** [comment]
@VarunAgw Did you try it?

**Comment by VarunAgw** [comment]
@cbucher Yes! I tried it. It is working perfectly. Thanks :)

**Comment by cbucher** [comment]
Thx
