### ISSUE TITLE
cygwin bash with console

### ISSUE THREAD

**Issue by jiqimaogou** [cbucher/console#293]
can not open cygwin bash.exe in consolez

**Comment by cbucher** [comment]
consult a psychic or explain yourself
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by myertveho** [comment]
I use consolez with cygwin bash all the time. C:\cygwin64\bin\bash.exe -exec "/usr/bin/ssh user@host"

**Comment by jiqimaogou** [comment]
I run in win10, and has the error "DLL injection has failed(reason: unknown exception)!"

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
fixed a bug in last experimental version
the reason *should* be more explicit than "unknown exception"

**Comment by cbucher** [comment]
@myertveho last call before closure...
