### ISSUE TITLE
Needing a CONSOLEZ environment variable

### ISSUE THREAD

**Issue by d-faure** [cbucher/console#298]
I'm running ConsoleZ + [busybow-w32](http://frippery.org/busybox/index.html) in a **portable** environment and I need to let the shell handle itself a `.profile` file accordingly, providing my own definition of the `HOME` environment variable which will depend on the current location of ConsoleZ itself.

For now, I'm using a wrapping `.bat` script, which sets a `CONSOLEZ` environment variable derived from `%~dp0` before launching ConsoleZ itself, then use a `%CONSOLEZ%...` based expression to define a `HOME` variable in a busybox dedicated tab parameters.

It would be nice if ConsoleZ could provide this variable itself.

**Comment by cbucher** [comment]
@d-faure Please try the pre-release 1.16.0.
