### ISSUE TITLE
cmd.exe crash with ConsoleZ running vim.exe

### ISSUE THREAD

**Issue by wilstark** [cbucher/console#299]
When attempting to open the attached file with the command line ("vim foo.xml"), a dialog with the following text appears, and cmd.exe does down.  Vim.exe is still running.

The crash dialog:
<pre>
---------------------------
cmd.exe - Application Error
---------------------------
The instruction at 0x7725953d referenced memory at 0x0000fff8. The memory could not be read.

Click on OK to terminate the program
Click on CANCEL to debug the program
---------------------------
OK   Cancel   
---------------------------
</pre>
The ConsoleZ configuration is the out-of-the-box configuration; nothing special.  The crash does not happen every time.  It only seems to be about 1 out of 5 times for me.  I have not noticed this failure running vim.exe directly from a standard cmd.exe shell (i.e. no ConsoleZ).

OS: Windows 7: Microsoft Windows [Version 6.1.7601]
VIM version 7.4
ConsoleZ version 1.15.0.15253
CPU: HP Z440 / 32GB RAM.

Note: uploaded foo.xml.txt must be renamed to foo.xml.
[foo.xml.txt](https://github.com/cbucher/console/files/112924/foo.xml.txt)

*** Update ***
Here's a diagnostic from another machine showing the issue:

```
ConsoleZ aero amd64 1, 15, 0, 15253
is elevated? no
UAC prefix "Administrator: "
Tab (active): ConsoleZ
  View (active): 1. ConsoleZ - foo.xml (~\Downloads) - VIM
  is elevated? no
  Windows console font

  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 1
  Flags 1  primary
  DeviceID \\?\DISPLAY#SDC5344#4&125c64ed&0&UID68092928#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (0,0)x(1920,1080)
  Work (0,30)x(1920,1080)
Settings file internal resource
```

Crash dump of cmd.exe is here: https://drive.google.com/file/d/0B95SlwArnpPLR0V6dWdwUG1MNTQ/view?usp=sharing

My expectation is that I can open vim from a cmd.exe instance wrapped by consolez and not have cmd.exe crash.

I cannot reproduce on latest (1.16.0.16029) (as bug filing document requests) as just trying to open ConsoleZ (to blank window) and then pressing enter in the window causes continuous repeated prompts to be generated (in both ConsoleZ window and the hidden console window).  Only way out is to kill the cmd.exe or console.exe process.  So the problem might be there, but I can't get to the point I can try it.

**Comment by wilstark** [comment]
In addition, this has been replicated by another developer in my group.  It appears that the XML file may be a required component - perhaps something about the syntax highlighting that VIM is doing is related to the problem.  Also, VIM is in its out-of-the-box configuration.

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by wilstark** [comment]
Diagnostic from another machine that shows the crash of cmd.exe.

```ConsoleZ aero amd64 1, 15, 0, 15253
is elevated? no
UAC prefix "Administrator: "
Tab (active): ConsoleZ
  View (active): 1. ConsoleZ - foo.xml (~\Downloads) - VIM
  is elevated? no
  Windows console font

  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 1
  Flags 1  primary
  DeviceID \\?\DISPLAY#SDC5344#4&125c64ed&0&UID68092928#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0001
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (0,0)x(1920,1080)
  Work (0,30)x(1920,1080)
Settings file internal resource
```

**Comment by cbucher** [comment]
3. Verify if the latest version (experimental, beta or release) doesn't fix your problem
--> download beta version 1.16.xxx

5. Search for existing issues using the search field at the top of the page
--> #279
