### ISSUE TITLE
command line switch -r doesn't work

### ISSUE THREAD

**Issue by lennoncork** [cbucher/console#304]
I haven't been able to get the -r switch to work. I've tried updating to latest release and still no change. The console executable is in my path. 

Running "console -r dir" opens a new console in the current directory, I was expecting it to run the "dir" command and display the output in the new window/tab. 

Running "console -d c:\", works as expected, starting the console in "c:\".

**Comment by cbucher** [comment]
Your command line is wrong.
As expected ConsoleZ launches  `cmd.exe dir`. You can type `help cmd' to display cmd.exe command line.

You should read carefully the manual:

**Note:** Some shells need an additional switch in the startup command string. E.g. when using cmd.exe, you must put /k at the beginning of your command string: 

![image](https://cloud.githubusercontent.com/assets/363759/12947825/6ed71530-cffe-11e5-93d8-a22a3a7fa128.png)
