### ISSUE TITLE
Allow launching of tabs from jumplist without -reuse flag

### ISSUE THREAD

**Issue by ipankajg** [cbucher/console#309]
In the jumplist commands, -reuse is used causing multiple tabs to open in same window. It would be nice to allow launching separate window instead of creating tabs (based upon user preference).

**Comment by cbucher** [comment]
You're right.
The "multi-instance" setting in configuration file has been added after. And the "-reuse" option should have been removed.

**Comment by cbucher** [comment]
@ipankajg  Please, try last experimental version.

**Comment by barclay-reg** [comment]
documentation still shows the -reuse flag, should this be removed now?

**Comment by cbucher** [comment]
The flag is no longer used in jump list command lines but it still exists.
