### ISSUE TITLE
Console Z Desktop Wallpaper related issue/suggestion

### ISSUE THREAD

**Issue by rhymdsadeelf** [cbucher/console#311]
I've some suggestion and there are some issues I faced, so I'm just posting them under a same issue

A) ConsoleZ hangs momentarily on wallpaper change during slideshow. If I keep my desktop wallpaper as a slideshow with a duration of 10 seconds, it keeps hanging momentarily after every 10 seconds. Try keep pressing a key for 12 seconds, and it will stop momentarily every 10 seconds.

B) Option to specify global background setting for each type of tab (cygwin, cmd, PS,..) so I don't have to specify individually for each type.

C) I'm not sure if it is intended behavior (automatically coloring of this bar as in attachment by "Windows 10 colored Title Bar feature"), but it doesn't looks very good (at least to me). Earlier it was always white. So if possible, always make it the same color as menu bar

D) Show .png files too in Browse dialog for background picture. 

![console tabs](https://cloud.githubusercontent.com/assets/17356735/13197504/99005190-d815-11e5-9359-0d59d8e5fdaa.png)

**Comment by cbucher** [comment]
>so I'm just posting them under a same issue

see [wiki](https://github.com/cbucher/console/wiki/How-to-Report-an-Issue)

**Comment by cbucher** [comment]
A) Yes I know.
FreeImage is pretty bad for re-dimensioning and this can hang...
You can try with wallpapers adapted to your monitor size and report if there is an improvement.

**Comment by cbucher** [comment]
B) create a feature request for this

**Comment by cbucher** [comment]
C) This is the non-client area (I let you google).
This is the color you choose or the system determine from your wallpapers.
This is the color of your Windows taskbar and start menu...
Microsoft call this the accent color.

**Comment by rhymdsadeelf** [comment]
I will check A and will update the issue later. 

Regarding C, I didn't knew that. I thought it might be possible to make it fixed color.

**Comment by rhymdsadeelf** [comment]
So, I've suggested some other features too now, which I feel will be good to have. But I agree they will be a lot of work. None of them are important feature and you don't have to work on any of them if you don't feel like. Think of them just as some less important suggestions which I feel will make ConsoleZ more awesome.

**Comment by cbucher** [comment]
A) I upgraded FreeImage version, but I don't think that will be speed up the rendering.
GDI+ supports files of type BMP, ICON, GIF, JPEG, Exif, PNG, TIFF, WMF, and EMF.
FreeImage should be replaced by GDI+ ... if somebody has time he can contribute :wink:

**Comment by cbucher** [comment]
@rhymdsadeelf You can close the issue if you think I answer to questions.

**Comment by rhymdsadeelf** [comment]
Thanks a lot for working on them @cbucher.
