### ISSUE TITLE
Per tab setting to convert line endings on paste

### ISSUE THREAD

**Issue by rhymdsadeelf** [cbucher/console#314]
I use 4 tabs (CygWin, SSH, CMD, PowerShell). It will be great whenever I paste something into first two, they will get converted to Unix Line ending. Also they should get automatically converted to Windows line endings on CMD and PowerShell.

I think there can be a radio button for each tab

Line endings on Paste
- Paste as it is
- Convert it to Unix
- Convert it to Windows

**Comment by cbucher** [comment]
Line endings are not sent to consoles!
Text is transformed into key inputs. The line ending becomes a return key.
