### ISSUE TITLE
Underline links on mouse hover

### ISSUE THREAD

**Issue by rhymdsadeelf** [cbucher/console#317]
Let suppose, I set Ctrl + LClick as "Click Link" in Settings -> Hotkeys -> Mouse

So whenever I hover a link with mouse pressing Ctrl key, it should underline the link to suggest it is clickable.

**Comment by cbucher** [comment]
see  #123 and #300

**Comment by rhymdsadeelf** [comment]
Oh! One more issue I face is, when I Ctrl+Click in an empty space, it opens it startup directory. Is this the intended behavior? Can this be disabled?

Whenever I try to Press Ctrl+Fn keys to create new tab, my hand sometime accidentally touches the touch pad causing Ctrl+Click event and a new unwanted window.

**Comment by cbucher** [comment]
In this case, ShellExecute is called with an empty string and verb "open".
Do you want tnot calling ShellExecute in this case?

**Comment by rhymdsadeelf** [comment]
Yes if possible.

**Comment by cbucher** [comment]
@rhymdsadeelf Please try last beta version.
