### ISSUE TITLE
Some wallpapers are crashing ConsoleZ

### ISSUE THREAD

**Issue by rhymdsadeelf** [cbucher/console#319]
http://s000.tinyupload.com/index.php?file_id=76294734113653616518

Set this folder as slideshow in Windows. 

ConsoleZ always crash when wallpaper changes to `Pyramid of Kukulkбn, Chichen Itza, Yucatan Peninsula, Mexico.jpg`

On renaming `б` to normal English character, it works fine. So it has some issue with these characters

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by rhymdsadeelf** [comment]
I don't want to share these reports since they contain personal information. I'm not sure, but I think it should be easily reproducible?

**Comment by cbucher** [comment]
>I don't want to share these reports since they contain personal information.

Reports are human readable. Other people simply mask personal information!

**Comment by cbucher** [comment]
@rhymdsadeelf Please try last beta version.

**Comment by rhymdsadeelf** [comment]
I was talking about the Crash dump too. I'm not sure if it is human readable too.
