### ISSUE TITLE
Error: DLL Injection failed

### ISSUE THREAD

**Issue by denkyuu** [cbucher/console#321]
Whenever I try to launch ConsoleZ, it starts infinitely throwing the above error, building up a stack of hundreds of notification windows. I have to restart to stop them from popping up, and deleting consoleZ and redownloading doesn't fix the issue.

**Comment by cbucher** [comment]
Have you configured console.exe as the shell in COMSPEC variable or in tab's settings?

**Comment by denkyuu** [comment]
I actually found the config file and deleted it. That fixed the issue, whatever went wrong. Now I just need to get git bash working.

Thanks!
