### ISSUE TITLE
Console Z only showing wallpaper in a corner

### ISSUE THREAD

**Issue by rhymdsadeelf** [cbucher/console#324]
This bug is introduced in v1.16.1.16060 and was not before. 

To reproduce it:
1) Set a single wallpaper as background (no slideshow)
2) It will be visible only in a corner (not full window as in screenshot)

I've noticed, if I set Slideshow as wallpaper, this bug will stop occurring after the first wallpaper is changed.

![2016-02-29_162429](https://cloud.githubusercontent.com/assets/17356735/13392540/45d50928-df01-11e5-811f-fd71b6983158.png)

**Comment by cbucher** [comment]
@rhymdsadeelf P Lease, try last beta version.
