### ISSUE TITLE
autorun script on open

### ISSUE THREAD

**Issue by avisser** [cbucher/console#327]
Question, not an issue.

If I were to implement an autorun feature (think bash `.profile` or `autoexec.bat`) would you be open to taking that back as a pull request? I know I _could_ write a batch file that sets things up, then runs cmd.exe ala VisualStudio command prompt. But the *nix way seems cleaner. I just want a file that sets a bunch of environment variables and maybe runs something else.

Again, I _could_ do this in console, but I like the idea of having this file be shared amongst a few configurations.

Great work extending Console2. I just found you today and look forward to seeing the new features.

-Andy

**Comment by cbucher** [comment]
Hi,

Executing a script requires a command line interpreter. This is a shell's task and **ConsoleZ is not a shell**.
You can already define specific environment variables per tab. Common environment variables should be defined in Windows system settings (`Advanced system settings`).

Regards

**Comment by avisser** [comment]
Fair enough. I'm just wistful for bash and typing `vim ~/.profile` and making a sticky change. It's _so_ much nicer than right click "my computer" -> properties ... -> ... -> ... 

And the thought of burying all of these settings into ConsoleZ isn't appealing either, when I inevitably change systems.

But understood. I'll try and copy the Visual Studio model and see how that works.

**Comment by cbucher** [comment]
>It's so much nicer than right click "my computer" -> properties ... -> ... -> ...

Win + Pause
click 'Advanced system settings'
click 'Environment Variables...'

**Comment by avisser** [comment]
Learn a new keyboard shortcut every day. 

I ended up copying the VS2013 profile and having it call ~/profile.bat.

Great work and thanks for moving Console2 forward.

**Comment by cbucher** [comment]
Thx
