### ISSUE TITLE
console windows font property can't save.

### ISSUE THREAD

**Issue by rosolino** [cbucher/console#330]
Hello.
I can't save console window property in version 1.16.1.16068.
the  version 1.16.0.16038  has not this probrem.
Though I set console window property,every time I excute Consolez, the setting is clear to default.( "Lucidia Console" size 5.)
 I use japane font with powershell,so I want to set to console window font to MS Gothic.
Overlap Japanese font at present in Powershell, I can't read.

[dmpC9F2.tmp.txt](https://github.com/cbucher/console/files/191316/dmpC9F2.tmp.txt)
![powershell](https://cloud.githubusercontent.com/assets/6219165/14069661/cda72b56-f4d7-11e5-80d5-047d7bb8023f.png)

**Comment by cbucher** [comment]
@rosolino Please, try last experimental version.
You can also contribute to japanese localization here #303

**Comment by rosolino** [comment]
Thanks.
I try experimental version. It is good. 
Japanese font display correctly.
![powershellgood](https://cloud.githubusercontent.com/assets/6219165/14101491/d5731234-f5cf-11e5-8cb0-4178e13bdd72.png)

**Comment by cbucher** [comment]
Thx for feeback
