### ISSUE TITLE
VCOMP120.DLL is missing System Error

### ISSUE THREAD

**Issue by chernosliv** [cbucher/console#331]
ConsoleZ.x64.1.16.1.16068.zip when unzipped and run as Console.exe produces System Error complaining about missing VCOMP120.DLL.
Env: Win 7 x64 SP1
https://github.com/cbucher/console/releases/download/1.16.1/ConsoleZ.x64.1.16.1.16068.zip

This version runs ok - https://github.com/cbucher/console/releases/download/1.14.0/ConsoleZ.x64.1.14.0.15129.zip
![systemerror](https://cloud.githubusercontent.com/assets/1199579/14112423/e8efeec8-f5ce-11e5-9dc3-63f9e3eb35ba.PNG)

**Comment by miked63017** [comment]
I have this problem too

**Comment by fzipi** [comment]
Same problem here.

**Comment by slier81** [comment]
this is because of missing c++ redistributed package.
go here to download missing package: https://www.microsoft.com/en-us/download/details.aspx?id=40784

**Comment by miked63017** [comment]
Mine is installed, i even reinstalled it to make sure.

**Comment by cbucher** [comment]
@miked63017 You haven't installed the good one, otherwise you would not have this error.

**Comment by cbucher** [comment]
Try the last experimental verson. I rebuild the external library FreeImage.

**Comment by chernosliv** [comment]
Looks like resolved in http://code.fosshub.com/ConsoleZ/download/ConsoleZ.1.17.0.16092.7z in ...\x64\Release

Thanks!

**Comment by cbucher** [comment]
Thx
