### ISSUE TITLE
German GUI Typo "Editieren -> Anzeige auswächseln" should be "Editieren -> Anzeige auswechseln"

### ISSUE THREAD

**Issue by emi-le** [cbucher/console#333]
There is a typo in the german GUI:

Editieren -> Anzeige auswächseln

needs to be changed to 

Editieren -> Anzeige auswechseln

![image](https://cloud.githubusercontent.com/assets/18303829/14311110/f8906732-fbe5-11e5-8777-7ab3ee7d191b.png)

see http://dict.leo.org/ende/index_de.html#/search=auswechseln&searchLoc=0&resultOrder=basic&multiwordShowSingle=on

I have installed version 1.16.1.16068
-----------------------------------------------------------------------------------------------------------------------------

### Expected Behavior
In GUI
Editieren -> Anzeige auswechseln

### Actual Behavior
Editieren -> Anzeige auswächseln

### Steps to reproduce
1. What steps consistently cause this behavior?
2. What does someone need to do to recreate the issue?

### Diagnostic Report
```
From within ConsoleZ select Help > Diagnose.
This will open a file in Notepad with useful information.
Please paste that information here or include that file.
```

### Crash Report
When reporting a crash you **must** provide a crash dump.
Instructions on how to generate one can be found here:
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
@cruzzer for you

**Comment by cbucher** [comment]
@emi-le You can easily correct the translation:

fork the project:
![image](https://cloud.githubusercontent.com/assets/363759/14598198/58a1db8c-0551-11e6-8531-805d1dc34586.png)

go to l10n folder:
![image](https://cloud.githubusercontent.com/assets/18527052/14598531/dfbe0b12-0552-11e6-97ab-e63b2ebd943f.png)

go to language folder:
![image](https://cloud.githubusercontent.com/assets/18527052/14598504/ba5acd24-0552-11e6-9308-2ecdb01ddc8b.png)

Edit the ini file:
![image](https://cloud.githubusercontent.com/assets/363759/14598579/400117d0-0553-11e6-8f44-b58b47d6b6a5.png)
![image](https://cloud.githubusercontent.com/assets/363759/14598632/833fa48a-0553-11e6-83ad-83762dd40053.png)

Modify and start a pull request:
![image](https://cloud.githubusercontent.com/assets/363759/14598933/f5981e80-0554-11e6-867f-b065805d3601.png)

Create pull request:
![image](https://cloud.githubusercontent.com/assets/363759/14598989/38a4e532-0555-11e6-9b2c-f1625d65f9bc.png)

**Comment by cruzzer** [comment]
I'll get on to it. I've been semi-offline for my exams.
