### ISSUE TITLE
VCOMP120.DLL missing

### ISSUE THREAD

**Issue by alexchandel** [cbucher/console#338]
In ConsoleZ 1.16.1.16068, attempting to start chocolatey on a vanilla Windows 2012R2 machine results in a "VCOMP120.DLL missing" error, presumably from some dependency on OpenMP.

The culprit appears to be FreeImage.dll which links against VCOMP120.DLL. MS redistributable dlls are cancer, so somewhere along the line that should get statically linked.

**Comment by JackMorrissey** [comment]
Just ran into this as well.

ConsoleZ 1.16.1.16068
Chocolatey v0.9.9.12
Windows 10

**Comment by cbucher** [comment]
Duplicate issues are cancer too...
#331

**Comment by alexchandel** [comment]
@cbucher Implying I didn't? I searched for "VCOMP120.DLL" and related strings, 0 Open and 0 Closed issues, and didn't see anything. Should complain to GitHub about their search engine.

**Comment by cbucher** [comment]
>Should complain to GitHub about their search engine.

Are you sure?

**found in closed issues**
![image](https://cloud.githubusercontent.com/assets/363759/14579156/37f5a25a-039f-11e6-9d63-ec4fcd41d402.png)

**found in issues**
![image](https://cloud.githubusercontent.com/assets/363759/14579158/566ac8e6-039f-11e6-8a0c-ab97aee09658.png)

**found...**
![image](https://cloud.githubusercontent.com/assets/363759/14579164/6cec3bcc-039f-11e6-9490-42a5a3d4ada3.png)

![image](https://cloud.githubusercontent.com/assets/363759/14579226/53f84154-03a1-11e6-9d58-371c31324242.png)

**Comment by alexchandel** [comment]
@cbucher I kid you not. I'm impressed by how off I was. Yet I literally searched this repo (not all GitHub) for "VCOMP120.DLL", and got no issues.
