### ISSUE TITLE
[Feature Proposal] Add CLI arguments to console.exe for Explorer integration

### ISSUE THREAD

**Issue by tobiasmuehl** [cbucher/console#343]
This is not a bug report.

I'd like to see an integration for ConsoleZ in the context menu of Windows Explorer. To be able to add such shortcut, it must be possible to call console.exe and supply some arguments to it. In this case, it should be possible to set the startup directory, although a simple execute command would be fine too.

![alt text](http://www.tech-recipes.com/wp-content/uploads/open-command-window-here.png "screenshot")

**Comment by cbucher** [comment]
If you want to add a **single entry** into explorer context menu, you can simply configure the registry.

**Comment by tobiasmuehl** [comment]
I don't understand how it's possible to open ConsoleZ **in the current directory** from the context menu

**Comment by cbucher** [comment]
Google `"consoleZ" context menu` or `"console2" context menu`.
You will find a lot of examples:
https://coderwall.com/p/v8aora/adding-console2-consolez-to-folder-context-menus
https://github.com/michael-wolfenden/Configuration/blob/master/utils/consolez/add-to-context-menu.reg
...

**Comment by cbucher** [comment]
@tobiasmuehl Were you able to configure the file explorer? Can we close the topic?

**Comment by tobiasmuehl** [comment]
sorry for late reply, yes your suggestion worked. issue can be closed.

Christophe Bucher <notifications@github.com> schrieb am Mo., 9. Mai 2016,
16:51:
