### ISSUE TITLE
Feature request: "Toggle always on top" hotkey command

### ISSUE THREAD

**Issue by john-black-3k** [cbucher/console#347]
Hi,

Sometimes I need the console window to have the topmost style set and sometimes not so. I can see that it is possible to set the Z order in "Settings -> Appearance", but it would be nice to have a "Toggle always on top" command in "Settings -> Hotkeys" and assign a hotkey to it.

Thanks!

PS: Very good program by the way, I have been using it for a day or so and I like it already.

**Comment by cbucher** [comment]
@john-black-3k  Please, try the [last experimental version](http://code.fosshub.com/ConsoleZ/downloads).

**Comment by john-black-3k** [comment]
Thank you!
