### ISSUE TITLE
Improvement: Expand environment variables in snippets directory string

### ISSUE THREAD

**Issue by john-black-3k** [cbucher/console#348]
Hi,

I have tried setting the "dir" attribute of the "snippets" element inside "console.xml" settings file to a string that contains environment variables, like so:

`<snippets dir="%b2eprogrampathname%snippets\" />`

The "%b2eprogrampathname%" variable is defined for the "console.exe" process (I checked this using [ProcessHacker](http://processhacker.sourceforge.net/)). Additionally, when running the "set" command inside a "cmd" tab of ConsoleZ I can see that the "%ConsoleZSnippetsDir%" variable is resolved to the correct "snippets" folder. Inside this folder there is a "test.xml" file identical to the one from [Snippet.h#L4-39](https://github.com/cbucher/console/blob/master/Console/Snippet.h#L4).

The problem is that the "Edit -> Insert Snippet" menu is grayed out when using an environment variable to define the snippets directory inside the settings file "console.xml".

Looking at [SnippetCollection::load()](https://github.com/cbucher/console/blob/master/Console/Snippet.cpp#L128) inside "Snippet.cpp" shows why this happens. It would be nice if you could add something like the following at the start of the method, before the "try" block:

`wstring f = Helpers::ExpandEnvironmentStrings(folder);`

and replace "folder" with "f" (or whatever) inside this method (currently lines 135 and 153). Something similar is already done in several other places, including [Helpers::LoadTabIcon](https://github.com/cbucher/console/blob/master/Console/Helpers.cpp#L498) from "Helpers.cpp".

Thanks again!

PS: This application is even nicer than I have thought in the beginning.

**Comment by cbucher** [comment]
@john-black-3k  Please, try the [last experimental version](http://code.fosshub.com/ConsoleZ/downloads).

**Comment by john-black-3k** [comment]
Thank you!
