### ISSUE TITLE
font alignment issue 

### ISSUE THREAD

**Issue by lion117** [cbucher/console#352]
![q -20160711194816](https://cloud.githubusercontent.com/assets/3996029/16729665/73f9208e-47a0-11e6-8997-1b9bee8dc493.png)
OS; windows  7  64bit

![q -20160711194831](https://cloud.githubusercontent.com/assets/3996029/16729666/744521e6-47a0-11e6-8ae1-dfbdb797e395.png)
my windows origin cmd console

are there any way to solve this problem ?

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/FAQ#why-ui-becomes-strangeuglymisaligned

**Comment by lion117** [comment]
thanks

**Comment by lion117** [comment]
![q -20160712174752](https://cloud.githubusercontent.com/assets/3996029/16762810/b7b85d54-4858-11e6-95a4-b38c6d31c7cd.png)
hi, i had tried the guide on the help document , but it did not work .  
step1 : I did not find the **subkey named "ConsoleZ command window"**
step2:  "Language for non-Unicode programs" my computer had setted as Simplified chinese
step3: i had tried serval kinds of font , but it did not work 
![q -20160712180025](https://cloud.githubusercontent.com/assets/3996029/16763222/936b5486-485a-11e6-8803-e791db649f84.png)
![q -20160712180111](https://cloud.githubusercontent.com/assets/3996029/16763223/936b79b6-485a-11e6-8950-3b65504b245a.png)

Is there any way to solve this problem ? Thanks

**Comment by cbucher** [comment]
>Anyway, select proper **TrueType console font** and set its size to something small (8 or 10 points). Small size will allow you bigger max ConsoleZ window size. 

![image](https://cloud.githubusercontent.com/assets/363759/16773003/8995ea10-4856-11e6-8ee3-a387f34be6b7.png)
