### ISSUE TITLE
Block mode for highlight/copy/selection

### ISSUE THREAD

**Issue by gfody** [cbucher/console#357]
This is a feature request to support block mode highlighting when ALT key is pressed while clicking (like VS).
LDOWN
![current](https://cloud.githubusercontent.com/assets/1146032/17158426/1b50a522-534b-11e6-83a4-872baa60ef4c.gif)
ALT+LDOWN
![blockmode](https://cloud.githubusercontent.com/assets/1146032/17158432/286743f6-534b-11e6-9e2e-4fe11de71edc.gif)

**Comment by cbucher** [comment]
Configure ConsoleZ like this:
![capture](https://cloud.githubusercontent.com/assets/363759/17188604/20ca16b6-543e-11e6-8fe6-d63289711997.PNG)

**Comment by gfody** [comment]
brilliant! that works, shame I didn't try it first
