### ISSUE TITLE
PragmataPro is not a supported font, even though it is monospace.

### ISSUE THREAD

**Issue by stephenlam** [cbucher/console#360]
### Expected Behavior
PragmataPro is listed as an available font.

### Actual Behavior
Only PragmataPro Mono is listed, even though both PragmataPro and PragmataPro Mono are monospaced fonts.

### Steps to reproduce
1. What steps consistently cause this behavior?
Install PragmataPro font from http://www.fsd.it/shop/fonts/pragmatapro/.
Go to menu -> Edit -> Settings.
In Settings dialog, go to Appearance -> Font.
When clicking ... button next to Name, the PragmataPro font does not show up.

2. What does someone need to do to recreate the issue?
Same as 1).

### Diagnostic Report
```
From within ConsoleZ select Help > Diagnose.
This will open a file in Notepad with useful information.
Please paste that information here or include that file.
```
[dmp9360.tmp.txt](https://github.com/cbucher/console/files/413875/dmp9360.tmp.txt)

### Crash Report
When reporting a crash you **must** provide a crash dump.
Instructions on how to generate one can be found here:
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by cbucher** [comment]
A monospaced font, also called a fixed-pitch, fixed-width, or non-proportional font, is a font whose letters and characters each occupy the same amount of horizontal space.

!["PragmatoPro" font families](http://www.fsd.it/wp-content/uploads/2015/12/PragmataPro_PragmataProMono_EssentialPragmataPro.png)

"PragmatoPro" is not a fixed-pitch font and so it's not listed by [ChooseFont](https://msdn.microsoft.com/en-us/library/cc194833.aspx) function with the flag CF_FIXEDPITCHONLY.
