### ISSUE TITLE
WSL bash (Ubuntu On Windows) problems

### ISSUE THREAD

**Issue by ankostis** [cbucher/console#361]
Tried your excellent terminal (`v1.17.0.16129`) with recent Windows-10U "bash" (termed *"Windows Subsyste for Linux"* or WSL) and so far discovered that special keys (cursor, PgUp/PgDown) are not working; Esc & Tab work OK.

I confirm that these keys work ok with an older *Console2* .

**Comment by cbucher** [comment]
duplicate issue #335

**Comment by ankostis** [comment]
My apologies, totally missed it :-(
