### ISSUE TITLE
Automatic row/column computation incorrect

### ISSUE THREAD

**Issue by bartvanandel** [cbucher/console#362]
### Expected Behavior
When (half-)maximizing ConsoleZ (Windows 10: <kbd>Win</kbd>+<kbd>up</kbd> or <kbd>Win</kbd>+<kbd>left</kbd> or <kbd>Win</kbd>+<kbd>right</kbd>), the number of columns and rows should fit the screen. I'm using Lucida Console at 9pt.

### Actual Behavior
The row count is off, in this case leaving an empty area at the bottom. When using 11pt, the result is as expected.

### Steps to reproduce
1. Set font to Lucida Console, 9pt
2. Maximize window
3. Enter some command which should fill up the screen, like `dir %WINDIR%`.

### Diagnostic Report
[consolez-diag.txt](https://github.com/cbucher/console/files/424796/consolez-diag.txt)

**Comment by cbucher** [comment]
```
font index: 8
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=16
max window size: cols=239 rows=63
```

See `Why am I limited in number of row/column?` section in wiki/FAQ.

**Comment by bartvanandel** [comment]
Okay so this is some weird limitation forced upon us by Microsoft. Nice. But... isn't `void ConsoleHandler::SetConsoleFont()` supposed to fix/circumvent this by setting the console font to a smallish font?

**Comment by cbucher** [comment]
`ConsoleHandler::Set Console Font` is actually not called. This feature has been disabled. DBCS code pages require specific fonts... and I don't know how to guess what font should be use.
(see #330)

**Comment by bartvanandel** [comment]
Since not everyone requires DBCS, maybe this can be made into an option? Also, why would you need to guess the font? Can't you simply use the font which has been selected by the user? If the computation of rows/columns is based on font (which it is from what I gathered from MSDN) this probably makes sense.

If this works, the only remaining issue would be that the [`GetLargestConsoleWindowSize`][1] function apparently always uses the first monitor. I', clueless about whether someone found a solution for this (and I haven't been doing any Windows programming myself recently, so I haven't tried myself).

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683193(v=vs.85).aspx

**Comment by cbucher** [comment]
>Since not everyone requires DBCS, maybe this can be made into an option? 

Option implies that people read documentation or FAQ to activate it. I don't know which font is needed so I should not activate this option by default.

>Also, why would you need to guess the font? Can't you simply use the font which has been selected by the user? If the computation of rows/columns is based on font (which it is from what I gathered from MSDN) this probably makes sense.

What font?
- The font selected in ConsoleZ application? Only few fonts are selectable in Windows console. The default font used by ConsoleZ is not one of them.
- The font selected in Windows console? By default this is a raster font. So by default the font is wrong.

>If this works, the only remaining issue would be that the [`GetLargestConsoleWindowSize`][1] function apparently always uses the first monitor. I', clueless about whether someone found a solution for this (and I haven't been doing any Windows programming myself recently, so I haven't tried myself ).

This is an internal boundary that prevents specify a larger size . The only workaround is to configure a smaller font.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683193(v=vs.85).aspx
