### ISSUE TITLE
Output displays make: write error

### ISSUE THREAD

**Issue by sapomuyverde** [cbucher/console#365]
Hi,
When I run make within the console itself ends the compilation and generates the binary file, but displays this output:
> make: write error

Here diagnose file 
[dmpFFBF.txt](https://github.com/cbucher/console/files/432853/dmpFFBF.txt)

Regards,
Javier

**Comment by cbucher** [comment]
I see no link with ConsoleZ.
Are-you sure you don't reproduce your issue without ConsoleZ? (By testing in same conditions: same shell, same command lines and same environment variables.)
