### ISSUE TITLE
Problems with docker-composer and encoding

### ISSUE THREAD

**Issue by MihaMarkic** [cbucher/console#367]
Hi guys,

When using docker-composer with ConsoleZ, it'd spit out 
"LookupError: unknown encoding: cp65001" (error coming from python code).
It works in normal cmdline and powershell windows as well, so I guess it has something to do with ConsoleZ.
Is this something that can be addressed?

**Comment by cbucher** [comment]
http://stackoverflow.com/questions/35176270/python-2-7-lookuperror-unknown-encoding-cp65001

**Comment by cbucher** [comment]
error coming from python code
