### ISSUE TITLE
Creating new tab sometimes moves entire window

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#375]
### Summary
When creating a new tab (in my case, with the hotkey ALT+W), the main window moves down a little after making the first new tab if the window was previously moved.

### Expected Behavior
When making a new tab, the window should stay where it is.

### Actual Behavior
What actually happens.

### Steps to reproduce
1. Configure ConsoleZ to remember it's size and position. Have it set about half way down the screen and all the way to the left. Close so this is saved as the default position.
2. Launch the program.
3. Move the window about half way up, so it's about 1/3rd to 1/4th down your screen and still all the way to the left.
4. Make a new tab - note the window goes back down to where it was at step 2.
5.) Making a new tab here doesn't move it - but move it back up and make a new tab. It will go back down. For some reason, this will only work when the window is pushed all the way to the left (snapped).

### Diagnostic Report
Please see attached - too big to copy here.
[diagnose.txt](https://github.com/cbucher/console/files/514997/diagnose.txt)

### Crash Report
NA

**Comment by cbucher** [comment]
The bug is linked with "Snap to edges" feature.

**Comment by cbucher** [comment]
@msmigiel Please try last experimental version.

**Comment by msmigiel** [comment]
I'm still able to simulate this bug in "ConsoleZ.1.17.2.16290 x64".

**Comment by cbucher** [comment]
@msmigiel docking problem should be fixed in last experimental version.

**Comment by msmigiel** [comment]
Thank you, this appears to be fixed in "1.17.2.16300".

**Comment by cbucher** [comment]
Thx for your feedback
