### ISSUE TITLE
"Diagnose" should open in default text editor, not Notepad

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#376]
### Summary
When clicking "Diagnose", a file opens in Notepad. I use Notepad++ as my default .txt editor and is associated that way on my system. ConsoleZ should respect the system's file associations and use whatever editor the user has associated.

### Expected Behavior
The default text editor on the system should be used.

### Actual Behavior
Notepad is always used.

### Steps to reproduce
1. Go to Help -> Diagnose.
2. Note that Notepad is used instead of the default text editor on the system.

### Diagnostic Report
Please see attached
[diagnose.txt](https://github.com/cbucher/console/files/515004/diagnose.txt)

### Crash Report
NA

**Comment by cbucher** [comment]
The diagnostic filename is created with GetTempFileName API. The filename extension is .tmp and not .txt.

The primary purpose of the diagnostic is: copy/paste the content into a bug report. There is no need for advanced editing features :wink:
