### ISSUE TITLE
Please consider making the app taskbar/tray icon editable

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#378]
### Summary

Please consider making the application taskbar and tray icon end user editable - either with some predefined choices or allowing the user to enter a path to their own icon. I personally really liked the dark icon used in 1.12 and earlier and while the new icon is very nice, it looks similar to some of my other programs so at quick glance, I often misclick it for something else.

**Comment by cbucher** [comment]
Go to `Settings/Appearance`.
In `Title & Icon` section, uncheck `Use tab icons` and select an icon.
Restart the application.

**Comment by msmigiel** [comment]
Thank you for the clarification. That seems to change the application's icon - but is there any way to get the tabs to match this custom icon too? I'm sorry if I wasn't clear earlier - I'm trying to change all of the icons (application and tabs) to a custom icon and it seems that as of now, you can only change the application's icon.

**Comment by cbucher** [comment]
1) I agree, This is a more consistent behavior.
But if no one complained for many years, perhaps this behavior is helpful to others.
In my work configuration, I have many tabs and they all have a distinct icon.

2) I seen that icon modification requires a restart when I previously commented. I immediately removed the restart requirement.
Concerning tab icons: restart the application is not required, new tabs have the correct icon.

**Comment by msmigiel** [comment]
1.) Maybe that's true, but I have been using this program (ConsoleZ and the previous Console) for many years and never noticed it until I started to play around with it. Personally I think it would be better and more consistent to have tabs inherit the icon (even custom ones) as they already inherit colors, etc... Working with a bug is no excuse for the bug. :)

**Comment by cbucher** [comment]
If someone want to distinguish two distinct instances of ConsoleZ (using distinct settings) without modifying the tab icon, the current behavior is useful.
So I cannot consider this as a bug and break the current behavior.
I can add a new setting for empty tab icon.

**Comment by cbucher** [comment]
Please try last experimental version.

**Comment by msmigiel** [comment]
For the most part I think this is working as designed but here are my observations:

1.) I am able to change the global application icon without restart - this is good.
2.) When changing a tab's icon, it only affects newly opened tabs - I think this is as intended but I wanted to see if it makes sense to update already opened tab icons too.
3.) On the Tab settings screen, if I select "Use default" and have the "Icon:" field empty, the icon becomes what I think is some default Windows 7 icon when no icon is found (blue/white icon with 2 gears). I think this should default to the application's icon. To simulate, create a new "Tab" in settings and select "Use default" without giving a file path. If "Use default" is not selected, the proper default icon is used (the application's icon).

**Comment by cbucher** [comment]
2) yes this is the intended behavior

3) if you check default, the icon field is ignored (disabled) and we search the shell icon  (same icon as in explorer). If shell is empty, default icon is ConsoleZ icon.
This is the intended behavior.

Icon with two gears is the default icon for batch script, your shell seems to be a .bat or .cmd file.

**Comment by msmigiel** [comment]
You're right - that was it. My shell for that tab was cygwin.bat. 

However, is this behavior what should happen? "Use default" I thought meant to use the default application's icon, ie the default ConsoleZ icon, not the shell's icon. Maybe this checkbox should be renamed to either "Use Application Icon" or "Use Shell Icon" ? Maybe even expose both options.

**Comment by cbucher** [comment]
"default" means default shell icon
I will change the text (translators will be pleased...)

But I'm surprised the checkbox behavior is difficult to understand: that's described in manual and you can visually see the result when you check/uncheck.

**Comment by cbucher** [comment]
@msmigiel done in last experimental version
For more consistency, when "Use shell icon" is checked, I extract the icon from %ComSpec% command line (usually cmd.exe).

**Comment by msmigiel** [comment]
Thank you, I think this is more clear now. I do have a few more observations:

1.) In "Settings -> Console -> Shell", I have it set to cygwin.bat. In "Settings -> Tabs -> <my tab> -> Shell", I have this blank so it will default to cygwin.bat. If I select "Use shll icon", it uses the icon of cmd.exe but I would think the default shell of cygwin.bat would be more appropriate?

2.) With the above settings, if I make a new tab group and have the shell set to cmd.exe (with no icon), the default icon is the program icon - this is correct. However, "Use shell icon" doesn't appear to be doing anything.

**Comment by cbucher** [comment]
1) yes
2) you must set a correct full path for the shell (icon extraction functions don't use PATH environment variable)

**Comment by cbucher** [comment]
@msmigiel Please, try last (beta) version.
