### ISSUE TITLE
Please consider adding option to prevent closing of application on exit of last/only tab.

### ISSUE THREAD

**Issue by Merlin8000** [cbucher/console#385]
I'd like to have the ability for console to start a new default tab when the last tab exit, keeping the application open.

My particular use case is for the Quake-style configuration, so that when I exit my command-line session, it simply closes the console and then spawns a command line, leaving the ability to load a command window by global hotkey available.

**Comment by cbucher** [comment]
Why exit your command-line session if you don't want to terminate ConsoleZ?

**Comment by Merlin8000** [comment]
For me,  it boils down to one of these three purposes. 

1) force of habit
2) to quickly clear the screen and buffer
3) to reset the command environment to default 

They all have more cumbersome avenues to the same place, but it would be nice to not have to think about it.

For a little more context, this is the behavior I have with Yakuake.  So far, that's the only Yakuake behavior that I can't replicate using ConsoleZ.

**Comment by cbucher** [comment]
@Merlin8000 Please try last (beta) version.
There is an option in `Settings/Behavior/Close-Detach`.
Actually, ConsoleZ cannot start with no shell, but you can now close all tabs.

**Comment by Merlin8000** [comment]
I've been using it for a couple of days now, seems to be working well.

If I exit the last tab, hitting Ctrl+F1 brings up the default tab.  If I decide that I want to actually exit the application, I can still use alt+f,X.

**Comment by cbucher** [comment]
thanks for your feedback
