### ISSUE TITLE
DLL injection has failed (reason: (GetThreadContext)The parameter is incorrect.

### ISSUE THREAD

**Issue by HeinrichGit** [cbucher/console#387]
### Expected Behavior > v. 1.17.1.16266 / Win 8.1 64 (in a virtualBox)
Start a tab defined like: Tab -> Shell: Shell: C:\PortableGit\bin\bash.exe --login -i

### Actual Behavior
DLL injection has failed (reason: (GetThreadContext)The parameter is incorrect.
)!

### Steps to reproduce
1. Start a tab defined like: Tab -> Shell: C:\PortableGit\bin\bash.exe --login -i
PS The same with sh.exe
PS The same with Shell: C:\cygwin\bin\bash.exe -l
2. Open a new Tab and observe the eror

**NOTE** : With 1.16.1.16068 the problem doesn't exist.

**Comment by cbucher** [comment]
You can reopen the issue after providing the diagnostic report.

But I'm guessing you use 32 bits version of ConsoleZ and attempt to load 64 bits shells.

**Comment by HeinrichGit** [comment]
You were right. Sorry for bothering. It was indeed the 32b version trying to load 64 bits.
