### ISSUE TITLE
ConsoleZ contents don't use additional height of second bigger display

### ISSUE THREAD

**Issue by VarunAgw** [cbucher/console#389]
I don't know how to really describe this. I have two monitors. Second one is external and is bigger.

Suppose I launch ConsoleZ with Mon 1 as primary and then move it to Mon 2, a little space at bottom is ignored.

But if I disable Mon 1, and launch console Z with Mon 2 as default, it cover full area this time.

I am uploading a screenshot to make it more clear.

![console](https://cloud.githubusercontent.com/assets/4201835/20623845/df3f8854-b309-11e6-9310-8c17976096b0.png)

**Comment by cbucher** [comment]
Next time, follow the issue template instructions!
Read FAQ: https://github.com/cbucher/console/wiki/FAQ#why-am-i-limited-in-number-of-rowcolumn
