### ISSUE TITLE
Japanese font overlap

### ISSUE THREAD

**Issue by rosolino** [cbucher/console#390]
Hello.
I use version 1.17.2.
Japanese font displayed overlapped like attached screen shot.

[dmp14B3.tmp.txt](https://github.com/cbucher/console/files/615433/dmp14B3.tmp.txt)
![overlap](https://cloud.githubusercontent.com/assets/6219165/20656947/40120a04-b575-11e6-89c2-2aeab0583f8d.png)

**Comment by cbucher** [comment]
Hello,

It looks like your code page is not DBCS.
Can you dump the registry key `HKEY_CURRENT_USER\Console`?
Can you verify the code page returned by typing the command `chcp`?

**Comment by rosolino** [comment]
[console.txt](https://github.com/cbucher/console/files/617758/console.txt)


Hello.
chcp result was 65001.
Is is OK to chage to 932 ?

**Comment by cbucher** [comment]
Yes, change to chcp 932 will fix.
Otherwise you can try to add an extra width in `Settings/Appearance/Font`, `Extra width' input  (but all chars will use a larger space, including latin chars).

**Comment by rosolino** [comment]
Thanks,
Overrap fixed on Powershell and cmd.exe.
But still overrapped on Bash for windows.
Locale of Bash for windows is ja_JP.utf8.
Is this reason for overrap ?

I tryed 'Extra width' ,but hard to see.

**Comment by cbucher** [comment]
I don't know. Is there an overlap when you use Bash for Windows without ConsoleZ?

**Comment by cbucher** [comment]
>I tryed 'Extra width' ,but hard to see.

Extra width is defined in pixels.
Extra width = 0
![capture](https://cloud.githubusercontent.com/assets/363759/20746643/ef4de836-b6e6-11e6-8112-9224e161a438.PNG)

Extra width = 10
![capture](https://cloud.githubusercontent.com/assets/363759/20746594/b8391e06-b6e6-11e6-95dd-e91a98cc2018.PNG)

**Comment by rosolino** [comment]
No, only on ConsoleZ, there is an overlap like below.
![bashonw1](https://cloud.githubusercontent.com/assets/6219165/20776525/71f663ae-b7a4-11e6-8b23-014bef8b318b.PNG)

on console window, there is no overlap.

![bashonw2](https://cloud.githubusercontent.com/assets/6219165/20776547/940cc0d2-b7a4-11e6-9fa9-5485177277a3.PNG)

Sorry about Extra width.
Because laten character space extends,It is hard to see.

**Comment by cbucher** [comment]
Can you show the real console window (`Menu/View/Console Window`) and take a screenshot of `Properties/Font` dialog?

**Comment by rosolino** [comment]
Real Console Window and Font dialog.  I use MS Gothic.

![console1](https://cloud.githubusercontent.com/assets/6219165/20818674/8325fe7c-b872-11e6-9d7e-714ac1ad4d72.PNG)

I notice when I use Bash on widows , code page of console window change to utf-8 like below.

![console2](https://cloud.githubusercontent.com/assets/6219165/20818712/bf0c80be-b872-11e6-9d72-17b2118b1d05.PNG)

Of course,when i use Powershell, code page is 932 (same with registry)

![console3](https://cloud.githubusercontent.com/assets/6219165/20818734/e24d6692-b872-11e6-8ad0-f31bc17e9ab3.PNG)

**Comment by cbucher** [comment]
UTF-8 code page explain why COMMON_LVB_LEADING_BYTE flag is missing.
I suppose that Bash On Windows sets the code page.
If Japanese chars are correctly displayed without DBCS flags, then Microsoft developers cheat and have modified the behavior of CONHOST...

Normally, without DBCS flags you can write 80 chars in a 80 columns buffer. in this case the right string should be truncated if chars are displayed with double width.
Can you fill an entire line with Japanese chars and take a screenshot of ConsoleZ and real console?
In a 80 columns buffer how many Japanese chars can you write?

**Comment by rosolino** [comment]
I input Japanese Char from IME like below.
![inputchar](https://cloud.githubusercontent.com/assets/6219165/20872161/cac02518-badf-11e6-9460-3875942f0c24.png)

consolez displayed like below

![consolez](https://cloud.githubusercontent.com/assets/6219165/20872173/e2496104-badf-11e6-8a68-b9ea68a6ba90.PNG)

Console displayed 

![console](https://cloud.githubusercontent.com/assets/6219165/20872186/f140af6e-badf-11e6-8cec-656ded091ffb.PNG)

I think that bash on windows do not seem to be able to input Japanese accurately yet.

**Comment by cbucher** [comment]
It seems in console, chars don't have a fixed width.
Can you take screenshots with this text ?

```
こんにちは世界
0123456789012345678901234567890123456789
こabんcdにefちghはij世kl界
0123456789012345678901234567890123456789
こ_ん_に_ち_は_世_界
012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
こんにちは世界こんにちは世界こんにちは世界こんにちは世界こんにちは世界こんにちは世界こんにちは世界こんにちは世界こんにちは世界こんにちは世界
```

**Comment by rosolino** [comment]
ConsoleZ
![consolez-result](https://cloud.githubusercontent.com/assets/6219165/21173970/daf0f904-c21d-11e6-8bba-536c2db23a8e.PNG)

console

![console-result](https://cloud.githubusercontent.com/assets/6219165/21173979/e9712b48-c21d-11e6-9ad9-294985fa515f.PNG)

**Comment by cbucher** [comment]
The purpose of long  text lines was to see the behavior with return lines.
Please, can you test with a 80 columns console and with a 71 columns console?

**Comment by rosolino** [comment]
ConsoleZ 80 columns

![80-consolez](https://cloud.githubusercontent.com/assets/6219165/21211735/537c8bc6-c2c9-11e6-92fc-f310aea7fb24.PNG)

console-80 columns

![80-console](https://cloud.githubusercontent.com/assets/6219165/21211739/661d0a9e-c2c9-11e6-818a-c5829f0c47ca.PNG)

ConsoleZ-71 columns

![71-consolez](https://cloud.githubusercontent.com/assets/6219165/21211747/7cac4aae-c2c9-11e6-96c0-fb41dae26468.PNG)

console-71 columns

![71-console](https://cloud.githubusercontent.com/assets/6219165/21211757/939133c4-c2c9-11e6-8ce2-955b4b254f14.PNG)

I used MS Gothic (Fixed font).
Reagrds.

**Comment by cbucher** [comment]
So I was right [here](https://github.com/cbucher/console/issues/390#issuecomment-264430344).
Windows console text is right truncated. 
Console buffer is wrongly filled by WSL with double width chars.

**Comment by rosolino** [comment]
Thank your for your investigation.
I do not know the details, but as written in the following URL,
bash.exe seems to behave in a special way.

https://conemu.github.io/en/BashOnWindows.html
