### ISSUE TITLE
Quake mode doesn't work with maximized window

### ISSUE THREAD

**Issue by iamkarlson** [cbucher/console#391]
### Expected Behavior
When windows is maximized work the same as normal

### Actual Behavior
Just showing up by hotkey, no quake style

### Steps to reproduce
1. Set up quake mode by faq
1. Open consolez as normal windows - works fine
1. maximize window
1. hide and show works like usual pop and hide

### Diagnostic Report
[dmpA516.tmp.txt](https://github.com/cbucher/console/files/618341/dmpA516.tmp.txt)

**Comment by cbucher** [comment]
As noted in documentation, AnimateWindow API doesn't support non-client area with AERO. This means you must uncheck `caption` and `resizable` option in `Settings/Appearance`.

You can define ConsoleZ initial size and initial position to mimic maximized window.
