### ISSUE TITLE
ConsoleZ window will only show 71 lines even if the window is larger

### ISSUE THREAD

**Issue by jones-g** [cbucher/console#392]
### Expected Behavior
Maximizing the window with a powershell or cmd prompt show lines all the way to the bottom of the window. This works with powershell or cmd directly

### Actual Behavior
Maximum lines is capped at 71 lines leaving a black space at the bottom (see screenshot attached).

### Steps to reproduce
1. Open tab with powershell
2. Resize window to above 71 lines
3. Lines will not go above 71 lines

### Diagnostic Report
![consolez71lines](https://cloud.githubusercontent.com/assets/5399484/20920749/788deb78-bba1-11e6-9c1f-87f6f24b4bd1.png)
[ConsoleZ aero amd64 1.17.2.txt](https://github.com/cbucher/console/files/633456/ConsoleZ.aero.amd64.1.17.2.txt)

**Comment by cbucher** [comment]
duplicate duplicate duplicate ...
https://github.com/cbucher/console/wiki/FAQ#why-am-i-limited-in-number-of-rowcolumn
