### ISSUE TITLE
Enhance inactive tab activity flash color

### ISSUE THREAD

**Issue by Slamdunk** [cbucher/console#393]
Hi, first of all congratulations for this amazing fork; have been using Console2 for years, and now this is a huge improvement.

Following https://github.com/cbucher/console/issues/99 I'm here to ask a better color/highlight of activity flash on inactive tab:

Console2:
![console2-tab-highlight](https://cloud.githubusercontent.com/assets/152236/20924170/7c76c5ac-bbb0-11e6-8d21-88b32a187ef5.png)

ConsoleZ:
![consolez-tab-highlight](https://cloud.githubusercontent.com/assets/152236/20924196/97b898d6-bbb0-11e6-877a-e6a6d6d244d2.png)

The second tab is the target.
On both I need to be noticed, and in ConsoleZ is pretty invisible the difference: is possible to improve it?

PS: again, cheers for your work 👏 🎉 

[ConsoleZ.x64.1.17.2.16323.zip](https://github.com/cbucher/console/releases/download/1.17.2/ConsoleZ.x64.1.17.2.16323.zip)

**Comment by cbucher** [comment]
ConsoleZ uses system colors to render tabs (COLOR_HIGHLIGHT). You can change the system colors or your theme aero color.

In your screenshot, I don't think the highlight is invisible: verify your monitor contrast settings.

You can also modify the number of flashes.
