### ISSUE TITLE
Console as a 64-bit app

### ISSUE THREAD

**Issue by d73** [cbucher/console#396]
Is there any way to make ConsoleZ run as a 64 bit app?

The reason I ask is that it currently seems to run as a 32 bit app (shows as Console.exe *32 in Task Manager). I have my shell set to cmd.exe. And cmd.exe will run as a 32-bit app because it is being started by a 32-bit app. Which means that I can't run telnet.exe because it is a 64-bit app.

If I go to Start -> Run -> cmd.exe then cmd.exe starts as a 64 bit app, and I can run telnet.exe.

**Comment by cbucher** [comment]
?!? 32 bits and 64 bits release are available... Install and launch the good one.
See download page in wiki.

**Comment by d73** [comment]
Cos I'm blind apparently. Sorry!!!
