### ISSUE TITLE
Option to hide the "close tab" button

### ISSUE THREAD

**Issue by d73** [cbucher/console#397]
Request for an option to hide the "close tab" button (ie the red X on the right side of the tab).
Thank you :-)

**Comment by cbucher** [comment]
What is the purpose of this development?

**Comment by cbucher** [comment]
@d73 Please try last experimental version.

**Comment by cbucher** [comment]
@d73 Please try last experimental version.

**Comment by d73** [comment]
@cbucher Tested 1.18.0.17030 - perfect :1st_place_medal:

**Comment by cbucher** [comment]
thx
