### ISSUE TITLE
Request for tab title to reflect current directory in realtime

### ISSUE THREAD

**Issue by d73** [cbucher/console#398]
### Expected Behavior
When I change directory, expect tab title to change accordingly.

### Actual Behavior
Tab title does not change in real time. Tab title only changes when tab focus is changed.

### Steps to reproduce
1. Set format string set in Settings -> Appearance to: %d

2. create a tab (tab A)
note that the tab is called (in my case) d:\
which is correct and expected behaviour

3. cd to some other directory (eg cd \git)
tab title remains unchanged (ie d:\)
expected title is d:\git

4. change focus to a different tab or create a second tab
tab title of Tab A is changed to reflect the correct path (ie d:\git)

Thank you!

**Comment by cbucher** [comment]
https://github.com/cbucher/console/issues/274#issuecomment-267704304

>Actually, using %d or %D is not recommended in tabs, because directory changement is not signaled. You must wait for another signal or select another tab to see the tab text refreshed with correct directory. **I will check if there is a performance impact by adding this enhancement.**

**Comment by d73** [comment]
Thank you for this enhancement! Closing this req.

**Comment by Rhywun** [comment]
I upgraded to version 1.18.1.17087 and I'm still having the same issue as the OP. In fact the current directory is not reflected on the tab after switching tabs either.

(Installed to Win7 via chocolatey)

**Comment by cbucher** [comment]
Either shell does not use SetCurrentDirectory WIN32 API (for example PowerShell).
Either injection is made in another process: you start a process that launches the shell (for example "C:\Program Files\Git\bin\bash.exe" starts "C:\Program Files\Git\usr\bin\bash.exe").

**Comment by Rhywun** [comment]
Ah, I see my problem. I didn't realize the "default shell" setting overrides the "tab shell" setting. My default shell was set to "ansicon" but I was using a tab with no shell setting. Once I removed the "default shell" setting everything behaves as desired. Thanks!
