### ISSUE TITLE
Request to not set default tab title to ConsoleZ

### ISSUE THREAD

**Issue by d73** [cbucher/console#399]
### Expected Behavior
Tab title setting should respect my choice to have an empty string as the default title

### Actual Behavior
Tab title defaults to "ConsoleZ" if the setting is an empty string

### Steps to reproduce
1. Go to Settings -> Tabs
2. Delete the "Title" in the "Title & icon" section
3. Click OK to save settings
4. Reopen Settings -> Tabs
5. Tab title has been auto-populated as "ConsoleZ"

### My Use Case
This is my tab title string: `?t(%t):(?s(%s):(%d))`
I want to show either the running process or the current directory unless I explicitly set a title for the current tab. However, because the tab title defaults to "ConsoleZ", ?t always evaluates as true.

### Current workaround
1. Open console.xml
2. Add `title=""` to the relevant <tab ...> tag, eg
```
<tab title="" use_default_icon="0">
<console shell="" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
</tab>
```
3. This works until console.xml is overwritten by changing/saving any settings.

**Comment by cbucher** [comment]
Tab title is not designed to be empty, ConsoleZ is the default value.
See a good practice here: https://github.com/cbucher/console/issues/395#issuecomment-266958727
