### ISSUE TITLE
Theme colour being shown on toolbar and tabs

### ISSUE THREAD

**Issue by adamralph** [cbucher/console#401]
### Expected Behavior

When I switch on Settings -> Personalisation -> Colours -> "Show colour on title bar" in Windows 10:

<img src="https://cloud.githubusercontent.com/assets/677704/21581475/8ce8b836-d033-11e6-9cf2-34f1186cdfb1.png" width="176" />

I expect the theme colour to be shown on the title bar:

<img src="https://cloud.githubusercontent.com/assets/677704/21581396/37d4ca9e-d031-11e6-9488-04d8efd3df0c.png" width="544" />

### Actual Behavior

The theme colour is also applied to the toolbar and tabs:

<img src="https://cloud.githubusercontent.com/assets/677704/21581363/3be2815e-d030-11e6-9cf4-97027c42b271.png" width="544" />

### Steps to reproduce
1. Switch on the Settings -> Personalisation -> Colours -> "Show colour on title bar" ([added in Windows 10 1511](https://twitter.com/jonstodle/status/815234675031543808)).
2. Open ConsoleZ.

### Diagnostic Report
[dmp3829.txt](https://github.com/cbucher/console/files/680012/dmp3829.txt)

**Comment by cbucher** [comment]
This is not an issue but the intended aero theme.

**Comment by adamralph** [comment]
@cbucher I realise that beauty is in the eye of the beholder, but IMHO it looks rather terrible. Is it worth reconsidering this design?

**Comment by cbucher** [comment]
@adamralph I agree, you chose a terrible green color :wink:
You can try the legacy version (available in full version, see wiki/download section).

**Comment by adamralph** [comment]
I appreciate my choice of green isn't to everyone's taste 😉 

However, this is going to look similar regardless of which colour is chosen. I don't believe that the theme colour should be used for the toolbar and tabs. I've not come across any other application which does this.

**Comment by cbucher** [comment]
>I don't believe that the theme colour should be used for the toolbar and tabs. 

So aero theme is not your taste. Try the legacy one...

**Comment by adamralph** [comment]
IMHO it's not a matter of taste, I believe the behaviour is wrong. The theme colour should not be used for those elements. I guess we're not going to agree on this though. `¯\_(ツ)_/¯`

**Comment by cbucher** [comment]
It's your opinion, but not shared by designers of major applications like:
- Firefox
- Chrome
- Internet explorer
...

And for the last time, there is another version without aero theme...

**Comment by adamralph** [comment]
### Chrome

![image](https://cloud.githubusercontent.com/assets/677704/21605783/98833d3c-d1ab-11e6-9d87-90bc6fb7d3e9.png)

- No theme color in the toolbars
- Theme color used in the in active tabs and tab background, but this is adjacent to the title bar so it blends in naturally

### IE

![image](https://cloud.githubusercontent.com/assets/677704/21605835/fcc7e0ae-d1ab-11e6-96f4-4a12580c4d81.png)

(Similar to Chrome)

### Firefox

I don't have it so can't compare.

### Others

![image](https://cloud.githubusercontent.com/assets/677704/21605879/453703e2-d1ac-11e6-9677-05e995ce46d1.png)

![image](https://cloud.githubusercontent.com/assets/677704/21605914/78341334-d1ac-11e6-9cad-5f654676613c.png)

---

I think the main issue is the use of the theme colour for the toolbar. I can't see any other app which does this. The use of the color for the tabs section is arguable, but one common aspect in all the other apps is that the use of the theme colour is contiguous, i.e. those elements which use it are adjacent to the title bar, so there is only section which has that colour, as opposed to a coloured section, a default (grey) section and then another coloured section, as in the case of ConsoleZ.

Anyhow, I'll stop here. The point has become moot to me anyway, since I've decided to switch to Cmder. No hard feelings, I just feel it's the better app for my needs and I'm switching regardless of this issue.

BTW - while you can point to the legacy version as being a version that is available without this (IMHO broken) styling, it's a still a *legacy* version and as a user, I wouldn't want to have to restrict myself to a legacy version to avoid something which I feel is broken in the current version. I'd want that to be fixed in the current version.

**Comment by cbucher** [comment]
>I think the main issue is the use of the theme colour for the toolbar. I can't see any other app which does this. 

because toolbars are deprecated and no more used... hide the toolbar ;-)
