### ISSUE TITLE
Arabic text

### ISSUE THREAD

**Issue by reza1615** [cbucher/console#402]
### Expected Behavior
can render Arabic strings

### Actual Behavior
With Lucid Console font it doesn't show correctly

### Steps to reproduce
1. I made a txt file which contains 
```
ASCII              abcde xyz
German             äöü ÄÖÜ ß
Polish             ąęźżńł
Russian            абвгдеж эюя
CJK                你好
Arabic             جيدة هذا هو اختبار
```
and do these steps
2-change font to lucid console
3-chcp 1256
4-type mytext.txt
5- it shows the text like below
```
ASCII              abcde xyz
German             أ¤أ¶أ¼ أ„أ–أœ أں
Polish             ؤ…ؤ™إ؛إ¼إ„إ‚
Russian            ذ°ذ±ذ²ذ³ذ´ذµذ¶ رچرژرڈ
CJK                ن½ ه¥½
Arabic             ط¬ظٹط¯ط© ظ‡ط°ط§ ظ‡ظˆ ط§ط®طھط¨ط§ط±
```

**Comment by cbucher** [comment]
`type` command outputs content of the file without checking encoding.
Here you write content of an UTF-8 encoded file on console (code page 1256) .
That doesn't work **with or without** ConsoleZ!
Change console code page to UTF-8 or create a file in Windows 1256 encoding.

![capture](https://cloud.githubusercontent.com/assets/363759/21655941/483d581e-d2bc-11e6-9699-145732ba3cc9.PNG)
