### ISSUE TITLE
Request for improved menu icons

### ISSUE THREAD

**Issue by hl2guide** [cbucher/console#407]
Less blurry main menu icons would be nice to have 💃

**Comment by cbucher** [comment]
Already done for 16x16 icons in experimental version.
Please try it.

**Comment by cbucher** [comment]
@hl2guide Please, try experimental version. Does this version meet your expectations?

**Comment by hl2guide** [comment]
Much, much nicer :D Well done, can't wait for your next release 💃

**Comment by cbucher** [comment]
Thx
