### ISSUE TITLE
Request: Option to pass mouse scroll events to console window

### ISSUE THREAD

**Issue by tidzo** [cbucher/console#408]
I'm using ConsoleZ with git-cmd.exe and frequently run openssh connections to remote machines where I run vim.

I can click around inside vim sessions fine, and drag splits etc, but using the mouse scroll wheel causes the whole terminal to move, not just the vim buffer.  That is to say the vim status line moves up and down rather than moving the cursor inside the buffer.

However, if I turn on the console window with View->Console Window, and scroll the mouse there, I get the desired behaviour of scrolling up and down inside the file I am editing, and the ConsoleZ window reflects the same activity.  But if I return focus to the ConsoleZ window and scroll, the whole terminal moves again.

I've tried both with and without explicit mappings of ```<ScrollWheelUp>``` and Down in my .vimrc 

I don't think this a bug as such, more of a feature request if I've understood correctly how consoleZ works.  It would be extremely laborious for me to get the output from Help->Diagnose from the heavily-locked-down work machine (which I nonetheless eventually managed to get consoleZ to run on!) so I've not included that, but, retyping a few pertinent details:

```
ConsoleZ Aero x86 1.17.1
Windows 7 SP1 (32 bit) 6.1.7601
elevated? no
...
shell=....git-cmd.exe --cd-to-home --command=usr/bin/bash.exe -l -I
```

Also the env variable TERM is currently set to 'cygwin' though I've tried other sane values with no benefit.

Thanks for reading.

**Comment by cbucher** [comment]
Hi

I tried Vim via SSH.
If I set Vim with
```
:set mouse=a
:set term=xterm
```

The behavior is the expected one.

**Comment by cbucher** [comment]
The only problem here is to guess when forwarding the mouse wheel scrolling.

WM_MOUSEWHEEL window message is transformed into a MOUSE_EVENT_RECORD which can be read with ReadConsoleInput API by the console application.

But this should be done only when there is an application which use ReadConsoleInput.
And I have no way to detect this.
I cannot guess if I have to scroll in ConsoleZ or send a MOUSE_EVENT_RECORD .

Do you have an idea?
A mode that can be (in)activated by command (menu entry/shortcut) can do the job?

**Comment by cbucher** [comment]
[ConsoleView.zip](https://github.com/cbucher/console/files/745522/ConsoleView.zip)

**Comment by cbucher** [comment]
@tidzo Please, try the command from last experimental version.

![image](https://cloud.githubusercontent.com/assets/363759/22586107/52f716fe-e9fb-11e6-9203-0ea4210e7e4e.png)

![image](https://cloud.githubusercontent.com/assets/363759/22586066/15feef7e-e9fb-11e6-891d-2ef5489e27ee.png)

**Comment by cbucher** [comment]
@tidzo Please, try the `Forward Mouse Events` command from last beta version.

**Comment by tidzo** [comment]
Thanks so much for adding this feature.   I'm sorry I didn't get back to you; I've been offline following a family bereavement.  It looks like you've done exactly what I hoped for - thanks.
