### ISSUE TITLE
Feature request - Powershell - resize window content to fill screen regardless of column setting

### ISSUE THREAD

**Issue by ClairelyClaire** [cbucher/console#410]
PowerShell in Windows 10 finally supports both full window maximization and resizing the window's content to the full width of the window, rather than adhering to a static column limit. Is it possible to implement the same in Console?

**Comment by cbucher** [comment]
This is the default behavior of ConsoleZ.

https://github.com/cbucher/console/wiki/FAQ#why-am-i-limited-in-number-of-rowcolumn

**Comment by ClairelyClaire** [comment]
I took a look at that but I'm using English, so how would I ensure that full window width is available? It seems stuck at 135 columns.

**Comment by cbucher** [comment]
**FAQ:**
>Windows calculates the max number of row/column using the primary monitor size and the Windows console font size (do not confuse with ConsoleZ font!).

**manual:**
You can skip language files installation and go to step 3.

>Unhide windows console (View->Console window) and open its properties dialog. Go to "Font" tab. Raster Fonts will be selected in the fonts list. Choose the other, TrueType font. For most languages, this will be Lucida Console.

>Anyway, select proper TrueType console font and set its size to something small (8 or 10 points). Small size will allow you bigger max ConsoleZ window size. 

If your issue is not solved, post a diagnostic report.

**Comment by ClairelyClaire** [comment]
Thank you!! I was changing Defaults rather than Properties for the console window.

What about syntax highlighting? I'm not seeing all the colors that are used in the PS-based tool I use regularly. The colors are there in a regular PS session.

**Comment by cbucher** [comment]
For questions/chatting you can use [![Join the chat at https://gitter.im/cbucher/console](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/cbucher/console?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge).

Only one problem per ticket, otherwise it is chaos.
