### ISSUE TITLE
Ability to duplicate focused tab, including running processes

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#411]
### Summary
I'm not sure if this is possible but I would like to discuss and see if it is. 

I use ConsoleZ with Cygwin to SSH into remote Unix machines. When I start the program and a new tab appears, it is local to my machine. I then use something like "ssh user@machine" to get into my remote machine. Would it be possible that when doing a "Clone in new tab" to also include the running process - in this case, duplicate a connection to my remote machine?

**Comment by cbucher** [comment]
Very difficult
- How to guess the right process to duplicate?
process to duplicate can be the last of the process tree or not
process to duplicate can be in the process tree or not
- How to create it?
simply duplicate the command line is very optimistic

Personally, I created a tabs with `ssh.exe ...` as shell command line (one by remote machine).

**Comment by msmigiel** [comment]
Thank you for the feedback. I wasn't sure this was possible or how to implement it so I figured I would ask someone smarter than me. :)

Creating a new tab with ssh.exe is a good solution and something I wouldn't have thought of - thank you for the idea.

**Comment by cbucher** [comment]
You're welcome
