### ISSUE TITLE
Customizable hotkey for "Copy All to Clipboard"

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#412]
### Summary
Coming from Putty and other similar terminal emulators and front ends, they have a command/hotkey to copy all of the contents of a tab to the clipboard. Please consider adding to the Hotkey screen the ability to provide a custom hotkey to copy everything to the clipboard (without the need to first highlight everything and then copy).

**Comment by garoto** [comment]
Have you tried this:
![screenshot-0554-02-02-2017](https://cloud.githubusercontent.com/assets/11768175/22560846/c976dfe6-e954-11e6-90dc-f8a6550a72b5.png)

**Comment by cbucher** [comment]
Configure the behavior in `Settings/Behavior/Copy & Paste`.
![capture](https://cloud.githubusercontent.com/assets/363759/22561615/433fd200-e979-11e6-828d-b4d33ef837b5.PNG)
