### ISSUE TITLE
Different transparency when full screen

### ISSUE THREAD

**Issue by JPlumridge** [cbucher/console#414]
Is it possible to have different transparency settings for Windowed and Full screen modes? The ability to do this with the "Controls" section in Styles is great, and I'd love to be able to do this with transparency.

**Comment by cbucher** [comment]
Can you be more specific concerning transparency settings that can be different between windowed and full screen?

You want to
- switch transparency mode?
- switch on/off transparency? (like menu/view/switch on/off transparency)
- change alpha transparency value?

**Comment by JPlumridge** [comment]
Sure, specifically what I'd like to have is:

**Windowed:**
- Colour background or image background
- No transparency

**Fullscreen:**
- Transparent single color background

Ideally it would be great if all of the transparency settings could be different between the two modes (just as the "Controls" are). This would let us set it up however we want.

Another idea: I'd also love if there was a hotkey that was a combination of "Full Screen" and "Activate ConsoleZ". This would mean I could have a regular, windowed session, then while busy in some other window, press the active button and have the quake style dropdown open in full screen!

**Comment by cbucher** [comment]
>Ideally it would be great if all of the transparency settings could be different between the two modes (just as the "Controls" are). This would let us set it up however we want.

Yes, but there can be some limitations with glass transparency: change from glass to other transparency mode (or vice versa) is expensive (and can have unexpected behaviour).

>Another idea: I'd also love if there was a hotkey that was a combination of "Full Screen" and "Activate ConsoleZ". This would mean I could have a regular, windowed session, then while busy in some other window, press the active button and have the quake style dropdown open in full screen!

I'm not sure I understand the idea.
You can use "ActivateConsoleZ" global hotkey and switch to full screen (with hotkey).
If you want combine the two hotkeys in one, you can use some tools like AutoIt.

Switch from regular window to full screen and quake style by pressing one hotkey... I do not have enough room in hotkeys settings to describe the command ;-)
Test plan is already very long and I don't think this feature could interest many users.

**Comment by cbucher** [comment]
@JPlumridge Please, try last experimental version.

**Comment by cbucher** [comment]
@JPlumridge Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by JPlumridge** [comment]
@cbucher This is great, thanks! :+1: 

If we could set (per tab) a different background setting for windowed and full screen, this would be absolutely perfect.

**Comment by cbucher** [comment]
Thx for your feedback.

>If we could set (per tab) a different background setting for windowed and full screen, this would be absolutely perfect.

... and a different cursor and a different set of colors and a different font and ...
There is a threshold where create two distinct setting files and launch two instances of ConsoleZ will be easier ;-)

I think it is useful to allow disable transparency or rise opacity when we switch to full screen. But I don't see the point of modifying other elements.
