### ISSUE TITLE
Cygwin bash cannot display UTF-8

### ISSUE THREAD

**Issue by Slamdunk** [cbucher/console#416]
Hi, stated that I am aware that this **likely is not an issue of ConsoleZ** itself, I'm here to ask you an help or a hit to solve this problem.

I am unable to display Utf-8 charactes when using Cygwin bash.

### Starting environment

- Windows 7 64bit
- Cygwin64 2.877
- Bash 4.4.12(3)-release (x86_64-unknown-cygwin)
- Font Lucida Console

`euro.txt` content:
```
Euro      - €                  -
ASCII     - abcde xyz          -
German    - äöü ÄÖÜ ß          -
Polish    - ąęźżńł             -
Russian   - абвгдеж эюя        -
CJK       - 你好                 -
Arabic    - جيدة هذا هو اختبار -
Symbols   - ✔                  -
```

`C:\cygwin64\bash.bat` content:
```bat
@echo off

C:
chdir C:\cygwin64\bin
REM set LANG=C.utf8
REM chcp 65001
bash --login -i
```

Running the bash I get this result:
![1](https://cloud.githubusercontent.com/assets/152236/23064078/49cd688a-f50e-11e6-8f4c-0eb3deda3b35.png)
which isn't what I want, but at least is something.

Uncommenting one, the other or both the two REM lines:
```bat
set LANG=C.utf8
chcp 65001
```
changes the `locale` and the chcp of course, but doesn't change the output.

### With ConsoleZ

- ConsoleZ 1.17.2.16323
- Settings > Console > Shell: C:\cygwin64\bash.bat
- Settings > Appearance > Font > Name: Lucida Console

With the original `C:\cygwin64\bash.bat` content I get:
![2](https://cloud.githubusercontent.com/assets/152236/23064083/4fd553e6-f50e-11e6-9b59-e51ec0e985ef.png)

Uncommenting `set LANG=C.utf8` is ineffective.
Uncommengint `chcp 65001` I get:
```
tessarotto@tessarotto01 ~
$ cat euro.txt
cat: write error: Permission denied
```

Any guess on how to find a solution?

### CMD.exe
It has to be noted that even the Windows cmd.exe behave weird.

#### CMD.exe alone
![3](https://cloud.githubusercontent.com/assets/152236/23064348/f89b7554-f50f-11e6-82ba-857b54714540.png)
#### CMD.exe on a fresh ConsoleZ instance
![4](https://cloud.githubusercontent.com/assets/152236/23064358/01083cea-f510-11e6-94be-2376e0316032.png)

**Comment by cbucher** [comment]
Concerning Windows console behaviour, you can see explanation here: #402

Astonishing, this is the same test file.

This strange Windows console behaviour occurs when Windows console font is `raster`.
you need a true type one to display Unicode chars.
Open the manual (press F1 in ConsoleZ) and follow instructions fromUsing ConsoleZ/Language settingssection.

![image](https://cloud.githubusercontent.com/assets/363759/23068129/a265062e-f522-11e6-8dcf-78d82fb8270c.png)

**Comment by Slamdunk** [comment]
> [...] Unhide windows console (View->Console window) and open its properties dialog. Go to "Font" tab. [...]

Awesome. Tricky, but awesome, everything works fine 👍 

Thank you for your patience and your complete documentation (that I missed, shame on me).

P.S.: the test file is (almost) the same because I spent the entire morning through issues and google 😝

**Comment by Slamdunk** [comment]
For the sake of completeness for future readers, in my example I could only see a portion of characters because, as the manual say:

> 4. You can now open ConsoleZ settings and choose whatever fixed-width font you like (**make sure it has characters you need** :-)

I was using an old version of a font I like.

After switching to [DejaVu fonts](https://en.wikipedia.org/wiki/DejaVu_fonts) (designed for Unicode support), everything prints flawlessly.
