### ISSUE TITLE
ConsoleZ won't run on Win10TP 32-bit

### ISSUE THREAD

**Issue by DerellLicht** [cbucher/console#421]
My system: Win10 Tech Preview 32-bit 
running in VirtualBox
ConsoleZ version: ConsoleZ.1.18.0.17048.7z

Extracted to a fresh c:\ConsoleZ subdirectory.
When I double-click on C:\consolez\Win32\Release\Console.exe
It displays a cascading sequence of error dialogs saying:

Unable to start c:\ConsoleZ\Console.exe
(reason: (CreateProcess)The system cannot find the file specified.)!

If I copy the contents of this directory into c:\ConsoleZ, I then get an infinite number of dialogs saying:
c:\ConsoleZ\Console.exe is not a Win32 console application!

I had previously had ConsoleZ (an earlier version) running on this machine, I don't know what changed??  Do I need to delete something from the registry?

**Comment by DerellLicht** [comment]
I searched through the registry and deleted one entry of c:\ConsoleZ\console.exe, that was only reference in the registry.  However, this issue still occurs.

Also, Windows updated itself to build 9200 (presumably, rc2), and this issue still occurs.

**Comment by cbucher** [comment]
>If I copy the contents of this directory into c:\ConsoleZ, I then get an infinite number of dialogs saying:
c:\ConsoleZ\Console.exe is not a Win32 console application!

It seems that you configured console.exe as shell...
Verify your settings file and your COMSPEC environment variable.

**Comment by DerellLicht** [comment]
hmmm... COMSPEC is:
c:\tccle13\tcc.exe

and there's no settings file (console.xml) at all... I wonder if it's in the user directories, somewhere??
I'm working from a clean copy of ConsoleZ, why would it not be creating its settings file?

**Comment by DerellLicht** [comment]
Whoops... after I started updating some settings, it went back to the infinite errors again!!
Now I'm getting an infinite number of errors:
c:\consolez\Win32\Release\Console.exe is not a Win32 console application!

It's also tying up 100% of CPU while doing this, so I can't even kill it from another window... damn...

**Comment by guillaume-uH57J9** [comment]
I have experience a very similar issue:

```
Unable to start y
(reason: (CreateProcess)The system cannot find the file specified.)!
```

ConsoleZ 1.18.0.17048
Windows 7 64-bit

Like @DerellLicht, clearing the Romaing directory solved the issue. 
I don't know what triggered this.

**Comment by cbucher** [comment]
Error message says you configured into shell settings the command line: `y`...

**Comment by guillaume-uH57J9** [comment]
That's odd, I haven't changed the shell command line, at least not intentionally. 

It'd be nice to improve the error message a bit, maybe add a button to open the preferences where this can be fixed ?

**Comment by cbucher** [comment]
Frankly I find the error message error pretty clear.
ConsoleZ starts in safe mode, then you can go in settings and fix your mistake.

**Comment by guillaume-uH57J9** [comment]
Startinc ConsoleZ in safe mode afterward would make sense.

However when this occured, ConsoleZ just showed the error but didn't start in safe mode. 
Does this mode activate itself upon error, or is there way to manually start the safe mode?

**Comment by cbucher** [comment]
Since 1.17.1 version, a safe mode shell is automatically launched when no shells can be started.
