### ISSUE TITLE
alt+space doesn't display the window menu

### ISSUE THREAD

**Issue by kasajian** [cbucher/console#423]
I would like to request that the Alt+Space menu item be enable.   It's the only consistent way that one can minimize a window while using any application.  I could be in a browser, notepad, excel, etc., and simply type Alt+Space, N, and the window will be minimized.   This feature has been in Windows for decades, but some reason (probably a good reason I don't understand) Console2 and ConsoleZ have this disabled.

**Comment by cbucher** [comment]
This is not a feature, this a bug.
I never used this keyboard shortcut.
First look at the issue: I don't receive WM_SYSKEYDOWN with VK_SPACE, but
WM_SYSKEYDOWN with VK_MENU (v alt)
WM_KEYDOWN VK_SPACE (v SPACEBAR)
WM_KEYUP VK_SPACE (^ SPACEBAR)
WM_SYSKEYUP with VK_SPACE (^alt)

**Comment by cbucher** [comment]
There are two bugs. I fixed the bug in my code : ConsoleZ works like Console2.
But there is a bug into WTL: if you press ALT and hide the menu, then ALT+SPACE is no longer working.

**Comment by cbucher** [comment]
@kasajian Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by cbucher** [comment]
There is a bug into modified code: double chars in vim.

**Comment by cbucher** [comment]
@kasajian Please, try last (pre)release version.
