### ISSUE TITLE
Settings directory created even if "Save settings to user directory" setting is unchecked

### ISSUE THREAD

**Issue by thdoan** [cbucher/console#425]
### Expected Behavior
When "Save settings to user directory" setting is unchecked, no directory should be created in user directory.

### Actual Behavior
Empty `Console` directory is created in `C:\Users\%username%\AppData\Roaming`

### Steps to reproduce
1. Uncheck "Save settings to user directory"
2. Restart ConsoleZ

**Comment by cbucher** [comment]
Yes the directory is created...
I do not see why this poses any problem.

**Comment by thdoan** [comment]
Because when you use it as a portable app and unplug the USB stick, you don't want any trace of the app left on the  host  PC.

**Comment by cbucher** [comment]
@thdoan Please, try last experimental version.

https://github.com/cbucher/console/wiki/Downloads

**Comment by thdoan** [comment]
@cbucher I'm using Windows 7 Pro 64-bit. When I unzipped ConsoleZ.x64.1.18.2.17170.zip and double-clicked on Console.exe I got this error:

![image](https://user-images.githubusercontent.com/4110567/27364139-42521b14-566b-11e7-8e5c-83647652492e.png)

Here are the dump files:
https://drive.google.com/open?id=0B9BRpv2uOex3azU1TUJNeHFPRUE

**Comment by cbucher** [comment]
@thdoan Bug has been fixed in a new version.

**Comment by thdoan** [comment]
@cbucher Thanks, I can confirm that this bug is now fixed. Thanks for making ConsoleZ truly leave-no-trace portable :+1:

**Comment by cbucher** [comment]
thx
