### ISSUE TITLE
"Switch On/Off Transparency" state is not saved

### ISSUE THREAD

**Issue by thdoan** [cbucher/console#426]
### Expected Behavior
The "Switch On/Off Transparency" state (checked/unchecked) should be saved when you exit.

### Actual Behavior
The "Switch On/Off Transparency" state is not saved (it is always checked).

### Steps to reproduce
1. Toggle the View / Switch On/Off Transparency option
2. Restart ConsoleZ

**Comment by cbucher** [comment]
This feature has never been suggested...
You can contribute by doing a specification or a pull request.
Consider that transparency settings can be different in full screen or windowed mode.

**Comment by cbucher** [comment]
@thdoan Please, try last experimental version.

https://github.com/cbucher/console/wiki/Downloads

**Comment by thdoan** [comment]
@cbucher I just verified the fix -- thanks! One suggestion though: it is ambiguous what the checkmark means because the label reads "Switch **On/Off** Transparency". To make it very clear, you can rename this label to read "Enable Transparency" or something similar.

**Comment by cbucher** [comment]
"Switch On/Off Transparency": I agree.
"Enable Transparency" is a good choice.

**Comment by cbucher** [comment]
1.18.2.17272 version has been released
