### ISSUE TITLE
Mouse hotkey label has incorrect order

### ISSUE THREAD

**Issue by thdoan** [cbucher/console#428]
### Expected Behavior
Under the "Mouse action" column, the modifier should be listed first (e.g., **Alt + Left**).  This is consistent with Windows conventions and is also easier to read (e.g., hold down `Alt`, then click Left).

### Actual Behavior
The modifier is listed second (e.g.,  **Left + Alt**).

**Comment by cbucher** [comment]
@thdoan Please, try last (pre)release version.

**Comment by thdoan** [comment]
Thanks, I appreciate the quick patch :+1:
