### ISSUE TITLE
Path error when restoring workspace

### ISSUE THREAD

**Issue by thdoan** [cbucher/console#429]
### Expected Behavior
When restoring a workspace, every tab should be restored without errors regardless of what directory you change to.

### Actual Behavior
The workspace isn't restored properly if you change directory inside the batch file passed to `cmd.exe` -- I am getting this error:

![image](https://cloud.githubusercontent.com/assets/4110567/24293833/9d0a0874-10ce-11e7-818d-87e51bb4743f.png)

### Steps to reproduce
1. Create a file called `C:\ConsoleZ\start.bat` with this code:

```
@echo off
cd \
```

2. Enter `%ComSpec% /k "start.bat"` for the Shell:

![image](https://cloud.githubusercontent.com/assets/4110567/24293687/026ee028-10ce-11e7-970f-e04edcd1cd2a.png)

3. Verify that it works by selecting File / New Tab / ConsoleZ. You should be at the root directory.
4. Ensure the Close/Detach settings are like this:

![image](https://cloud.githubusercontent.com/assets/4110567/24293235/b2f1c6d4-10cb-11e7-8456-b277b0a309f1.png)

5. Restart ConsoleZ. When the workspace is restored, you will get the error as seen above.

One way to prevent this is to expose a variable pointing to where ConsoleZ is located, similar to ConEmu's `%ConEmuBaseDir%`. This way you can specify the shell as `%ComSpec% /k "%ConsoleZBaseDir%\start.bat"`.

**Comment by cbucher** [comment]
Yes, you **have to** use an **absolute path**
When you save a workspace, for each console, current directory is saved.
When you load a workspace, for each console, saved directory is used as startup directory.

**Comment by thdoan** [comment]
@cbucher is there a variable similar to `%ConEmuBaseDir%` that we can use? I plan to have a `scripts` directory under the ConsoleZ directory and would prefer to keep things relative to the ConsoleZ directory instead of using absolute paths.

**Comment by cbucher** [comment]
You named it: `ConsoleZBaseDir`.
ConsoleZ specific environment variables:
```
ConsoleZBaseDir
ConsoleZSettingsDir
ConsoleZSnippetsDir
ConsoleZVersion
```

**Comment by thdoan** [comment]
That's great, thanks!
