### ISSUE TITLE
Clicking on icon in tray transfers mouse pointer over the console window

### ISSUE THREAD

**Issue by MarcinOrlowski** [cbucher/console#431]
Clicking on ConsoleZ's icon in tray transfers mouse pointer over the console window. While this thing is here for while I see no option to disable it - hence the bug report. Can this be made configurable please?

**Comment by MarcinOrlowski** [comment]
This is pretty annoying thing  so kind bump in hope to have it not configurable (I just want it off, but **maybe** someone finds that useful :), so at least half-baked ini entry I can set by hand whatever?.

**Comment by cbucher** [comment]
@MarcinOrlowski Please try last experimental version.
https://dl.bintray.com/cbucher/ConsoleZ/1.18.2.17128/

**Comment by MarcinOrlowski** [comment]
Seems to work perfect. Thank you.

**Comment by cbucher** [comment]
thx
