### ISSUE TITLE
FRE: Option to hide tab number from tab title

### ISSUE THREAD

**Issue by MarcinOrlowski** [cbucher/console#433]
It'd be useful to have option to hide tab numbers from tabs to make them take less space (width) thus fitting more of them in a window width

**Comment by DerellLicht** [comment]
That's already doable - in fact, I have the tab number removed from all of my tabs.
Under ConsoleZ Settings: Appearance: Tab format:
just remove the code that represents tab number.  I don't exactly recall which code that is, but I use this:
?A([%D] ):(%D)
Which displays just the current directory-leaf name and nothing else; if it's an Admin shell, then the name is in square braces.  No tab numbers are present.
I'll try to attach a screen shot of my tabs, for your reference.
I'm using version 1.18.0, dated 14 Dec 2016

Derell Licht
![consolez tabs](https://cloud.githubusercontent.com/assets/5551606/24984444/4bfcb39a-1fa2-11e7-9102-f9df34844593.jpg)

**Comment by MarcinOrlowski** [comment]
Thanks for the hint. Problem solved :)
