### ISSUE TITLE
Add built-in environment variable

### ISSUE THREAD

**Issue by QiWei** [cbucher/console#436]
Thanks for great product.
Could you add  few predefined environment variables, example: 
%CONSOLEZ_ARCH% 32 or 64 -  ConsoleZ architecture.
%CONSOLEZ_PATH%
%CONSOLEZ_DRIVE%
%CONSOLEZ_ISADMIN% or %PROCESS_RUNASADMIN% can be either 0 or 1, if process is executed with elevated privileges.
%CONSOLEZ_PID%

**Comment by cbucher** [comment]
Hi,

> %CONSOLEZ_ARCH%

ok
Remark: `console.exe` must be 32 bits on 32 bits OS and 64 bits on 64 bits OS. You don't have choice.

> %CONSOLEZ_PATH%
> %CONSOLEZ_DRIVE%

`ConsoleZBaseDir`variable already exists.
Is not it redundant?

> %CONSOLEZ_ISADMIN% or %PROCESS_RUNASADMIN% can be either 0 or 1, if process is executed with elevated privileges.

Is the process console.exe or started shell?

> %CONSOLEZ_PID%

Is the process console.exe or started shell?

Regards

**Comment by artie-finkelstein** [comment]
At one time I thought I needed the PID of the current shell, found a nice routine on DOSTIPS.com, reworked it a bit, and have never needed it since.  But in case QiWei or someone else does: see dbenham post on 23 December 2014 at http://www.dostips.com/forum/viewtopic.php?t=6133&start=30

**Comment by QiWei** [comment]
%CONSOLEZ_ARCH% is ConsoleZ  architecture self.
ConsoleZ.x64 is 64, ConsoleZ.x86 is 32.
c code:
```
#if _WIN32 || _WIN64
#if _WIN64
#define ENV64BIT
#else
#define ENV32BIT
#endif
#endif

int exeBit;
#if defined(ENV64BIT) || defined(__x86_64__) || defined(_M_X64)
	/* x86 64-bit ----------------------------------------------- */
	exeBit = 64;
#elif defined(ENV64BIT) || defined(__i386) || defined(_M_IX86)
	/* x86 32-bit ----------------------------------------------- */
	exeBit = 32;
#else
	if (sizeof(void*) == 8) {
		exeBit = 64;
	} else if (sizeof(void*) == 4) {
		exeBit = 32;
	} else {
		exeBit = 0;
	}
#endif
```

**Comment by QiWei** [comment]
%CONSOLEZ_PATH% is redundant.
%CONSOLEZ_DRIVE% is not redundant, example:
I want set environment variable in tabs, like:
`LIBPATH=%CONSOLEZ_DRIVE%\VS2013\LIB\%CONSOLEZ_ARCH%;%LIBPATH%`

**Comment by QiWei** [comment]
%CONSOLEZ_ISADMIN% or %PROCESS_RUNASADMIN% is the process console.exe, started shell  inherited from console.exe

**Comment by artie-finkelstein** [comment]
FWIW:

When I need to make architecture decisions, I use:
    :: clink -- get effective bitness using processor architecture
    for /f "delims=AMDx" %%A in ("%PROCESSOR_ARCHITECTURE%") do set "TARGET=%~dp0clink_x%%A.exe"

I have also used:
    :: clink -- get effective bitness using CMD pseudo environment 
    set "TARGET=%~dp0clink_x64.exe"
    if exist %windir%\sysnative\* set "TARGET=%~dp0clink_x86.exe"
    
Both versions work well, but I prefer the single line of the former version, and I have the uneasy 
feeling that relying on the knowledge of 'sysnative' is "not a good thing".


I don't have anything for ISADMIN/RUNASADMIN as I don't ever not run as Admin 
(after all it's MY computer).

**Comment by cbucher** [comment]
>%CONSOLEZ_ISADMIN% or %PROCESS_RUNASADMIN% is the process console.exe, started shell  inherited from console.exe

Started shell doesn't always inherit console.exe elevation type.
- you can run the shell as administrator
- you can run the shell as another user
- shell can use a manifest in which a different behavior is defined (https://msdn.microsoft.com/en-us/library/windows/desktop/bb756929.aspx)

> %CONSOLEZ_PID%

You want the PID of console.exe instance or the PID of the started shell?
What is the purpose of this information?

**Comment by QiWei** [comment]
When started shell does not inherited from console.exe， environment variables will not inherit console.exe.

%CONSOLEZ_PID% is not important, i think this variable  is dispensable.
It might be unuseful to me.

**Comment by cbucher** [comment]
There is no relevant or valid environment variable in this request.
