### ISSUE TITLE
Starting large ConsoleZ does not use whole window b/c windows console has fewer rows.

### ISSUE THREAD

**Issue by sweavo** [cbucher/console#437]
Can you reproduce this issue in the original shell without using ConsoleZ?  No
Before continuing please check to see if the issue occurs in the latest version (experimental, beta, or release) available here: Yes in ConsoleZ.x64.1.18.1.17080.zip
Lastly, please search for an existing issue before opening a new one: Done.

### Expected Behavior
What you expect to happen.

I expect consolez to use the whole of the screen before scrolling.

### Actual Behavior
What actually happens.

My bash prompt appears approx 2/3 of the way down the screen and the bottom 1/3 is never used but consolez scrolls instead. 

If I view the Windwos Console, it appears to be roughly the height of my landscape monitor, though it's displayed on my portrait one. I can resize or maximize it and I can seemingly change the defaults to persuade it to be larger, but the changes do not stick and the problem reoccurs.

### Steps to reproduce

(Windows 7 64-bit. )

I have two monitors. Monitor set to be main monitor (Monitor2) is landscape. Secondary monitor (Monitor1) is portrait. ConsoleZ is set to open fullscreen on the portrait monitor.  It starts msys bash and I cat a 1000 line file. 

### Diagnostic Report
`ConsoleZ aero amd64 1.18.1.17080 beta1
Windows 7 Service Pack 1 (64 bits) [6.1.7601]
is elevated? no
UAC prefix "Administrator: "
Tab (active): Main
  View (active): 1. Main
  is elevated? no
  input code page 850
  output code page 850
  Windows console font
font index: 0
face name: 
font familly: 48 MODERN
font weight: 400
font size: width=10 height=20
max window size: cols=105 rows=56
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 2
+ Flags 0
  DeviceID \\?\DISPLAY#NEC68D7#5&3711523&0&UID5243153#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0005
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (1920,-225)x(3000,1695)
  Work (1920,-225)x(3000,1695)
  DPI (per monitor: no)
+ Flags 1  primary
  DeviceID \\?\DISPLAY#NEC68D5#5&3711523&0&UID5243152#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
  DeviceName \\.\DISPLAY2\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (0,0)x(1920,1200)
  Work (0,0)x(1920,1152)
  DPI (per monitor: no)
System dpi 120
System metrics
  SM_CXSMICON        20
  SM_CYSMICON        20
  SM_CXICON          40
  SM_CYICON          40
  SM_CXVIRTUALSCREEN 3000
  SM_CYVIRTUALSCREEN 1920
  SM_CYVIRTUALSCREEN 1920
Settings file C:\Users\crs1yok\AppData\Roaming\Console\console.xml
<?xml version="1.0"?>
<settings lang="auto" icon_size="0">
	<console change_refresh="10" refresh="100" rows="200" columns="80" buffer_rows="10000" buffer_columns="0" shell="#~" init_dir="" start_hidden="0" save_size="0" background_text_opacity="255">
		<colors background_text_opacity="255">
			<color id="0" r="0" g="0" b="0"/>
			<color id="1" r="0" g="0" b="128"/>
			<color id="2" r="0" g="150" b="0"/>
			<color id="3" r="0" g="150" b="150"/>
			<color id="4" r="170" g="25" b="25"/>
			<color id="5" r="128" g="0" b="128"/>
			<color id="6" r="128" g="128" b="0"/>
			<color id="7" r="192" g="192" b="192"/>
			<color id="8" r="128" g="128" b="128"/>
			<color id="9" r="0" g="100" b="255"/>
			<color id="10" r="0" g="255" b="0"/>
			<color id="11" r="0" g="255" b="255"/>
			<color id="12" r="255" g="50" b="50"/>
			<color id="13" r="255" g="0" b="255"/>
			<color id="14" r="255" g="255" b="0"/>
			<color id="15" r="255" g="255" b="255"/>
		</colors>
		<cursor style="0" r="255" g="255" b="255"/>
		<background type="0" r="0" g="0" b="0">
			<image file="" relative="0" extend="0" position="0">
				<tint opacity="0" r="0" g="0" b="0"/>
			</image>
		</background>
	</console>
	<appearance>
		<font name="DejaVu Sans Mono" size="10" bold="0" italic="0" smoothing="3" bold_intensified="0" italic_intensified="1" extra_width="0" ligature="1">
			<color use="0" r="0" g="0" b="0"/>
		</font>
		<window title="ConsoleZ" icon="" use_tab_icon="1" use_console_title="0" show_cmd="1" show_cmd_tabs="1" use_tab_title="1" trim_tab_titles="20" trim_tab_titles_right="0" main_title_format="?U([%u] )?N({%u} )%m?s( - %s)" tab_title_format="%n. ?U([%u] )?N({%u} )%t?s( - %s)"/>
		<controls show_menu="0" show_toolbar="0" show_statusbar="0" show_tabs="0" hide_single_tab="1" show_scrollbars="1" flat_scrollbars="1" tabs_on_bottom="0" hide_tab_icons="0" show_searchbar="0" hide_tab_close_button="0"/>
		<styles caption="1" resizable="1" taskbar_button="1" border="1" inside_border="2" tray_icon="0" quake_like="0" jumplist="0" integrated_ime="0" quake_animation_time="300" hide_when_inactive="0" split_bar_size="0" per_monitor_dpi="0" keep_view_theme="0">
			<selection_color r="255" g="255" b="255"/>
			<highlight_color r="191" g="191" b="191"/></styles>
		<position x="2190" y="-225" dock="4" snap="-1" z_order="0" save_position="1" w="540" h="1920" save_size="1" save_state="1" state="3"/>
		<transparency type="0" active_alpha="255" inactive_alpha="199" r="192" g="192" b="192"/>
		<fullscreen start_in_fullscreen="1" fullscreen_monitor="1">
			<controls show_menu="0" show_toolbar="0" show_searchbar="0" show_statusbar="0" show_tabs="1" hide_single_tab="1" tabs_on_bottom="0" hide_tab_icons="0" hide_tab_close_button="0" show_scrollbars="1"/>
			<transparency type="0" active_alpha="255" inactive_alpha="199" r="192" g="192" b="192"/></fullscreen>
	</appearance>
	<behavior>
		<copy_paste copy_on_select="1" clear_on_copy="1" no_wrap="1" trim_spaces="1" copy_newline_char="0" sensitive_copy="1" include_left_delimiter="0" include_right_delimiter="0" left_delimiters=" ([" right_delimiters=" )]" eol_spaces="1" rtf="0"/>
		<scroll page_scroll_rows="0"/>
		<tab_highlight flashes="3" stay_highligted="1"/>
		<close allow_closing_last_view="0" confirm_closing_multiple_views="1" exit_on_closing_of_last_tab="1" save_workspace_on_exit="0"/>
		<focus follow_mouse="1"/>
		<instance allow_multi="0"/>
		<clone use_current_dir="0"/>
		<search match_case="0" match_whole_word="0"/>
		<runas use_credprov="1"/>
		<environment inherit="1" sync="1"/></behavior>
	<hotkeys use_scroll_lock="1">
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="118" command="settings"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="112" command="help"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="0" code="115" command="exit"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="112" command="newtab1"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="113" command="newtab2"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="114" command="newtab3"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="115" command="newtab4"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="newtab5"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="117" command="newtab6"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="118" command="newtab7"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="119" command="newtab8"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="120" command="newtab9"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="121" command="newtab10"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="122" command="newtab11"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="123" command="newtab12"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="49" command="switchtab1"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="50" command="switchtab2"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="51" command="switchtab3"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="52" command="switchtab4"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="53" command="switchtab5"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="54" command="switchtab6"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="55" command="switchtab7"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="56" command="switchtab8"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="57" command="switchtab9"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="48" command="switchtab10"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtab11"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtab12"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="9" command="nexttab"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="9" command="prevtab"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="movetableft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="movetabright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="closetab"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="113" command="renametab"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="34" command="nextview"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="33" command="prevview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="37" command="leftview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="39" command="rightview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="38" command="topview"/>
		<hotkey ctrl="0" shift="0" alt="1" extended="1" code="40" command="bottomview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="dechsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="inchsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="decvsize"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="incvsize"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="87" command="closeview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="detachview"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="attach"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="220" command="splithoriz"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="220" command="splitvert"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="splitswap"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clone"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="122" command="fullscreen"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="96" command="zoom100"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="107" command="zoominc"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="0" code="109" command="zoomdec"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="groupall"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="ungroupall"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="grouptab"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="ungrouptab"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="clear"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="45" command="copy"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="selectall"/>
		<hotkey ctrl="1" shift="0" alt="0" extended="1" code="46" command="clear_selection"/>
		<hotkey ctrl="0" shift="1" alt="0" extended="1" code="45" command="paste"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="paste_selection"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="stopscroll"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="resumescroll"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textseltop"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselbottom"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselhome"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselend"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselpageup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="textselpagedown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colseltop"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselbottom"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselhome"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselend"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselpageup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="colselpagedown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollrowdown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageup"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpagedown"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollcolright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageleft"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="scrollpageright"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="find"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findnext"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="findprev"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="switchtransparency"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="alwaysontop"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="112" command="dumpbuffer"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu1"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu2"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdMenu3"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="cmdSnippets"/>
		<hotkey ctrl="1" shift="1" alt="0" extended="0" code="67" command="ctrlC"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="wspload"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="wspsave"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="fwdmouse"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd1"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd2"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd3"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd4"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd5"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd6"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd7"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd8"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd9"/>
		<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd10"/>
		<hotkey ctrl="1" shift="0" alt="1" extended="0" code="90" command="activate" win="0"/>
	</hotkeys>
	<mouse>
		<actions>
			<action ctrl="0" shift="0" alt="0" button="1" name="copy"/>
			<action ctrl="0" shift="1" alt="0" button="1" name="select"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="select_column"/>
			<action ctrl="0" shift="0" alt="0" button="3" name="paste"/>
			<action ctrl="1" shift="0" alt="0" button="1" name="drag"/>
			<action ctrl="0" shift="0" alt="0" button="4" name="link"/>
			<action ctrl="0" shift="0" alt="0" button="2" name="menu"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="menu2"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="menu3"/>
			<action ctrl="0" shift="0" alt="0" button="0" name="snippets"/>
		</actions>
	</mouse>
	<tabs>
		<tab title="Main" use_default_icon="0">
			<console shell="C:\MinGW\msys\1.0\bin\bash.exe --login" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
		</tab>
		<tab title="Side Task" use_default_icon="0">
			<console shell="C:\MinGW\msys\1.0\bin\bash.exe --login" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
			<background type="0" r="2" g="7" b="40">
				<image file="" relative="0" extend="0" position="0">
					<tint opacity="0" r="0" g="0" b="0"/>
				</image>
			</background>
		</tab>
		<tab title="WIP=3!" use_default_icon="0">
			<console shell="C:\MinGW\msys\1.0\bin\bash.exe --login" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
			<background type="0" r="43" g="0" b="0">
				<image file="" relative="0" extend="0" position="0">
					<tint opacity="0" r="0" g="0" b="0"/>
				</image>
			</background>
		</tab>
		<tab title="Support" use_default_icon="0">
			<console shell="C:\MinGW\msys\1.0\bin\bash.exe --login" init_dir="" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
			<background type="0" r="5" g="43" b="0">
				<image file="" relative="0" extend="0" position="0">
					<tint opacity="0" r="0" g="0" b="0"/>
				</image>
			</background>
		</tab>
	</tabs>
	<external_commands>
	</external_commands>
	<snippets dir=""/></settings>`

### Crash Report
N/A

**Comment by cbucher** [comment]
Please read FAQ: https://github.com/cbucher/console/wiki/FAQ#why-am-i-limited-in-number-of-rowcolumn

>  Windows console font
font index: 0
face name: 
font familly: 48 MODERN
font weight: 400
font size: width=10 height=20
max window size: cols=105 rows=56

You can see, in your diagnostc report, max widow size limited by a big font size.

Duplicate (See #275, #203, #173...)

**Comment by sweavo** [comment]
Thanks, appreciate the quick response.
I've added "Read the FAQ" to the wiki page that is referenced when you create an issue to try to reduce how often this issue gets duplicates raised.

**Comment by draenor** [comment]
Smaller font-size only uses the the already usable portion of the screen more effectively so it's not a great workaround. Consequently half my screen is still left unusable. 

The code is this: https://github.com/cbucher/console/blob/master/ConsoleHook/ConsoleHandler.cpp

```
COORD coordMaxSize = ::GetLargestConsoleWindowSize(hStdOut);
m_consoleParams->dwMaxRows		= coordMaxSize.Y;
m_consoleParams->dwMaxColumns	= coordMaxSize.X;
```

How about adding a checkbox to the configuration to ignore above check and force the columns/rows to remain constant per the already present row/column setting?

**Comment by cbucher** [comment]
I don't understand.
What do you expect by ignoring this check?

GetLargestConsoleWindowSize returns max rows/columns (computed by Windows from console font and primary monitor sizes).
If you try a value greater than max, max is used.

**Comment by draenor** [comment]
As I understand it max rows/columns consoleZ will use is based on `GetLargestConsoleWindowSize` which  may result in fewer rows/columns than than there is space for on the screen under certain circumstances. If I know my screen can fit 30 rows but `GetLargestConsoleWindowSize` only reports 20 then it would be nice if I could override that value. 

Does that make sense?

**Comment by cbucher** [comment]
Largest console size is returned by WIN32 API GetLargestConsoleWindowSize.
If you want a larger console: you need to reduce the console font size so GetLargestConsoleWindowSize will return a larger size.
Windows limits console size (this limit is returned by GetLargestConsoleWindowSize).

**Comment by draenor** [comment]
Aha ok I get it, so even if consoleZ were to set `30` rows and `GetLargestConsoleWindowSize` returns `20` then only `20` would be visible regardless. Thanks for the clarification
