### ISSUE TITLE
Forward Mouse Events and Mouse copy

### ISSUE THREAD

**Issue by hyee** [cbucher/console#440]
Hello,

If I enable the "Forward Mouse Event" option, then I cannot use mouse to select and copy text,  is there any option to bypass the fowarding when the select/copy behaviour happens? Thanks

**Comment by cbucher** [comment]
hello

>If I enable the "Forward Mouse Event" option, then I cannot use mouse to select and copy text

This is the meaning of this option.

When "Forward Mouse Event" option is disabled, only mouse events that are not configured as mouse actions  (see Settings/Hotkeys/Mouse) are forwarded.

When "Forward Mouse Event" option is enabled, all mouse events are forwarded (mouse actions are ignored).

**Comment by hyee** [comment]
Understood, thanks.
