### ISSUE TITLE
How to start new tab with pre-specified cmd ?

### ISSUE THREAD

**Issue by 4r7w0rk** [cbucher/console#441]
Hello !

Is it possible to launch a new tab with a pre-specified cmd?
For example, i'd like to launch tab with the cmd Ping pre-specified.
Then i just have to copy / past the IP

Thanks ! #

**Comment by cbucher** [comment]
Yes it is.
![image](https://user-images.githubusercontent.com/363759/27726982-ee31c5c0-5d7c-11e7-92b7-db2a8d00806b.png)

**Comment by cbucher** [comment]
how to avoid cmd will be closed after a batch was executed?
use `cmd.exe /K`
