### ISSUE TITLE
Unable to send CTRL+a followed by a character

### ISSUE THREAD

**Issue by richard-scott** [cbucher/console#444]
### Expected Behavior
When using 'screen' in BashOnWindows you type CTRL+a then a letter to do something e.g. c to create a new window, or d to detatch. This works fine in BashOnWindows, and works ok in [ConEmu](https://conemu.github.io/)

### Actual Behavior
The CTRL+a part doesn't seem to get sent, only the final letter appears on the command line.

### Steps to reproduce
1. Log into a Linux box and start running screen.
2. Now try and send screen some control commands.

I am unable to unmap the CTRL+A Hotkey which is set in the Edit menu for Select All.

**Comment by richard-scott** [comment]
I've just found #356 and wanted to say that this is not the same issue here. I'm not running screen on my local system. I use Bash.exe to SSH to a remote box and then run screen there.

Also, for reference CTRL+a,c and CTRL+a,d work fine directly with Cygwin's terminal runing screen on a local system as I've juste tested it right now troubleshooting this issue.

**Comment by cbucher** [comment]
>I am unable to unmap the CTRL+A Hotkey which is set in the Edit menu for Select All.

![image](https://user-images.githubusercontent.com/363759/28338763-44fdbdbe-6c0a-11e7-8e57-319c24ef20e5.png)

**Comment by richard-scott** [comment]
LMAO... what a strange way to do it in a two step process. You'd have thought clicking _Clear_ and clicking _OK_ would be enough. An unintuative way but it all works now thanks.

**Comment by richard-scott** [comment]
Actually cancel that, it still doesn't work ;-(
