### ISSUE TITLE
Infinite Error Window Loop

### ISSUE THREAD

**Issue by velu76** [cbucher/console#445]
**In SETTINGS under Console**
Configuring the "Shell" to point back to the same ConsoleZ exe file causes an infinite number of error windows to pop up and crashing windows. 

The user should be prevented from setting the Shell as the same "ConsoleZ" application.

**Comment by cbucher** [comment]
I can detect if console.exe process is launched with injection.
That will detect if console.exe has been configured in tab settings (including environment variable like ComSpec).
But I have no simple solution if console.exe is called from a script.
For example in a bat file : ConsoleZ will launch cmd.exe, cmd.exe will launch console.exe, console.exe will launch cmd.exe, cmd.exe will launch console.exe ...

**Comment by cbucher** [comment]
1.18.2.17272 version has been released
