### ISSUE TITLE
Arrows don't work when using Bash on Ubuntu for Windows.

### ISSUE THREAD

**Issue by ichenfeng** [cbucher/console#447]
My system is Windows 10.
When I start Bash on Windows in consoleZ, Arrows don't work so that I can't using history command by Arrows.
I test bash started from PowerShell Terminator, in this case Arrows worked.

**Comment by cbucher** [comment]
duplicate #335 
If you really want a fix, please comment here: https://github.com/Microsoft/BashOnWindows/issues/111
