### ISSUE TITLE
FRE: Ability to maximize a view

### ISSUE THREAD

**Issue by rshivane** [cbucher/console#451]
My typically work setup: one consoleZ window fully maximized  per screen, with multiple split views within the window. This works great.

There are however times when I would like to maximize a view temporarily, finish some bit of work and then come back to the split view. 

To achieve this, I tried detaching the view, maximizing it and then attaching it back. But looks like attaching back is not possible as discussed in #244 

Is it possible to add the ability to maximize and restore a view?

**Comment by cbucher** [comment]
This feature request resembles this one: #221. That's right ?

**Comment by rshivane** [comment]
Yes, it is a duplicate of #221 
Closing this
Thanks
