### ISSUE TITLE
Hotkeys: External Command cleared upon restart

### ISSUE THREAD

**Issue by cruzzer** [cbucher/console#452]
### Expected Behavior
When storing an External command under hotkeys, it should survive upon reboot. 

### Actual Behavior
The hotkey (e.g. ctrl+n) is kept, put the actual command (e.g. calc) is not, it becomes empty. This results in error:  "Unable to start (reason:(CreateProcess) The parameter is incorrect.)) when using the hotkey.

Right after the command is stored it works, but is cleared once restarting the program. This used to work a long time ago.

### Steps to reproduce
1. Store hotkey
Settings>Hotkeys>External command 1:
Command=calc; hotkey=ctrl+n;
[assign]

2. Test hotkey working
[ctrl+n] (works)

3. Close ConsoleZ
4. Start ConsoleZ
5. Test hotkey
[ctrl+n] (fails)
  

### Diagnostic Report
ConsoleZ aero amd64 1.18.1.17087
Windows 10 (64 bits) [10.0.10586]
is elevated? no
UAC prefix "Administrator: "
Tab (active): Bash
  View (active): 1. Bash - ~
  is elevated? no
  input code page 437
  output code page 437
  Windows console font
font index: 8
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=16
max window size: cols=80 rows=95
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 3
+ Flags 0
  DeviceID \\?\DISPLAY#ACI22A2#5&114bebc9&0&UID268#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0003
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (2560,537)x(4240,1587)
  Work (2560,537)x(4240,1587)
  DPI (per monitor: yes) X=96 Y=96
+ Flags 1  primary
  DeviceID \\?\DISPLAY#HWP2690#5&114bebc9&0&UID269#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0004
  DeviceName \\.\DISPLAY2\Monitor0
  DeviceString HP LP3065 Wide LCD Monitor
  StateFlags 3
  Rect (0,0)x(2560,1600)
  Work (0,0)x(2560,1560)
  DPI (per monitor: yes) X=96 Y=96
+ Flags 0
  DeviceID \\?\DISPLAY#ACI22A2#5&114bebc9&0&UID13762560#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d36e96e-e325-11ce-bfc1-08002be10318}\0006
  DeviceName \\.\DISPLAY3\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (-1680,522)x(0,1572)
  Work (-1680,522)x(0,1572)
  DPI (per monitor: yes) X=96 Y=96
System dpi 96
System metrics
  SM_CXSMICON        16
  SM_CYSMICON        16
  SM_CXICON          32
  SM_CYICON          32
  SM_CXVIRTUALSCREEN 5920
  SM_CYVIRTUALSCREEN 1600
  SM_CYVIRTUALSCREEN 1600

```
<hotkey ctrl="1" shift="0" alt="0" extended="0" code="78" command="externalcmd1"/>
<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd2"/>
<hotkey ctrl="0" shift="0" alt="0" extended="0" code="0" command="externalcmd3"/>
```

**Comment by cbucher** [comment]
I reproduce this issue.

**Comment by cruzzer** [comment]
Cool, thanks

**Comment by cbucher** [comment]
Please, try pre-release version https://github.com/cbucher/console/releases/tag/1.18.2

**Comment by cruzzer** [comment]
Yes, it is fixed.

Merci
