### ISSUE TITLE
Get-Credential throws "Access Denied" when ConsoleZ is in Quake-style mode

### ISSUE THREAD

**Issue by PDunbarCGI** [cbucher/console#454]
### Expected Behavior
When running Get-Credential, a graphical prompt for user/password displayed.

### Actual Behavior
PS C:\Users\PDUNBAR\Applications\ConsoleZ> Get-Credential

cmdlet Get-Credential at command pipeline position 1
Supply values for the following parameters:
Credential
Access is denied
At line:1 char:1
+ Get-Credential
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception

### Steps to reproduce
1) Enable Quake-style (dock top-middle, always on top)
2) Run Get-Credential
3) Observe error above

### Diagnostic Report
```
[dmpD154.tmp.txt](https://github.com/cbucher/console/files/1352657/dmpD154.tmp.txt)

**Comment by cbucher** [comment]
Sorry I cannot reproduce your issue.
I don't think your problem is caused by ConsoleZ.
Are-you really sure you cannot reproduce your issue without ConsoleZ?

**Comment by PDunbarCGI** [comment]
![image](https://user-images.githubusercontent.com/29259522/31203526-2335a61e-a92d-11e7-84d5-d562a311ff4f.png)
The first time I ran Get-Credential, it was normally.  The second time I ran it, it was with the Console Window opened.

**Comment by cbucher** [comment]
By "normally", you mean "I have the issue" (aka the red error) ?

As you can see with your settings file and Windows 7, I don't reproduce your issue.
![image](https://user-images.githubusercontent.com/363759/31306805-c58e93ae-ab57-11e7-9961-b55e2bcd83ff.png)

**Comment by cbucher** [comment]
What are your UAC settings?
Try to disable antiviral software.

**Comment by PDunbarCGI** [comment]
By this, I meant "it was what I normally see" (the error in red).
> The first time I ran Get-Credential, it was normally.

UAC Settings are here:
![image](https://user-images.githubusercontent.com/29259522/31672822-28219804-b323-11e7-9eb8-2233e1c60c1c.png)

I'm not able to disable AV, I'm afraid.  

I see nothing in the Application, System or Security event log.

**Comment by cbucher** [comment]
Can you capture a trace with procmon?
Select "All events" when you save to file.
