### ISSUE TITLE
ConsoleZ is crashed in win10 v10.0.17035

### ISSUE THREAD

**Issue by hyee** [cbucher/console#458]
Previously my win10 version is 16xxx, after upgrading to 17035,  even a fresh ConsoleZ application without any settings, sometimes it crashes just after starting, I'm not sure if the OS upgrade could cause  such  issue, or just the unexpected OS configurations.

I can 100% recur the crash issue by typing `type ansi.txt` in cmd window from ConsoleZ, or if I integrate it with my  java console-base program, it also crashes and I could see below message from the `Diagnose` result:
```
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.
```

Please refer to the attachment for the crash dump,diagnose result and `ansi.txt` for your reference, thanks.
[conhost.exe.8088.zip](https://github.com/cbucher/console/files/1491074/conhost.exe.8088.zip)

**Comment by cbucher** [comment]
it is conhost.exe process that crashes.

I don't understand what "or if I integrate it with my java console-base program" means.

Can you reproduce Windows console crash without ConsoleZ?

**Comment by hyee** [comment]
Without ConsoleZ everything works well, and before the upgrade ConsoleZ also works well.

**Comment by cbucher** [comment]
As insider tester, you can use feedback hub application to report this bug to Microsoft.
https://support.microsoft.com/en-us/help/4021566/windows-10-send-feedback-to-microsoft-with-feedback-hub-app

**Comment by hyee** [comment]
Sorry for late response, I believe it should be the bug in 17035, and have managed to solve the issue by switching to the lagacy console. I'm closing this ticket, thanks a lot.

**Comment by cbucher** [comment]
*areo* and *legacy* versions shared the same injected code, They call same WIN32 console API.
Switching to legacy console shouldn't solve your issue.
