### ISSUE TITLE
Limited lines displayed

### ISSUE THREAD

**Issue by cruzzer** [cbucher/console#461]
### Expected Behavior

![printscreen_consolez_expected](https://user-images.githubusercontent.com/2527732/34624515-e50e0d78-f255-11e7-8387-244e2ada89f8.PNG)

Whole window can be filled with commands.
(Note: Window in image is small to demonstrate expected behavior. To reproduce error, window must be larger)

### Actual Behavior
![printscreen_consolez_before](https://user-images.githubusercontent.com/2527732/34624962-53ab65b8-f257-11e7-8ec9-d54ac17e518e.PNG)

![printscreen_consolez_after](https://user-images.githubusercontent.com/2527732/34624966-56dade44-f257-11e7-8f3d-9a25b2e94dc4.PNG)

Upon entering the next command, the result will not fill the window, but move everything up. I can confirm this worked with previous version of windows 10 [10.0.10586] on this system. 

### Steps to reproduce
(0. Update Windows 10 to Creators Update  1709)
1. Open ConsoleZ
2. Enter ~70 commands

### Alternative attempts to reproduce
- reset ConsoleZ profile (reproduced)
- attempted to disconnect two monitors (reproduced)
- change shell to cmd or powershell (reproduced)
- Older Version ConsoleZ.x64.1.14.0.15129 (reproduced)
- Older Version ConsoleZ.x64.1.15.0.15253 (reproduced)

Note: Monitors are 1x 2560x1600; 2x1680x1080

------------------------------------------------------------

### Diagnostic Report
ConsoleZ aero amd64 1.18.2.17272
Windows 10 (64 bits) [10.0.16299]
is elevated? no
UAC prefix "Administrator: "
Tab (active): Bash
  View (active): 1. Bash - ~
  is elevated? no
  input code page 850
  output code page 850
  Windows console font
font index: 0
face name: Consolas
font familly: 54 MODERN vector true type
font weight: 400
font size: width=8 height=16
max window size: cols=79 rows=64
  ConsoleZ font
GetFontLanguageInfo returns 262144.
The font contains extra glyphs not normally accessible using the code page.

Monitors 3
+ Flags 1  primary
  DeviceID \\?\DISPLAY#HWP2690#5&3181fea7&0&UID4352#{e6f}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d3}\0001
  DeviceName \\.\DISPLAY1\Monitor0
  DeviceString HP LP3065 Wide LCD Monitor
  StateFlags 3
  Rect (0,0)x(2560,1600)
  Work (0,0)x(2560,1560)
  DPI (per monitor: yes) X=96 Y=96
+ Flags 0
  DeviceID \\?\DISPLAY#ACI22A2#5}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d3}\0005
  DeviceName \\.\DISPLAY2\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (2560,546)x(4240,1596)
  Work (2560,546)x(4240,1596)
  DPI (per monitor: yes) X=96 Y=96
+ Flags 0
  DeviceID \\?\DISPLAY#ACI22A2#8&325ad13&0&UID256#{e6}
  DeviceKey \Registry\Machine\System\CurrentControlSet\Control\Class\{4d}\0003
  DeviceName \\.\DISPLAY5\Monitor0
  DeviceString Generic PnP Monitor
  StateFlags 3
  Rect (-1680,537)x(0,1587)
  Work (-1680,537)x(0,1587)
  DPI (per monitor: yes) X=96 Y=96
System dpi 96
System metrics
  SM_CXSMICON        16
  SM_CYSMICON        16
  SM_CXICON          32
  SM_CYICON          32
  SM_CXVIRTUALSCREEN 5920
  SM_CYVIRTUALSCREEN 1600
  SM_CYVIRTUALSCREEN 1600
Settings file C:\Users\cruiser\AppData\Roaming\Console\console.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<settings lang="auto" icon_size="0">
	<console shell="C:\shell.exe --login" init_dir="C:\user" refresh="25" change_refresh="5" rows="30" columns="80" buffer_rows="1000" buffer_columns="0" start_hidden="0" save_size="0">
		<colors background_text_opacity="255">
			<color id="0" r="0" g="0" b="0"/>
			<color id="1" r="0" g="0" b="128"/>
			<color id="2" r="0" g="150" b="0"/>
			<color id="3" r="0" g="150" b="150"/>
			<color id="4" r="170" g="25" b="25"/>
			<color id="5" r="128" g="0" b="128"/>
			<color id="6" r="128" g="128" b="0"/>
			<color id="7" r="192" g="192" b="192"/>
			<color id="8" r="128" g="128" b="128"/>
			<color id="9" r="0" g="100" b="255"/>
			<color id="10" r="0" g="255" b="0"/>
			<color id="11" r="0" g="255" b="255"/>
			<color id="12" r="255" g="50" b="50"/>
			<color id="13" r="255" g="0" b="255"/>
			<color id="14" r="255" g="255" b="0"/>
			<color id="15" r="255" g="255" b="255"/>
		</colors>
		<cursor style="0" r="255" g="255" b="255"/>
		<background type="0" r="0" g="0" b="0">
			<image file="" relative="0" extend="0" position="0">
				<tint opacity="0" r="0" g="0" b="0"/></image></background></console>
	<appearance>
		<font name="Lucida Console" size="10" extra_width="0" bold="0" italic="0" smoothing="1" bold_intensified="0" italic_intensified="0" ligature="1">
			<color use="0" r="0" g="0" b="0"/></font>
		<window title="ConsoleZ" icon="" main_title_format="?U([%u] )?N({%u} )%m?s( - %s)" tab_title_format="%n. ?U([%u] )?N({%u} )%t?s( - %s)" use_tab_icon="0" use_tab_title="1" trim_tab_titles="20" trim_tab_titles_right="0"/>
		<fullscreen start_in_fullscreen="0" fullscreen_monitor="0">
			<controls show_menu="0" show_toolbar="0" show_searchbar="0" show_statusbar="0" show_tabs="1" hide_single_tab="1" tabs_on_bottom="0" hide_tab_icons="0" hide_tab_close_button="0" hide_tab_new_button="0" show_scrollbars="0"/>
			<transparency type="0" active_alpha="224" inactive_alpha="224" r="49" g="49" b="49" active="1"/></fullscreen>
		<controls show_menu="0" show_toolbar="0" show_searchbar="0" show_statusbar="1" show_tabs="1" hide_single_tab="1" tabs_on_bottom="0" hide_tab_icons="0" hide_tab_close_button="0" hide_tab_new_button="0" show_scrollbars="0"/>
		<styles caption="1" resizable="1" taskbar_button="1" border="1" inside_border="2" split_bar_size="0" tray_icon="0" quake_like="0" quake_animation_time="300" jumplist="0" integrated_ime="0" hide_when_inactive="0" per_monitor_dpi="1" keep_view_theme="0">
			<selection_color r="255" g="255" b="255"/>
			<highlight_color r="191" g="191" b="191"/></styles>
		<position x="-1" y="-1" save_position="0" w="-1" h="-1" save_size="0" z_order="0" dock="-1" snap="-1" save_state="0" state="-1"/>
		<transparency type="0" active_alpha="182" inactive_alpha="225" r="49" g="49" b="49" active="1"/></appearance>
	<behavior>
		<copy_paste copy_on_select="0" clear_on_copy="1" sensitive_copy="1" no_wrap="1" eol_spaces="1" trim_spaces="1" rtf="1" copy_newline_char="0" include_left_delimiter="0" include_right_delimiter="0" left_delimiters=" ([" right_delimiters=" )]"/>
		<scroll page_scroll_rows="0"/>
		<tab_highlight flashes="0" stay_highligted="0"/>
		<environment inherit="1" sync="1"/>
		<focus follow_mouse="0"/>
		<instance allow_multi="1"/>
		<clone use_current_dir="1"/>
		<search match_case="0" match_whole_word="0"/>
		<runas use_credprov="0"/>
		<close allow_closing_last_view="0" exit_on_closing_of_last_tab="1" confirm_closing_multiple_views="1" save_workspace_on_exit="0"/></behavior>

**Comment by cbucher** [comment]
Read FAQ https://github.com/cbucher/console/wiki/FAQ#why-am-i-limited-in-number-of-rowscolumn

**Comment by cruzzer** [comment]
Great, Lucida Console and size 8 worked for me.

Btw, under:
(Help)>Using ConsoleZ>Language Settings: 3. ...."Apply Properties" dialog will appear....
This dialog did not appear for me. Should that still be the case, or has that window been removed?

If removed, I could create a pull request and remove it from the help manual if you like.

**Comment by cbucher** [comment]
This dialog was present in Windows until XP version. I think it has been removed (by Microsoft) in Windows VISTA.
If you want to fix documentation, that will be great.

**Comment by cruzzer** [comment]
Great, I've updated the documentation in #465 .
