### ISSUE TITLE
Crash on WindowsPE64

### ISSUE THREAD

**Issue by logg-sar** [cbucher/console#462]
Hi there
first of all - thank you for this tool. Its great!

I would like to use ConsoleZ on WindowsPE
PE has some limitations, so I only can execute 64-Bit programms. Therefore I removed all 32-Bit files.
On my Server2016 everything runs ok.

On WindowsPE there is an Application Error at starting.

    **_The exeption Integer division by zero._**
    **_(0x00000094) occured in the application at location_**
    **_0x0000000140056C57._**

    **_Click on OK to terminate the program_**

Sorry, no chance to create an dump...
I tried the Version 1.18.2.17272 and 1.18.3.18007

THX

**Comment by cbucher** [comment]
Hi,

https://www.symantec.com/connect/articles/getting-crash-dumps-winpe

Can you copy/install windbg on Windows PE and configure post mortem debuger:
```
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug" /v Debugger /t REG_SZ /d "\"M:\Debug\cdb.exe\" -pv -p %%ld -c \".dump /u /ma M:\Debug\mydump.dmp;.kill;qd\"" /f
reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AeDebug" /v Auto /t REG_SZ /d "1" /f
```
or launch console.exe with windbg.exe/cdb.exe ?

**Comment by cbucher** [comment]
Default font used by ConsoleZ is "Courier New". This font is not available in Windows PE.
You can create a configuration file (console.xml) and set font to "Consolas".

![image](https://user-images.githubusercontent.com/363759/35247121-7b74ff6c-ffc9-11e7-8f0a-ef5b4f87cbb2.png)

**Comment by logg-sar** [comment]
Hi
I somehow missed your first comment. Sorry for that.

And yes - you are absolutely right - I changed the font and its working

Thank you
