### ISSUE TITLE
Needs friendlier text in 'close all BUT this tab'

### ISSUE THREAD

**Issue by blonkm** [cbucher/console#464]
### Expected Behavior
I expect all menu items to address me in a friendly manner.

### Actual Behavior
I am shouted at using CAPITALS

### Steps to reproduce
1. What steps consistently cause this behavior?
looking at the File menu
2. What does someone need to do to recreate the issue?
look at the File menu

Suggestion:
"Close all other tabs"

**Comment by cbucher** [comment]
I copied these menu labels from Notepad ++.
And Notepad ++ has many more users than ConsoleZ.

I don't like when all label is using CAPITALS, but this is a way to highlight a word.

But I'm not a menu designer, if you think you can improve menus, please create a pull request.

**Comment by blonkm** [comment]
I already gave a suggestion: "Close all other tabs"
If you want to copy you should simply copy from the best, people who _do_ use interaction designers. 
BTW I am just a user, not an interaction designer, but I have common sense and have seen interaction designers at work. Right click on a tab in Google Chrome shows 'close other tabs' not 'close all tabs BUT this one'.
