### ISSUE TITLE
relative wallpaper background version selector (feature)

### ISSUE THREAD

**Issue by gfody** [cbucher/console#468]
I like to use my wallpaper as console background image, and I like to use slideshow for my wallpaper. Not every wallpaper is an appropriate background for text though and so the tint color option is handy, but a lot of my wallpapers have nighttime versions and it looks really cool to use those instead of tinting. Here's a couple of examples:

![cap](https://user-images.githubusercontent.com/1146032/37075730-06c978f6-2188-11e8-8320-0e264dfda1a5.gif)

![cap2](https://user-images.githubusercontent.com/1146032/37075736-0c491174-2188-11e8-8b96-ba867d645c99.gif)

..and so I'm thinking a feature where ConsoleZ can select the background version for the current wallpaper. It could be as simple as allowing a placeholder like %currentwallpaper% in the background image path or some simple pattern for specifying the folder naming convention.

**Comment by cbucher** [comment]
Sorry, but I don't understand what you mean by "background version for the current wallpaper".

**Comment by gfody** [comment]
I have pairs of wallpaper like somewallpaper.jpg + somewallpaper_nighttime.jpg, and when somewallpaper.jpg is my background I'd like to use somewallpaper_nighttime.jpg as my console background. I can configure this manually (as in the screenshots) but then when my wallpaper changes to the next image in the slideshow I have to manually change my console background again.

To get it working I would just support a simple placeholder in the background image path, reevaluate it when the wallpaper changes, and fallback on the current wallpaper when the files not found.

**Comment by cbucher** [comment]
Please, try last experimental version.

I modify the code to allow overriding of desktop wallpaper.
If a wallpaper picture is c\dir1\dir2\dir3\photo.jpg, we scan if this pictures exist (in this order):
c\dir1\dir2\dir3.ConsoleZ\photo.jpg
c\dir1\dir2.ConsoleZ\dir3\photo.jpg
c\dir1.ConsoleZ\dir2\dir3\photo.jpg

**Comment by gfody** [comment]
perfect! I tested it out and it works, unfortunately for some reason the experimental build breaks the 'Next desktop background' action from the desktop context menu. As long as ConsoleZ is running clicking 'Next desktop background' does nothing, but if I close ConsoleZ it works again. Same is true for the current head 3e73473.

**Comment by gfody** [comment]
a913d7b fixed it!

**Comment by cbucher** [comment]
Gdi+ was locking pictures. I wrote a workaround.
Please, try last experimental version.

**Comment by gfody** [comment]
works well thanks!

**Comment by ericblade** [comment]
hey @gfody , as an aside, would you mind stating where these images you're using might be available? :-)

**Comment by gfody** [comment]
http://digitalblasphemy.com/
