### ISSUE TITLE
bash shell is too slow compare with git-bash

### ISSUE THREAD

**Issue by timxx** [cbucher/console#472]
Use the bash shell which contains from git package (**C:\Program Files\Git\usr\bin\bash.exe**),
ssh to a Linux host, use [find_src ](https://github.com/timxx/tools/blob/master/find_src) to find the source code, compare to the git-bash (**C:\Program Files\Git\git-bash.exe**), is nearly 5 times slow!

ConsoleZ with bash
> real    0m22.283s
user    0m3.829s
sys     0m1.856s

git-bash
> real    0m5.659s
user    0m3.809s
sys 0m1.810s

When redirect all output to /dev/null, the time is same as git-bash, LoL.
It seems that git-bash also use the same bash. (Is starts the same process)

One strange thing is, when use the bash directly, it is slow as embedded in ConsoleZ. So I don't know is because the bash slow or something wrong with ConsoleZ. But since git-bash use the same bash and it runs very fast...

OS: Win10 64bit with lasted updates.
Bash (from git 2.16.3) and ConsoleZ (build from lastest master) both is 64bit too.

**Comment by cbucher** [comment]
>So I don't know is because the bash slow or something wrong with ConsoleZ

Try to compare without using ConsoleZ. 

ConsoleZ is a Windows console wrapper, it works only with a Windows console application.
*C:\Program Files\Git\git-bash.exe* launches mintty as terminal enumator. mintty is really fast but works only with ANSI escaped applications (try to launch a demo or an application using Windows console API, it will not work).

If I made some tests:
run
```
 find . -name *.cpp -exec cat '{}' \;
```

**C:\Program Files\Git\git-bash.exe** (bash.exe in mintty) : 4 seconds
**C:\Program Files\Git\usr\bin\bash.exe** (bash.exe in Windows console) : 44 seconds
**Windows 10 bash** (bash on Ubuntu on Windows using Windows console) : 8 seconds

Conclusion : the layer that translates ANSI escaping and writes in Windows console is very slow (MINGW problem ?).
