### ISSUE TITLE
better support for controlling the environment vars

### ISSUE THREAD

**Issue by elonderin** [cbucher/console#475]
### Expected Behavior
the environment vars with which i start controlz should be passed to all opened tabs.
see https://msdn.microsoft.com/en-us/library/windows/desktop/ms682653(v=vs.85).aspx

### Actual Behavior
- this is only true for new env vars
- pre-existing env vars (ie defined in ur win account/profile) are reverted to the default settings

### Steps to reproduce
1. open CMD
2. redefine any preexisting var. e.g. set username=my-test
3. define a new env var, e.g. set my-test=1234
4. open consolez from CMD which then opens another CMD

### Diagnostic Report
1. open process explorer from sysinternals
2. investigate the env vars for consolez and the child process CMD
-> my-test=1234 exists in both processes
-> username=my-test is only set like so in consolz process but not in its child CMD

this does not happen with Console-2.00b148-Beta_64bit

### feature request: more env var control
to better control the env vars, u already added the possibility to set own env vars thru the UI :+1: .
however, doing this with the UI is tedious and also if u need the same set of vars u need to do it several times keeping them in sync
i would like to see the following options:

- inherit the env vars from consolez (default)
- use env vars defined for this tab (in addition)
- define env vars via BAT: <path>

Note: u can do option 3 already by starting ur favorite shell program thru another BAT: eg. 
`cmd /c d:\dev\TOOLS\scripts\env.bat && "D:\dev\bin\PortableGit\bin\sh.exe" --login -i`

However, the disadvantage is, that u always have this parent process still hanging around when there really is no need for it.

**Comment by cbucher** [comment]
See `Pick up system or user environment variables changes` option in `Settings/Behaviour/Environment`.
From documentation:
>If checked, environment block is refreshed when WM_SETTINGCHANGE window message is received. This window message is broadcasted when system or user environment variables are updated.
>**If checked, a new environment block is created (You can inherit environment variables, from process which launched ConsoleZ, except those that are defined in system or user environment).** 

Uncheck this option.

**Comment by elonderin** [comment]
thx
well hidden :) 

i keep this open for the feature "define env vars via BAT"

**Comment by cbucher** [comment]
If you want define env via BAT, you have to configure shell command line in tab settings. (`cmd.exe /k varenv.bat`)
There is no need for a feature.
