### ISSUE TITLE
Support of Ctrl+Z to sleep running process (job control)

### ISSUE THREAD

**Issue by ankostis** [cbucher/console#478]
Till v1.18.3.18120, while running a MSYS2/Cygwin bash, the POSIX job-control is not possible:
Pressing **[Ctrl+Z]** does nothing.

In contrast, `mintty` works just fine with that.

Would it be possible to add a `Send CTRL+Z event` item in "Hotkeys"?

**Comment by ankostis** [comment]
Note that it might not be such a a good idea to bind the SIGSTOP this event to `Ctrl+Z` because that is the end-of-stream character for `cmd.exe`.  A complex alternative would be to allow setting this binding per tab (e.g only for bash environments), or simply by leave it by default unbound (advanced users know what to do).

Disclaimer; i have no knowledge wheter Windows can emulate such a signal, and/or how `mintty` has implemented this feature.

**Comment by cbucher** [comment]
If Ctrl-Z is not working, then :
- either you assigned Ctrl-Z to a hotkey in ConsoleZ settings
- or bash cannot read  keyboard inputs correctly
- or Ctrl-Z is not currently handled by bash on Windows

Can you clarify?

**Comment by ankostis** [comment]
- i have not assigned this hotkey
- i believe Bash is NOT handling Ctrl+Z.  
  Under *POSIX*, i think it is the terminal that filters STDIN, 
  and when it detect a Ctrl+Z, it sends the SIGSTOP signal to the process owning the console.
- as said, bash is irrelevant (my mistake to reference *bash* in my OP).

  Now on *Windows* i think there are no *events* mimiking the *POSIX* `SIGSTOP/SIGCONT` signals.
  Obviously `mintty` does some trick here.
  
- Ctrl-Z as explained is not a 

I guess that this is a POSIX-emulation layer issue, and none  of your business,
but still we may be able to workaround this if ConsoleZ sets a `CONSOLEZ_PID` env-var with the owing process.
Then doing [this trick](https://github.com/mintty/mintty/wiki/Tips#terminating-the-foreground-program) with ne "external command" might work.
What do you think?

**Comment by ankostis** [comment]
(reached close enough to the above trick, but may be impossible to go further)

I set an external command to launch with Ctrl+Z: 

    kill -SIGTSTP %P

(`kill` is in my cygpath/msys) and i can see it would work if `%P` was actually the foreground process - unfortunately both `%P` (and `%p`) is always "stuck" to shell's pid.

@cbucher is it possible to get the *current* process owing the console?

---
For reference, i paste this [more civilized cmd](https://stackoverflow.com/a/47448121/548792) which hides the mintty-console spawned to execute the kill-command:

    mintty.exe  /bin/env MSYSTEM=MINGW64 /bin/bash -lc "kill.exe -SIGTSTP %P %p"

**Comment by cbucher** [comment]
>@cbucher is it possible to get the current process owing the console?

If process is not attached to the Windows console, I don't know how to guess this foreground process.

**Comment by cbucher** [comment]
The best solution for a fully functional bash on Windows is to install Ubuntu Bash for Windows 10.

cygwin/MSYS2 bash process spawn another bash processes which are not attached to Windows Console and not related parent-child. There is no way to guess the PID of the current command.
