### ISSUE TITLE
Feature Request: "unsplit" views to own tabs

### ISSUE THREAD

**Issue by tquensen** [cbucher/console#481]
It would be great if you could move a view from a splitted tab to its own tab. Right now, you can connect two separate tabs to a split view, but this action cannot be reversed. "dublicate in new tab" and "detach view" don't really do that

**Comment by cbucher** [comment]
I agree, It makes sense to add this feature.

**Comment by cbucher** [comment]
@tquensen Please, try last experimental version.
A command "Move in New Tab" has been added.

**Comment by cbucher** [comment]
@tquensen Please try last beta version.
https://github.com/cbucher/console/wiki/Downloads
