### ISSUE TITLE
Two different set of colors defaults

### ISSUE THREAD

**Issue by lupien** [cbucher/console#482]
### Expected Behavior
Start  console without an console.xml file or with a console.xml not containing the colors section should use the same colors.

### Actual Behavior
Some of the colors are different (2, 3, 4, 9, 12)

Without a console.xml, the colors are loaded from
  console/setup/config/console.xml
with for example <color id="9" r="0" g="100" b="255"/>
which is 0xFF6400

But loading a console.xml file without the colors section, the colors are initialized from
ConsoleSettings::ConsoleSettings in  console/Console/SettingsHandler.cpp
in there color 9 is set to:  0x FF0000.

These differences are not that big but they did make we wonder is this by design or is it a mistake?

**Comment by cbucher** [comment]
![image](https://user-images.githubusercontent.com/363759/41730614-838fb402-757c-11e8-883c-eeac55764a74.png)

Default colors are Windows console default colors.
Configuration file embedded in console.exe contains a color theme.
It's not a mistake, It's on purpose.
