### ISSUE TITLE
command line -reuse to work with -w specified window

### ISSUE THREAD

**Issue by lgastevens** [cbucher/console#487]
Hi
Would like to be able, from command line, to open multiple (say 2) ConsoleZ windows and then be able to attach tabs to one window or the other, always using command line.

Example, pasting these into Start/Run:

`C:\Program Files\ConsoleZ\Console.exe -reuse -w "Window-A" -t ACLI -n ACLI10`
   This creates a new Window-A with a tab named ACLI10

`C:\Program Files\ConsoleZ\Console.exe -reuse -w "Window-A" -t ACLI -n ACLI11`
   This adds a 2nd tab named ACLI11 to the existing Window-A

`C:\Program Files\ConsoleZ\Console.exe -reuse -w "Window-B" -t ACLI -n ACLI20`
   The desire here would be to open a new Window-B, with a 1st tab named ACLI20; instead we get the tab added to existing Windows-A

`C:\Program Files\ConsoleZ\Console.exe -reuse -w "Window-B" -t ACLI -n ACLI21`
   This adds a 4th tab named ACLI21 to Windows-A; if the previous step had worked, the desire here would have been to add a 2nd tab named ACLI21 to Windows-B 

Maybe there is a way to do this, but I have not found it...
Thanks in advance
Best regards
Ludovico Stevens

**Comment by cbucher** [comment]
Hi,

It's a good idea.
`-w` forces the main window title.
I think it would be better to add a new parameter: `instance name`.
`C:\Program Files\ConsoleZ\Console.exe -reuse -i "Window-A" -t ACLI -n ACLI10`
Instance name can be used in tab/main title with a new syntax variable `%I`.
In this case, main title can be dynamic.

If `reuse` parameter is used without specifying an instance name, should we:
- consider that the instance name is empty (create or reuse an instance named "")
- try to use an existing instance with or without name (how to choose instance ?)

ConsoleZ uses Windows named shared object to handle instance. I can easily create a distinct name per instance, but I have no way to enumerate instances. Unless we restrict instance names to a small known set (one alphabet letter per example) (we find an instance by trying all possible names), I don't know how to implement  "try to use an existing instance with or without name".

**Comment by cbucher** [comment]
@lgastevens
Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by cbucher** [comment]
You can use **%I** in settings, here:
![image](https://user-images.githubusercontent.com/363759/41967208-63959be2-7a01-11e8-98ee-4a75731050ad.png)

Thanks for your feedback.
