### ISSUE TITLE
Attach existing shell console at start 

### ISSUE THREAD

**Issue by belotn** [cbucher/console#493]
Hello,

Is there a way to attach any existing shell within the session when starting consoleZ with a command line switch?

**Comment by cbucher** [comment]
Hello,

No, there is no way actually.
A command line switch will be added.

**Comment by belotn** [comment]
Great news ! Thanks alot !

**Comment by cbucher** [comment]
@belotn Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by belotn** [comment]
Hello,

I can attach existing console when launching console.exe with -attach.

**Comment by cbucher** [comment]
Thx
