### ISSUE TITLE
About the WTL TabbingFramework

### ISSUE THREAD

**Issue by janwilmans** [cbucher/console#499]
it looks like over the years there were quite a few changes to the WTL tabbing framework
https://github.com/cbucher/console/tree/master/TabbingFramework

I also use it and I'm having problems when putting a splitter in a TabbedFrame's tab.
Did you encounter this @cbucher ?

please find me on twitter @janwilmans or @gmail same username

**Comment by cbucher** [comment]
No I don't.
This is my only project in WTL and I wrote my own splitter.
