### ISSUE TITLE
Feature request: Add ability to organize tabs within folders (File >> New Tab >> ... and ConsoleZ Settings >> Tabs)

### ISSUE THREAD

**Issue by RyanMarcotte** [cbucher/console#500]
I have so many predefined tabs in ConsoleZ that the File >> New Tab >> ... menu for selecting one is getting unwieldy :)

Being able to parent tabs within folders would greatly help organize them

**Comment by cbucher** [comment]
Do you think to a complex folder's tree
```
File>
     New Tab>
             folder1>
                     folder2>
                             folder3>
                                     shell1
                                     shell2
                                     shell3
                             folder4>
                                     shell4
                                     shell5
                                     shell6
                     folder5>
                             folder6>
                                     shell7
                                     shell8
                             folder7>
                                     shell9
             folder8>
                     shell10
                     shell11
                     shell12
             shell13
             shell14
             shell15
```
or just one level of folder
```
File>
     New Tab>
             folder1>
                     shell1
                     shell2
                     shell3
             folder2>
                     shell4
                     shell5
                     shell6
             shell7
             shell8
             shell9
```

We can deduce folder from tab's name. For example:
![image](https://user-images.githubusercontent.com/363759/46293594-42b83400-c594-11e8-9615-e7aa9f74cff8.png)

```
File>
     New Tab>
             PS VC10>
                     x86
                     x64
             PS VC17>
                     x86
                     x64
             Admin
```

Or we can add a folder name in Tabs settings. 
![image](https://user-images.githubusercontent.com/363759/46294196-82335000-c595-11e8-9b21-f8da23e87143.png)

**Comment by RyanMarcotte** [comment]
A single folder level is sufficient for my own use, though I'm curious what others think.

Is something preventing the use of a directory tree control for displaying the tabs instead of a list control?  I've pulled the code down but have not done a deep dive on this yet.

![image](https://user-images.githubusercontent.com/1458084/46299609-f30b4580-c55e-11e8-85f4-1c864ebc77cf.png)

**Comment by cbucher** [comment]
>Is something preventing the use of a directory tree control for displaying the tabs instead of a list control?

Nothing but the cost in coding time.
It should be possible to use a tree control.

**Comment by cbucher** [comment]
I coded a simpler version.
I used `/` as text separator in the tab title. Left part is the submenu title.
Consecutive tabs with same submenu title are grouped.

![image](https://user-images.githubusercontent.com/363759/54850109-80497e80-4ce6-11e9-834c-783ed43c00ae.png)

![image](https://user-images.githubusercontent.com/363759/54850588-cc48f300-4ce7-11e9-9748-d43425081f3f.png)

**Comment by RyanMarcotte** [comment]
That's awesome, thanks for that!

**Comment by cbucher** [comment]
@RyanMarcotte Please try last beta version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by cbucher** [comment]
released
