### ISSUE TITLE
{OpenClipboard} Access is denied

### ISSUE THREAD

**Issue by VarunAgw** [cbucher/console#504]
It happens often to me. If you try to paste lot of content, or press paste several times, I get this error.

I assume it's because of concurrency and locks https://stackoverflow.com/a/1859321/2286243

**Comment by cbucher** [comment]
Another application locks the clipboard.
Can be a tool or a virus monitoring your clipboard content.

**Comment by VarunAgw** [comment]
Yes I use a clipboard manager which tries to scrub text when I paste it.

**Comment by VarunAgw** [comment]
Can you look into it someday? A simple retry might solve the issue.

**Comment by cbucher** [comment]
@VarunAgw Please try last beta version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by VarunAgw** [comment]
@cbucher Thanks Christophe!! I have updated it. I will let you know once I find any issue.

**Comment by cbucher** [comment]
released
