### ISSUE TITLE
Tab background position not preserved

### ISSUE THREAD

**Issue by VarunAgw** [cbucher/console#505]
Steps to reproduce:

A) Go to Tabs -> Background -> Choose Bing radio

B) In same dialog, set position to Stretch.

C) Set as default, and click OK

Now Open Settings -> Tabs again. Position is back to Center.

**Comment by cbucher** [comment]
I can reproduce the bug.

**Comment by cbucher** [comment]
@VarunAgw  Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by VarunAgw** [comment]
@cbucher I can still reproduce the bug in experimental release. I tried ConsoleZ.1.18.4.18338.7z\x64\Release

**Comment by cbucher** [comment]
@VarunAgw Sorry I missed a spot.
Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by VarunAgw** [comment]
@cbucher Thanks. It works fine now.
