### ISSUE TITLE
OpenSSH command

### ISSUE THREAD

**Issue by Nawakator** [cbucher/console#506]
Using ConsoleZ 1.18.3.18143

### Expected Behavior
start ssh command

### Actual Behavior
ssh work with powershell (or cmd dos) but not with ConsoleZ.

### Steps to reproduce
First make sur to install App & Features\Optional\Open SHH Client
And check you have C:\Windows\System32\OpenSSH in you environement variables
Simply start ssh

### Diagnostic Report
More stranfly you can go to c:\Windows\System32 and you cannot found OpenSSH folder !
You can create an OpenSSH  ? !
You can copy a file on it, but you cannot found the file on Windows explorer or with cmd or with Standard Powser Shell.
It's totaly strange

**Comment by Nawakator** [comment]
How to generate de diagnostic report ?

**Comment by cbucher** [comment]
https://github.com/cbucher/console/wiki/How-to-Report-an-Issue

**Comment by Nawakator** [comment]
Thanks,
Dump here while try to exeute ssh command :
[dmp1C09.zip](https://github.com/cbucher/console/files/2722921/dmp1C09.zip)

**Comment by cbucher** [comment]
>ConsoleZ aero x86 1.18.3.18143
>Windows 10 (32 bits) [10.0.17134]

Install ConsoleZ 64 bits on 64 bits OS!

Read [this](https://docs.microsoft.com/en-us/windows/desktop/WinProg64/file-system-redirector) to understand why you cannot see `C:\Windows\System32\OpenSSH` when you launch 32 bits application.

**Comment by Nawakator** [comment]
Obviously !
Thanks That work.
