### ISSUE TITLE
colortool does not apply colors

### ISSUE THREAD

**Issue by SimplyKnownAsG** [cbucher/console#508]
### Expected Behavior
I recently discovered `colortool.exe` (https://github.com/Microsoft/console/tree/master/tools/ColorTool). This works well in windows cmd, both "legacy" and with "new console features".

![colortool with Command Prompt](https://user-images.githubusercontent.com/1082590/50787901-99589c80-126c-11e9-9f23-4e0eda0211b6.png)

### Actual Behavior
It either takes no effect, or the colors are different but do not match what they "should."

![colortool with ConsoleZ](https://user-images.githubusercontent.com/1082590/50787820-58608800-126c-11e9-9050-f16c44b8efe2.png)

In this instance, it set the font color to blue:
![image](https://user-images.githubusercontent.com/1082590/50788398-26e8bc00-126e-11e9-8107-440aac183293.png)

### Steps to reproduce
1. Install colortool
2. In ConsoleZ run `colortool solarized_light`. I've also tried `colortool -x solarized_light` and `colortool -b solarized_light`.

Here are my settings via diagnostics: [diagnostics.log](https://github.com/cbucher/console/files/2733986/diagnostics.log). Though, when I look at my console.xml, I do not see the color id's:

```
<tab title="ConsoleZ" use_default_icon="0">
    <console shell="cmd /K %USERPROFILE%\.cmdrc.cmd" init_dir="C:\Users\<me>" priority="2" run_as_user="0" user="" net_only="0" run_as_admin="0"/>
</tab>
```

**Comment by cbucher** [comment]
ConsoleZ uses the colors map defined in tabs settings.

![image](https://user-images.githubusercontent.com/363759/51350235-f2fc6a80-1aa7-11e9-83a8-dddeae52dccf.png)

**Comment by SimplyKnownAsG** [comment]
Seems like this should be closed, plus I'm no longer using windows...
