### ISSUE TITLE
Feature: Saving workspace should also remember which tab had focus

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#509]
Saving the open tabs upon restarting is an excellent feature. Please consider also remembering which tab had focus upon restoring the workspace too. This should be very simple to add - in the autosave.workspace file, maybe introduce a new XML attribute as something like HasFocus="true".

**Comment by cbucher** [comment]
@msmigiel Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

**Comment by msmigiel** [comment]
The focus of the specific tab is being set correctly upon restart, but I notice that the other tabs flash as if there is an alert or something happening on them even though nothing has. The tabs flash until I focus on each of them individually. Ideally what should happen is the focus should be set on the previously selected tab (which is working) but the other tabs should not be flashing until I click on them.

**Comment by cbucher** [comment]
Tab flashes if something is printed when tab has not the focus.
This is the expected behavior.
Perhaps flashing, of a new tab, should be disabled during a starting delay.

**Comment by msmigiel** [comment]
That is what I thought it was, something alerting me if the console scrolls. If not already, there should be a way to disable the flashing and upon startup, I think that nothing should be flashing as everything is "new" and doesn't need to be told to the end user.

**Comment by msmigiel** [comment]
The latest experimental version doesn't flash upon startup - thank you for the fix.

**Comment by cbucher** [comment]
Thx
