### ISSUE TITLE
Virustotal report for ConsoleZ.x64.1.18.3.18143.zip

### ISSUE THREAD

**Issue by GeneKatacoda** [cbucher/console#510]
https://www.virustotal.com/#/file/178e5c1a8cb06768e193e80785b82e343bb7379d94c33105b81550120367936a/detection

Is consolez trustworthy?

**Comment by cbucher** [comment]
duplicate #477 

https://www.virustotal.com/fr/file/178e5c1a8cb06768e193e80785b82e343bb7379d94c33105b81550120367936a/analysis/1548719322/
the big threat: ConsoleWow.exe
code source here : https://github.com/cbucher/console/blob/master/ConsoleWow/ConsoleWow.cpp
It's an opensource project... just one line of code to read and verify...

😞
