### ISSUE TITLE
Feature: Ability to duplicate current tab

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#513]
It would be great if there was the ability via a customizable hotkey (and a menu item) to duplicate the currently focused tab. I'm sure it would be difficult if not impossible to duplicate the contents of the tab, but it should open in the same shell (with the same icon, name, and all that) and be at the same directory location as the original.

**Comment by msmigiel** [comment]
Please disregard, I looked more closely and found the clone functionality.

**Comment by msmigiel** [comment]
Actually, please disregard again. :)

It seems that the Clone tab functionality does not put you in the same directory as the original tab. A cloned tab should be in the same place as the original tab.

**Comment by cbucher** [comment]
@msmigiel Please, try last experimental version.
https://github.com/cbucher/console/wiki/Downloads

menu `Edit/Clone Tab`

**Comment by msmigiel** [comment]
This fix works nicely, thank you.
