### ISSUE TITLE
Upstream console2 -- ctrl+f brings up a find dialog

### ISSUE THREAD

**Issue by tomnor** [cbucher/console#514]
Hi

Sorry for hi-jacking this issue-tracker but it seems there is not much discussion on the upstream console2 development.

I have just installed console2 on a windows 10 machine at work, the version is 2.00.148. When I hit ctrl+f to move cursor forward it brings up a find dialog. Not only is that find seemingly useless, I don't want it to come up in the first place. I find no settings for this among the hotkeys. Also, ctrl+a does not do what I expect (go to the beginning of the line).

I should mention that  doing ctrl+F and ctrl+A does what I expect, meaning ctrl+shift+f and ctrl+shift+a. Does anyone here have an idea how to deal with this?

The ctrl+f problem is observed with a git-bash tab and also with a cmd tab (although then there is no use of ctrl+f, but anyway)

What do you think?

**Comment by cbucher** [comment]
This issue-tracker is reserved to ConsoleZ.
