### ISSUE TITLE
why not add 'select text and copy'  function

### ISSUE THREAD

**Issue by loveJasmine** [cbucher/console#516]

**Comment by cbucher** [comment]
see 'Copy & Paste' options in Settings/Behavior

**Comment by loveJasmine** [comment]
it cannot select part text, just 'select all'

**Comment by cbucher** [comment]
?!?

**Comment by loveJasmine** [comment]
use mouse select part of the text, then copy it,
Is this function available? I cannot do it.

**Comment by cbucher** [comment]
like this
![image](https://user-images.githubusercontent.com/363759/55434799-b6191d80-5598-11e9-99f1-5de60adcbd65.png)

**Comment by fr43nk** [comment]
Have a look under Settings -> Hotkeys -> Mouse
There is a configuration how to do the select.
