### ISSUE TITLE
Enhancement: Bookmark System

### ISSUE THREAD

**Issue by msmigiel** [cbucher/console#517]
I frequently use ConsoleZ in conjunction with Windows 10's ssh implementation and find it works very well. One thing that would make that easier would be to have some sort of bookmarking system to keep frequently used commands in easy reach. For example, in the main menu, have something like:

Bookmarks:
  Linux Machines
       ssh root@1.2.3.4 (start in new window)
       ssh root@.5.6.7.8 (start in new window)
  Programs
      cd ~/derby; ./runDerby.sh; cd - (start in currently focused window)

I know this is a somewhat unusual request and I'm not sure how feasible it would be, but this would make it a lot easier for people who run commands frequently.

**Comment by TheQwerty** [comment]
Take a look at the Snippets feature, it may satisfy your needs here.

**Comment by cbucher** [comment]
Yes, Snippets feature has been coded for this purpose.

**Comment by msmigiel** [comment]
Thanks guys, this might be what I want, but I'm not sure how exactly to use it. 

From searching the web, it seems that ConsoleZ has a Snippets Manager somewhere in the program, but I can't find it. How does one use it? The only way I see now is to manually construct the XML.

https://github.com/cbucher/console/issues/302
https://documentation.help/ConsoleZ/snippets.html

**Comment by cbucher** [comment]
Read the documentation (help):
![image](https://user-images.githubusercontent.com/363759/120923898-4b605100-c6d1-11eb-9c80-37748a9da4e2.png)

You have to create xml files in the snippets directory.
