### ISSUE TITLE
Window resize redraw

### ISSUE THREAD

**Issue by fr43nk** [cbucher/console#518]
Hi,

I'm using the following version of consoleZ

ConsoleZ aero amd64 1.19.0.19104
Windows 7 Service Pack 1 (64 bits) [6.1.7601]

The Problem is as follows:

Resize the window to a smaller size so that the content is "hidden". Release mouse button and resize the window again to bigger width.
The content is lost, there is no redraw or line wrap to fit the content into the available window size.
It doesn't matter what kind of shell I use (bash or cmd.exe)
![before_resize](https://user-images.githubusercontent.com/3279247/56264740-b6143400-60e7-11e9-864e-15aef754792f.PNG)
![after_resize_wide](https://user-images.githubusercontent.com/3279247/56264746-be6c6f00-60e7-11e9-9ce4-8b64a3770e21.PNG)

Best regards

**Comment by cbucher** [comment]
This is the behaviour of the Windows console.
You reproduce the same issue without ConsoleZ.

This behaviour has been modified by Microsoft in Windows 10.
