### ISSUE TITLE
Question: Remember last position & size?

### ISSUE THREAD

**Issue by ValYouW** [cbucher/console#521]
Hi,
Is it possible for Console to remember its last position & size?
Thx

**Comment by ValYouW** [comment]
Inspecting the code I found it is supported via the settings xml.
Just in case if anyone is looking, find your `console.xml` file and under the element `/settings/appearance/position` change the attributes `save_position` and `save_size` to `1`

**Comment by garoto** [comment]
> Would nice to have this in the settings UI

![screenshot-0682-12-07-2019](https://user-images.githubusercontent.com/11768175/61146720-116c7d00-a4b1-11e9-8cbb-03a9db631bd8.png)

**Comment by ValYouW** [comment]
Hilarious! I went over the settings like 1000 times and missed it... I guess the "window size" setting on the "Console" section confused me.
Oh well, at least I practiced my debugging...
