### ISSUE TITLE
Tab menu would be more useful with tab titles

### ISSUE THREAD

**Issue by aperomsik** [cbucher/console#522]
### Expected Behavior
Tab menu lists tab titles of open tabs. So if I have tab display set to display CWD and state in tab titles, I'd want the menu to show:

cwd1 state1 Ctrl +1 
cwd2 state2 Ctrl +2
cwd3 state3 Ctrl +3

### Actual Behavior
Tab menu lists names of open tabs. So I see:

tcsh Ctrl +1 
tcsh Ctrl + 2
tcsh Ctrl + 3

Which doesn't really help me understand which one I want to select.

### Steps to reproduce

configure tab titles ; open multiple tabs; look in tabs menu (RMB > Tabs).

**Comment by cbucher** [comment]
Please try [version >= 1.20.0.21157](https://github.com/cbucher/console/wiki/Downloads).

**Comment by cbucher** [comment]
Available since version 1.20.
