### ISSUE TITLE
It takes very long to start if there are network issues and I am using Bing Wallpaper

### ISSUE THREAD

**Issue by VarunAgw** [cbucher/console#524]
Steps to reproduce:

A) Use Bing Wallpaper

B) Get very unreliable internet (Sometime happens while connecting to a new Wifi which have no internet connectivity).

In such cases, ConsoleZ will wait for the Bing request to timout (which can take up to 30 seconds in some cases). It will not start until the wait timeout is over.

**Comment by Saibamen** [comment]
Fixed in master branch. Please wait for new release

**Comment by cbucher** [comment]
Please try [version >= 1.20.0.21157](https://github.com/cbucher/console/wiki/Downloads).

**Comment by cbucher** [comment]
Available since version 1.20.
