### ISSUE TITLE
ConsoleZ crash while starting if file containing current desktop wallpaper is moved

### ISSUE THREAD

**Issue by VarunAgw** [cbucher/console#526]
Version: Latest Windows 1909 x64

Steps to reproduce

1) Set "C:\Apps\ConsoleZ\448241.jpg" or something similar as Windows desktop wallpaper using right click.

2) Set ConsoleZ to use Windows wallpaper as background

3) Rename the file to "448241.jpg.bk" or something.

4) Start ConsoleZ.

It will not start now anymore without giving any error message. I didn't know why it happened and it was hard to find reason for crash.

I will suggest a fallback background to black color or a helpful error message or maybe use these cached wallpapers instead of original image path https://superuser.com/a/977582/398328

**Comment by Saibamen** [comment]
Fixed in master branch. Please wait for new release

**Comment by cbucher** [comment]
Please try [version >= 1.20.0.21157](https://github.com/cbucher/console/wiki/Downloads).

**Comment by cbucher** [comment]
Available since version 1.20.
