### ISSUE TITLE
feature: increment inside border limit

### ISSUE THREAD

**Issue by confor** [cbucher/console#528]
this is a feature request to increase the "inside border" limit of 10 pixels. i find `10 px` to be a little lacking on high res displays, the text is too close to the border. i haven't changed my dpi, default is fine (96?).

the setting can be found on Edit > Settings > Styles > "Inside border".

i successfully changed `inner_border="10"` to something else by modifying `console.xml`, so i know its a limitation of the settings dialog.

i skimmed through the code and found this line, which seems to be the one that needs changing: [Console/DlgSettingsStyles.cpp#L104](https://github.com/cbucher/console/blob/master/Console/DlgSettingsStyles.cpp#L104)

i don't have a working programming environment to change this myself, and i don't want to submit a blind pull request without making sure the change builds successfully, even if its small.

as this is not a real issue, i intentionally did not provide reproduction steps, report logs or crash dumps. i already searched through the issues, and did not find anyting like this one. as far as i know, this is unrelated to the user shell.

**Comment by cbucher** [comment]
Please try [version >= 1.20.0.21164](https://github.com/cbucher/console/wiki/Downloads).

**Comment by cbucher** [comment]
Available since version 1.20.
