### ISSUE TITLE
How to modify encoding of consoleZ....

### ISSUE THREAD

**Issue by qxdi** [cbucher/console#531]
I want to set the encoding to utf-8,because i use `git log` is garbled.
windows 10

**Comment by garoto** [comment]
I'm thinking `chcp 65001` on the cmd prompt.

**Comment by qxdi** [comment]
> I'm thinking `chcp 65001` on the cmd prompt.

No, this has not effect but it can be used on git bash.

![image](https://user-images.githubusercontent.com/44136546/80053141-cd81ca80-854e-11ea-86d1-a2c1c8c20238.png)
