### ISSUE TITLE
Unable to select with mouse

### ISSUE THREAD

**Issue by raphaelmsx** [cbucher/console#537]
Hi.

I'm unable to select characters to copy to clipboard with the mouse.

Using 1.19.0.19104 with Windows 10 and standard cmd.exe, also I tested in cmd.exe alone, and I can select with mouse.

Thanks.

**Comment by cbucher** [comment]
Verify your settings.

**Comment by raphaelmsx** [comment]
I just downloaded latest version and installed in a fresh vm to test with default settings, and it's not working.

To which settings you are referring to? I cannot find.

Thanks.

**Comment by cbucher** [comment]
![image](https://user-images.githubusercontent.com/363759/107277427-a7350900-6a54-11eb-8c51-487320b1851b.png)

**Comment by cbucher** [comment]
By default mouse text selection is set with : SHIFT+left button.

**Comment by raphaelmsx** [comment]
Hi, 

I unchecked the SHIFT option and it's working the way I like now.

I couldn't find this option before, thanks very much for your help!!
