### ISSUE TITLE
Importing settings to a new installation

### ISSUE THREAD

**Issue by raphaelmsx** [cbucher/console#538]
Hi.

I copied console.xml from %APPDATA%\console to a new computer, and it does not load the settings.

Also tried to copy to consolez install location, and also turning on/off "save settings to user directory", to no avail.

Thanks.

**Comment by cbucher** [comment]
Are you sure your settings file has not been altered during copy ?

**Comment by raphaelmsx** [comment]
It's not being altered, I did this many times, with two physical computers, and also two fresh installed virtual machines.

Thanks.

**Comment by raphaelmsx** [comment]
Hi again.

I just did and it's working now, I definitely did something wrong before.

Thanks very much for your help, and also thanks for a wonderful program!
