### ISSUE TITLE
how do you change the prompt!?

### ISSUE THREAD

**Issue by iansebryk** [cbucher/console#541]
don't know where else to ask this, it's not in the docs.  just want to replace the prompt to the one i typically use in Linux but have no idea where this is set/configured.  have tried .bashrc, .profile, to no avail.  if you can tell me, i'd be happy to write up and entry for the docs because i'm sure more people are wanting to do this.

**Comment by elieux** [comment]
Hi.  ConsoleZ doesn't do anything with the prompt, it's a *terminal*.  From your question, I assume you haven't changed your default *shell*, which on Windows is Cmd.  See https://ss64.com/nt/prompt.html for how to change it.
