### ISSUE TITLE
How to quake like drop down animation ?

### ISSUE THREAD

**Issue by rosolino** [cbucher/console#91]
Hello.
I set Hot key [Activate Console(Global)] to [Ctl+Alt+F11] and check [Quake Like] .
When I push [Ctl+Alt+F11],Consolez window that was hidden only be displayed on the front,I did not seen the drop-down animation.
How do I  see a drop-down animation?

**Comment by lcota** [comment]
Unable to get quake animation . does aero need to be enabled?

**Comment by cbucher** [comment]
from the documentation:

**Quake like**

If checked, ConsoleZ uses a Quake-style console effect when showing or hiding.
This animation requires a global hotkey to hide/show the application. Assign a hotkey to the command *Activate ConsoleZ (global)* in *Settings/HotKeys*.
Window must be docked to a screen edge (select a *Docking* value, other than none, in *Settings/Appearance*).
If AERO is active, non-client area is not supported. Consider to uncheck *Caption* and *Resizable*.

**Comment by calvimor** [comment]
I can see animation, thank you!
if i config quake animation like @cbucher  said, does it mean the window can not maximized?

**Comment by cbucher** [comment]
Yes, if you uncheck Resizable, you cannot resize the window and so you cannot maximize.

You can try with this option checked, but that should be ugly during animation.

You can always go to full screen.
You can also specify initial position and size into settings.
